### ISSUE TITLE
test_TSA is not stable, sometimes it fails to retrive the route some vm 

### ISSUE THREAD

**Issue by JibinBao** [sonic-net/sonic-mgmt#10119]
**Description**

test_TSA is not stable, sometimes it fail to retrive the route some vm.
The root cause might be related to there are some conflicts when running multi-tasks(multi-threads). 

**Steps to reproduce the issue:**
1. run Test_TSA on t1-64-lag topo many times. it fail about 1 time per 3 times.

**Describe the results you received:**
   ```
 def test_TSA(duthosts, enum_rand_one_per_hwsku_frontend_hostname, ptfhost,
                 nbrhosts_to_dut, bgpmon_setup_teardown, traffic_shift_community, tbinfo):
        """
        Test TSA
        Verify all routes are announced to bgp monitor, and only loopback routes are announced to neighs
        """
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        try:
            # Issue TSA on DUT
            duthost.shell("TSA")
            # Verify DUT is in maintenance state.
            pytest_assert(TS_MAINTENANCE == get_traffic_shift_state(duthost),
                          "DUT is not in maintenance state")
            # For T2 - TSA command sets up policies where only loopback address on the iBGP peers on the same linecard
            # are exchanged between the asics. Also, since bgpmon is iBGP as well, routes learnt from other asics on other
            # linecards are also not going to be advertised to bgpmon.
            # So, cannot validate all routes are send to bgpmon on T2.
            if tbinfo['topo']['type'] != 't2':
                pytest_assert(get_routes_not_announced_to_bgpmon(duthost, ptfhost, bgpmon_setup_teardown['namespace']) == [],
                            "Not all routes are announced to bgpmon")
    
>           pytest_assert(verify_only_loopback_routes_are_announced_to_neighs(duthost, nbrhosts_to_dut, traffic_shift_community),
                          "Failed to verify routes on nbr in TSA")

bgpmon_setup_teardown = {'local_addr': '20.0.0.0/31', 'local_intf': 'PortChannel1023', 'loopback_ip': u'10.1.0.32', 'namespace': None, ...}
nbrhosts_to_dut = {'ARISTA01T0': <EosHost VM1905>, 'ARISTA01T2': <EosHost VM1901>, 'ARISTA02T0': <EosHost VM1906>, 'ARISTA03T0': <EosHost VM1907>, ...}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7fda38e818d0>
traffic_shift_community = u'12345:12345'

bgp/test_traffic_shift.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bgp/test_traffic_shift.py:303: in verify_only_loopback_routes_are_announced_to_neighs
    return verify_loopback_route_with_community(dut_host, neigh_hosts, 4, community) and \
bgp/test_traffic_shift.py:285: in verify_loopback_route_with_community
    routes_on_all_nbrs = parse_routes_on_neighbors(dut_host, neigh_hosts, ip_ver)
bgp/test_traffic_shift.py:193: in parse_routes_on_neighbors
    routes_on_all_nbrs = parse_routes_on_eos(dut_host, neigh_hosts, ip_ver)
bgp/test_traffic_shift.py:187: in parse_routes_on_eos
    all_routes = parallel_run(parse_routes_process, (), {}, neigh_hosts.values(), timeout=240, concurrent_tasks=8)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

target = <function parse_routes_process at 0x7fda2b391950>, args = ()
kwargs = {'node': <EosHost VM1917>, 'results': <DictProxy object, typeid 'dict' at 0x7fda28ec9510>}
nodes_list = [<EosHost VM1903>, <EosHost VM1924>, <EosHost VM1915>, <EosHost VM1914>, <EosHost VM1902>, <EosHost VM1921>, ...]
timeout = 240, concurrent_tasks = 8, init_result = None
```

Some detailed infos:
`09:47:06 base._run                                L0083 DEBUG  | /root/mars/workspace/sonic-mgmt/tests/bgp/test_traffic_shift.py::parse_routes_process#166: [VM1917] AnsibleModule::eos_command Result => {"msg": "Unexpected failure during module execution.", "failed": true, "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py\", line 145, in run\n    res = self._execute()\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py\", line 664, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/eos.py\", line 105, in run\n    result = super(ActionModule, self).run(task_vars=task_vars)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/network.py\", line 48, in run\n    result = super(ActionModule, self).run(task_vars=task_vars)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/normal.py\", line 46, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py\", line 809, in _execute_module\n    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py\", line 203, in _configure_module\n    environment=final_environment)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/executor/module_common.py\", line 1023, in modify_module\n    environment=environment)\n  File \"/usr/local/lib/python2.7/dist-packages/ansible/executor/module_common.py\", line 878, in _find_module_utils\n    os.rename(cached_module_filename + '-part', cached_module_filename)\nOSError: [Errno 2] No such file or directory\n", "_ansible_no_log": false, "stdout": ""}`

**Describe the results you expected:**
Case is table.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@JibinBao please respond to the comments in the fix PR. Thank you!

**Comment by JibinBao** [comment]
> @JibinBao please respond to the comments in the fix PR. Thank you!

Done
