### ISSUE TITLE
[DualTor][QoS Remapping] The test case test_pfc_pause_extra_lossless_standby could fail if we run the dualtor topology on a platform who has more than 32 ports

### ISSUE THREAD

**Issue by congh-nvidia** [sonic-net/sonic-mgmt#10139]
**Description**
The test case test_pfc_pause_extra_lossless_standby could fail if we run the dualtor topology on a platform who has more than 32 ports.

Why this could happen:

- The test firstly sends a packet to one of the uplink port and finds the actual egress port of the bounced back packet. After it gets the number of the receiving ptf port, it uses the number to find the corresponding interface on the dut by searching the ptf port number in mg_facts['minigraph_ptf_indices'].

- If the actual egress port is Ethernet120 for example(it's determined by the ecmp), the ptf port number is 32 in dualtor topology on the upper tor(for example, the dut is randomly selected in the test).

- And the mg_facts['minigraph_ptf_indices'] is like this:

[(u'Ethernet8', 2), (u'Ethernet0', 0), (u'Ethernet4', 1), (u'Ethernet248', 62), (u'Ethernet244', 61), **(u'Ethernet128', 32)**, (u'Ethernet240', 60), (u'Ethernet40', 10), (u'Ethernet200', 50), (u'Ethernet124', 34), (u'Ethernet204', 51), **(u'Ethernet120', 32),** (u'Ethernet208', 52), (u'Ethernet160', 40), (u'Ethernet164', 41), (u'Ethernet76', 19), (u'Ethernet72', 18), (u'Ethernet32', 8), (u'Ethernet36', 9), (u'Ethernet136', 34), (u'Ethernet132', 33), (u'Ethernet232', 58), (u'Ethernet172', 43), (u'Ethernet236', 59), (u'Ethernet176', 44), (u'Ethernet64', 16), (u'Ethernet60', 15), (u'Ethernet20', 5), (u'Ethernet24', 6), (u'Ethernet180', 45), (u'Ethernet44', 11), (u'Ethernet184', 46), (u'Ethernet188', 47), (u'Ethernet108', 27), (u'Ethernet100', 25), (u'Ethernet212', 53), (u'Ethernet104', 26), (u'Ethernet228', 57), (u'Ethernet96', 24), (u'Ethernet148', 37), (u'Ethernet92', 23), (u'Ethernet28', 7), (u'Ethernet220', 55), (u'Ethernet144', 36), (u'Ethernet52', 13), (u'Ethernet224', 56), (u'Ethernet140', 35), (u'Ethernet56', 14), (u'Ethernet16', 4), (u'Ethernet12', 3), (u'Ethernet196', 49), (u'Ethernet192', 48), (u'Ethernet168', 42), (u'Ethernet116', 30), (u'Ethernet80', 20), (u'Ethernet112', 28), (u'Ethernet84', 21), (u'Ethernet152', 38), (u'Ethernet156', 39), (u'Ethernet48', 12), (u'Ethernet216', 54), (u'Ethernet68', 17), (u'Ethernet88', 22), (u'Ethernet252', 63)]

- We can see the ptf port number of Ethernet128 is also 32 , and because Ethernet128 is in front of Ethernet120 in the list, the test wil consider Ethernet128 as the actual egress port and send pfc storm to it, which will cause the test to fail.

The root cause is we replace the ptf ports number of the uplink ports for the dualtor topology. And if we have more ports in the platform than defined in the topology, we will face this issue.

**Steps to reproduce the issue:**
1. Deploy the dualtor topology on a platform who has more than 32 physical ports(such as Mellanox 4600C)
2. Run the test case tests/qos/test_tunnel_qos_remap.py::test_pfc_pause_extra_lossless_standby
3. There is a chance to see this issue if meets the conditions in the description.

**Describe the results you received:**
In the test log:
```
Failed: The queue 6 for port Ethernet128 counter increased unexpectedly: Received packet that we expected not to receive on device 0, port 32.
========== RECEIVED ==========
0000  46 4B FE F9 97 48 1C 34 DA C9 60 00 08 00 45 19  FK...H.4..`...E.
0010  00 6A 00 00 40 00 FF 04 67 34 0A 01 00 20 0A 01  .j..@...g4... ..
0020  00 21 45 11 00 56 00 01 00 00 3F 06 B8 E4 01 01  .!E..V....?.....
0030  01 01 C0 A8 00 02 04 D2 00 50 00 00 00 00 00 00  .........P......
0040  00 00 50 02 20 00 94 88 00 00 74 65 73 74 73 2E  ..P. .....tests.
0050  71 6F 73 2E 74 65 73 74 5F 74 75 6E 6E 65 6C 5F  qos.test_tunnel_
0060  71 6F 73 5F 72 65 6D 61 70 20 74 65 73 74 73 2E  qos_remap tests.
0070  71 6F 73 2E 74 65 73 74                          qos.test
==============================
```
We can see the Ethernet128 is not one of the uplink ports:
```
admin@r-tigon-20:~$ show interface status
     Interface            Lanes    Speed    MTU    FEC    Alias            Vlan    Oper    Admin             Type    Asym PFC
--------------  ---------------  -------  -----  -----  -------  --------------  ------  -------  ---------------  ----------
     Ethernet0          0,1,2,3     100G   9100     rs     etp1          routed    down     down  QSFP28 or later         off
     Ethernet4        8,9,10,11     100G   9100     rs     etp2           trunk      up       up  QSFP28 or later         off
     Ethernet8      16,17,18,19     100G   9100     rs     etp3           trunk      up       up  QSFP28 or later         off
    Ethernet12      24,25,26,27     100G   9100     rs     etp4           trunk      up       up  QSFP28 or later         off
    Ethernet16      32,33,34,35     100G   9100     rs     etp5           trunk      up       up  QSFP28 or later         off
    Ethernet20      40,41,42,43     100G   9100     rs     etp6           trunk      up       up  QSFP28 or later         off
    Ethernet24      48,49,50,51     100G   9100     rs     etp7           trunk      up       up  QSFP28 or later         off
    Ethernet28      56,57,58,59     100G   9100     rs     etp8           trunk      up       up  QSFP28 or later         off
    Ethernet32      64,65,66,67     100G   9100     rs     etp9           trunk      up       up  QSFP28 or later         off
    Ethernet36      72,73,74,75     100G   9100     rs    etp10           trunk      up       up  QSFP28 or later         off
    Ethernet40      80,81,82,83     100G   9100     rs    etp11           trunk      up       up  QSFP28 or later         off
    Ethernet44      88,89,90,91     100G   9100     rs    etp12           trunk      up       up  QSFP28 or later         off
    Ethernet48      96,97,98,99     100G   9100     rs    etp13           trunk      up       up  QSFP28 or later         off
    Ethernet52  104,105,106,107     100G   9100     rs    etp14           trunk      up       up  QSFP28 or later         off
    Ethernet56  112,113,114,115     100G   9100     rs    etp15           trunk      up       up  QSFP28 or later         off
    Ethernet60  120,121,122,123     100G   9100     rs    etp16           trunk      up       up  QSFP28 or later         off
    Ethernet64  128,129,130,131     100G   9100     rs    etp17           trunk      up       up  QSFP28 or later         off
    Ethernet68  136,137,138,139     100G   9100     rs    etp18           trunk      up       up  QSFP28 or later         off
    Ethernet72  144,145,146,147     100G   9100     rs    etp19           trunk      up       up  QSFP28 or later         off
    Ethernet76  152,153,154,155     100G   9100     rs    etp20           trunk      up       up  QSFP28 or later         off
    Ethernet80  160,161,162,163     100G   9100     rs    etp21           trunk      up       up  QSFP28 or later         off
    Ethernet84  168,169,170,171     100G   9100     rs    etp22           trunk      up       up  QSFP28 or later         off
    Ethernet88  176,177,178,179     100G   9100     rs    etp23           trunk      up       up  QSFP28 or later         off
    Ethernet92  184,185,186,187     100G   9100     rs    etp24           trunk      up       up  QSFP28 or later         off
    Ethernet96  192,193,194,195     100G   9100     rs    etp25           trunk      up       up  QSFP28 or later         off
   Ethernet100  200,201,202,203     100G   9100     rs    etp26          routed    down     down  QSFP28 or later         off
   Ethernet104  208,209,210,211     100G   9100     rs    etp27          routed    down     down  QSFP28 or later         off
   Ethernet108  216,217,218,219     100G   9100     rs    etp28          routed    down     down  QSFP28 or later         off
   Ethernet112  224,225,226,227     100G   9100     rs    etp29  PortChannel101      up       up  QSFP28 or later         off
   Ethernet116  232,233,234,235     100G   9100     rs    etp30  PortChannel102      up       up  QSFP28 or later         off
   Ethernet120  240,241,242,243     100G   9100     rs    etp31  PortChannel103      up       up  QSFP28 or later         off
   Ethernet124  248,249,250,251     100G   9100     rs    etp32  PortChannel104      up       up  QSFP28 or later         off
   Ethernet128  256,257,258,259     100G   9100     rs    etp33          routed    down     down  QSFP28 or later         off
   Ethernet132  264,265,266,267     100G   9100     rs    etp34          routed    down     down  QSFP28 or later         off
   Ethernet136  272,273,274,275     100G   9100     rs    etp35          routed    down     down  QSFP28 or later         off
   Ethernet140  280,281,282,283     100G   9100     rs    etp36          routed    down     down  QSFP28 or later         off
   Ethernet144  288,289,290,291     100G   9100     rs    etp37          routed    down     down  QSFP28 or later         off
   Ethernet148  296,297,298,299     100G   9100     rs    etp38          routed    down     down  QSFP28 or later         off
   Ethernet152  304,305,306,307     100G   9100     rs    etp39          routed    down     down  QSFP28 or later         off
   Ethernet156  312,313,314,315     100G   9100     rs    etp40          routed    down     down  QSFP28 or later         off
   Ethernet160  320,321,322,323     100G   9100     rs    etp41          routed    down     down  QSFP28 or later         off
   Ethernet164  328,329,330,331     100G   9100     rs    etp42          routed    down     down  QSFP28 or later         off
   Ethernet168  336,337,338,339     100G   9100     rs    etp43          routed    down     down  QSFP28 or later         off
   Ethernet172  344,345,346,347     100G   9100     rs    etp44          routed    down     down  QSFP28 or later         off
   Ethernet176  352,353,354,355     100G   9100     rs    etp45          routed    down     down  QSFP28 or later         off
   Ethernet180  360,361,362,363     100G   9100     rs    etp46          routed    down     down  QSFP28 or later         off
   Ethernet184  368,369,370,371     100G   9100     rs    etp47          routed    down     down  QSFP28 or later         off
   Ethernet188  376,377,378,379     100G   9100     rs    etp48          routed    down     down  QSFP28 or later         off
   Ethernet192  384,385,386,387     100G   9100     rs    etp49          routed    down     down  QSFP28 or later         off
   Ethernet196  392,393,394,395     100G   9100     rs    etp50          routed    down     down  QSFP28 or later         off
   Ethernet200  400,401,402,403     100G   9100     rs    etp51          routed    down     down  QSFP28 or later         off
   Ethernet204  408,409,410,411     100G   9100     rs    etp52          routed    down     down  QSFP28 or later         off
   Ethernet208  416,417,418,419     100G   9100     rs    etp53          routed    down     down  QSFP28 or later         off
   Ethernet212  424,425,426,427     100G   9100     rs    etp54          routed    down     down  QSFP28 or later         off
   Ethernet216  432,433,434,435     100G   9100     rs    etp55          routed    down     down  QSFP28 or later         off
   Ethernet220  440,441,442,443     100G   9100     rs    etp56          routed    down     down  QSFP28 or later         off
   Ethernet224  448,449,450,451     100G   9100     rs    etp57          routed    down     down  QSFP28 or later         off
   Ethernet228  456,457,458,459     100G   9100     rs    etp58          routed    down     down  QSFP28 or later         off
   Ethernet232  464,465,466,467     100G   9100     rs    etp59          routed    down     down  QSFP28 or later         off
   Ethernet236  472,473,474,475     100G   9100     rs    etp60          routed    down     down  QSFP28 or later         off
   Ethernet240  480,481,482,483     100G   9100     rs    etp61          routed    down     down  QSFP28 or later         off
   Ethernet244  488,489,490,491     100G   9100     rs    etp62          routed    down     down  QSFP28 or later         off
   Ethernet248  496,497,498,499      50G   9100    N/A    etp63          routed    down     down  QSFP28 or later         off
   Ethernet252  504,505,506,507      50G   9100    N/A    etp64          routed    down     down  QSFP28 or later         off
PortChannel101              N/A     100G   9100    N/A      N/A          routed      up       up              N/A         N/A
PortChannel102              N/A     100G   9100    N/A      N/A          routed      up       up              N/A         N/A
PortChannel103              N/A     100G   9100    N/A      N/A          routed      up       up              N/A         N/A
PortChannel104              N/A     100G   9100    N/A      N/A          routed      up       up              N/A         N/A
```
**Describe the results you expected:**
Test should pass even if we run the test with dualtor topology on a 64 ports(or more) platforms.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by congh-nvidia** [comment]
Hi @rbpittman, this issue is about the new qos remapping test case you added in PR (https://github.com/sonic-net/sonic-mgmt/pull/9318), and I have made a draft fix in (https://github.com/sonic-net/sonic-mgmt/pull/10140), could you please check and review? If you are OK with the fix, I will upstream it. Thanks.

**Comment by rbpittman** [comment]
Hi @congh-nvidia, thanks for filing the issue. I've also run into this, but figured it was an anomaly in our test setups, good to see it's common across platforms. 

I was wondering what caused the port_name->ptf_index map to have multiple port_name's that map to the same ptf_index. Discovered there's a place where the mapping is constructed as the composition of two maps, but is initialized as well, causing duplicates to occur. 

Filed #10144 to see if you have any thoughts. This fixed the issue for me locally, but I was concerned about how this could affect other platforms given odd usage of try-excepts in the surrounding code.

**Comment by congh-nvidia** [comment]
Hi @rbpittman , your fix looks good to me, the test passed on our testbed with it. Thanks!

**Comment by rbpittman** [comment]
Thanks for verifying! Requesting review or assignee from @bingwang-ms on the PR.

**Comment by bingwang-ms** [comment]
Thanks @congh-nvidia @rbpittman catching this issue. It's a great catch.
Change in https://github.com/sonic-net/sonic-mgmt/pull/10144 makes sense to me. The map `mg_facts['minigraph_port_indices']`  contains all front panel ports, including both admin up and admin down ports. However, only the ptf index of ports in `tbinfo['topo']['ptf_map'][str(dut_index)]` are updated into map `mg_facts['minigraph_ptf_indices']`. That may cause ptf index conflict. 
My concern for this change is, the admin down ports will be removed from map `mg_facts['minigraph_ptf_indices']`. I'm not 100% sure if we have any test case that queries the index for admin down ports (probably not). 
Since it's a pretty fundamental change, I suggest @wangxin help review this change.
Another work around is, we add the disabled port into `host_interfaces` section as well in the topo definition file. All port index in the map `mg_facts['minigraph_ptf_indices']` will also be updated in this way.
Please let me know if I miss anything. Thanks!

**Comment by rbpittman** [comment]
As I understand your latter suggestion, it'd involve the same change but with extra entries in the ptf_map so all mappings can be both present and unique. Not sure how/where this would be added.

Regardless, it might be good to just not have any down ports if they're not needed. 

cc @wangxin for assistance
