### ISSUE TITLE
T2: route/test_route_flow_counter.py / get_route_flow_counter_capability to be fixed for Multi-asic support

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#10203]
**Description**

The route/test_route_flow_counter.py script is failing for multi-asic , the CLI needs to have namespace prefixed part of the CLI. the proc get_route_flow_counter_capability to be updated for multi-asic.

cisco@sfd-lt2-lc0:~$ sudo sonic-db-cli STATE_DB HGET "FLOW_COUNTER_CAPABILITY_TABLE|route" support

        route_flow_counter_capability = [] # Use a list to store the capability

        if not wait_until(CAPABILITY_WAIT_TIME_IN_SEC, CAPABILITY_CHECK_INTERVAL_IN_SEC, 0, get_route_flow_counter_capability, rand_selected_du

t, route_flow_counter_capability):

>           pytest_assert(False, 'Failed to get route flow counter capability')

E           Failed: Failed to get route flow counter capability
**Steps to reproduce the issue:**
1.Running route/test_route_flow_counter.py on T2/multi-asic setup
2.
3.

**Describe the results you received:**
The CLI returns "" string.
root@sfd-lt2-lc0:/home/cisco# sonic-db-cli STATE_DB HGET "FLOW_COUNTER_CAPABILITY_TABLE|route" support

root@sfd-lt2-lc0:/home/cisco# 

**Describe the results you expected:**
Scripts needs to be modified to support multi-asic check to have namespace before the CLI.

root@sfd-lt2-lc0:/home/cisco# ip netns exec asic2 sonic-db-cli STATE_DB HGET "FLOW_COUNTER_CAPABILITY_TABLE|route" support
false
root@sfd-lt2-lc0:/home/cisco# 

@abdosi @vperumal

**Comment by yxieca** [comment]
@judyjoseph @arlakshm do you think separating chassis test cases to a different sub-folder or separate files (sharing the common test infrastructure code/flow, but differentiate specific implementations)?
