### ISSUE TITLE
route/test_route_flow_counter.py fails on supervisor of modular DUT

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#10208]
**Description**

route/test_route_flow_counter.py, recently enabled by PR https://github.com/sonic-net/sonic-mgmt/pull/8732, errors on the supervisor of a modular DUT.

The issue is that the supervisor lacks the FLOW_COUNTER_CAPABILITY_TABLE in STATE_DB that is used to determine whether or not the test should run (by the `get_route_flow_counter_capability()` funct in tests/flow_counter/flow_counter_utils.py).

**Steps to reproduce the issue:**
1. Run route/test_route_flow_counter.py on modular DUT
2.
3.

**Describe the results you received:**
```
E           Failed: Failed to get route flow counter capability
```
when run on the supervisor

**Describe the results you expected:**
Test should not run on the supervisor since it doesn't have have FLOW_COUNTER information in STATE_DB (including the FLOW_COUNTER_CAPABILITY_TABLE the test is querying to determine support).

**Additional information you deem important:**

**Comment by abdosi** [comment]
@wenyiz2021 will look into this,

**Comment by arlakshm** [comment]
These tests are skipped with this PR https://github.com/sonic-net/sonic-mgmt/pull/10314. Closing this issue

**Comment by arista-nwolfe** [comment]
PR for 202205 is pending:
https://github.com/sonic-net/sonic-mgmt/pull/10891
