### ISSUE TITLE
t2 topology is missing a portchannel on asic1 of multi-asic linecard - lack of test coverage

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#10399]
**Description**

The current t2 topology definition, forms all 8 of the portchannels in the first 18 interfaces of the linecard (2 of these are specified as routed ports), which will typically result in all the portchannels on asic0 of a multi-asic linecard and none on asic1.

Thus sonic-mgmt is missing test coverage for portchannels on asic1 of multi-asic linecards, which we should address by updating topo_t2.

Additionally this is causing "'PORTCHANNEL' is undefined" error in test_crm.py::test_acl_entry due to the `sonic-cfggen` command used by the test to verify which asic the portchannel is on:

e.g. on asic1 (no portchannels)
```
root@cmp227-4:~# sudo sonic-cfggen -n asic1 -v "PORTCHANNEL.keys()" -d
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 443, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 416, in main
    print(template.render(data))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'PORTCHANNEL' is undefined
```
vs on asic0 (with all the portchannels)
```
root@cmp227-4:~# sudo sonic-cfggen -n asic0 -v "PORTCHANNEL.keys()" -d
dict_keys(['PortChannel1010', 'PortChannel1012', 'PortChannel1016', 'PortChannel102', 'PortChannel1020', 'PortChannel104', 'PortChannel106', 'PortChannel108'])
```
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Comment by judyjoseph** [comment]
@veronica-arista I have a PR https://github.com/sonic-net/sonic-mgmt/issues/10342 raised to fix this PORTCHANNEL issue

**Comment by veronica-arista** [comment]
> @veronica-arista I have a PR #10342 raised to fix this PORTCHANNEL issue, Can you check if this fixes the issue

Thank you!  I tried out your fix and it works for me.

I think it would be worthwhile to fix the portchannel_on_asic() method as well, to prevent these kinds of potential problems appearing in other places where it’s used.  I opened a PR for this: 
https://github.com/sonic-net/sonic-mgmt/pull/10482
