### ISSUE TITLE
[chassis] [voq] voq_helper asicname check fail because of upper/lowercase difference

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-mgmt#10473]
**Description**
            # supervisor checks
            for entry in voq_dump:
                if entry.endswith('|%s' % neighbor) or entry.endswith(':%s' % neighbor):
    
                    if "portchannel" in local_port.lower():
                        slotname = cfg_facts['DEVICE_METADATA']['localhost']['hostname']
                        asicname = cfg_facts['DEVICE_METADATA']['localhost']['asic_name']
                    else:
                        slotname = sysport_info['slot']
                        asicname = sysport_info['asic']
    
                    logger.debug("Neigh key: %s, slotnum: %s", entry, slotname)
                    pytest_assert("|%s|" % slotname in entry,
                                  "Slot for %s does not match %s" % (entry, slotname))
                    pytest_assert("|%s:" % local_port in entry or "|%s|" % local_port in entry,
                                  "Port for %s does not match %s" % (entry, local_port))
                    pytest_assert("|%s|" % asicname in entry,
>                                 "Asic for %s does not match %s" % (entry, asicname))
E                   Failed: Asic for SYSTEM_NEIGH|lc3-1|Asic0|Ethernet72|fc00::ca does not match ASIC0

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wenyiz2021** [comment]
the issue no longer persist in latest 202205.54 image
minigraph change was done

**Comment by rlhui** [comment]
@wenyiz2021  to close
