### ISSUE TITLE
TC Issue: container_checker/test_container_checker.py::test_container_checker[<duthost>-1-swss] fails as there is no condition to check if the container is in running state before stopping it.

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-mgmt#10475]
**Description**
The Test Case container_checker/test_container_checker.py::test_container_checker[<duthost>-swss] fails as it doesn't check in pretest if all the enabled container are up and running before executing the the test case.

**Details**
Prior to the execution of the aforementioned test case, the test_container_checker.py::test_container_checker[<duthost>-teamd] test case is invoked. In our specific use case, the  (DHCP) test case is skipped. Instead, the test case stops the "teamd" container and subsequently monitors the logs for any alert messages. Since "teamd" is brought to a stop, it affects not only the "swss" container but also other containers, necessitating their restart.
Following this sequence of events, the "swss" test case initiates without conducting a prior check of the operational status of the "swss" and other associated containers.
In the test case, the command "asic.stop_service(service_name)" is executed, with the purpose of determining whether the container is stopped or not. If the container is indeed operational, it is subsequently stopped. In the event that the container is already in a stopped state, the action taken is limited to logging the fact that the container is already stopped, 

Since the "swss" container was stopped in the preceding test case and is presently in the process of starting, it is not yet fully operational. Consequently, at the time of executing the command, the test case verifies the status of the container. However, the container may have progressed to a running state during the execution of the check, which deviates from the expected behavior of the stopped state.
In the current context, the issue at hand is primarily a matter of timing. The problem arises during the execution of the stop command, as the container is transitioning from a starting state to a running state.
This assertion in the container's state during the execution of the status check creates a a failure scenario.
 

**Describe the results you received:**
The Issue is observed on a T2 Max Chassis which is fully loaded.
The Test Case Fails in some scenario where swss and other associated container does not progress to running state in limited time which is not asserted after stopped by preceding the test case 

**Describe the results you expected:**
The Current Test Case to ensure that all the enable container are up and running before and after the Test Case, Hence not impacting the subsequent test case

**Additional information you deem important:**
Observed only on T2 Max(Fully Loaded) Chassis

![image](https://github.com/sonic-net/sonic-mgmt/assets/135994174/0025c9e6-f7d8-4eb5-8263-e6df5bb060ec)

**Comment by rlhui** [comment]
@vikshaw-Nokia  - thanks a lot for root-causing.  Just wondering if you might also help to address this? Thanks.

**Comment by rlhui** [comment]
@vikshaw-Nokia  - any update/ETA of addressing this? Thanks.

**Comment by vikshaw-Nokia** [comment]
@rlhui - We are Testing the fix on out internal setup, weekly run. Will Raise PR soon

**Comment by vikshaw-Nokia** [comment]
@rlhui - Have Raised PR https://github.com/sonic-net/sonic-mgmt/pull/11397 for the issue, Can you please add chassis label, and assign someone to review the PR

Regards,
Vikash

**Comment by SuvarnaMeenakshi** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/11397 PR merged, closing this issue
