### ISSUE TITLE
Validate the packet get dropped and the RX_DROP counter increased while the packet's destination MAC is not the router MAC from Layer3 interface

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#10638]
**Description**

This is a testgap, if the packet's dest MAC is absent in FDB and this MAC is also not equal to the router MAC, then this packet would be dropped and the RX_DROP counter would increase. 
Need a new case to cover the above scenario.
topology is T1
**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by StormLiangMS** [comment]
hi @prsunny  this one seems a dataplane related test gap, assigned to you for further triage.

**Comment by prsunny** [comment]
This is not correct expectation. If FDB entry is not present, it will be flooded in the Vlan domain. Is this testgap on Vlan or some Portchannel test gap on T1?

**Comment by prsunny** [comment]
@kevinskwang , i'm assigning this to you for clarity on requirement.

**Comment by kevinskwang** [comment]
The requirement is mostly for T1, if the packet came in from a L3 interface, if the MAC is not the router MAC, we should just drop it.

**Comment by sdszhang** [comment]
Assign to @sdszhang for hackathon event.
