### ISSUE TITLE
test_copp.py can freeze if the ptf script fails.

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-mgmt#10652]
When running `test_copp.py` a test case froze indefinitely:
copp/test_copp.py::TestCOPP::test_remove_trap[nfc420-7-disable_feature_status]

I believe this was due to a crash seen on the device but this issue is the ptf script doesn't have a timeout specified so it will hang forever.
This was the last log generated by the test:
```
04/11/2023 11:02:50 base._run                                L0063 DEBUG  | /data/tests/ptf_runner.py::ptf_runner#80: [ptf] AnsibleModule::shell, args=["/root/env-python3/bin/ptf --test-dir ptftests/py3 copp_tests.BGPTest --qlen=100000 --platform nn -t 'peerip=u'\"'\"'10.0.0.6'\"'\"';verbose=False;myip=u'\"'\"'10.0.0.7'\"'\"';send_rate_limit=2000;target_port=4;has_trap=True' --device-socket 0-4@tcp://127.0.0.1:10900  --device-socket 1-4@tcp://10.240.107.52:10900"], kwargs={"chdir": "/root", "module_ignore_errors": false}
```

And if I look at the ptf container I still see that process is alive:
```
>ps aux | grep -i copp_test
root      8333  0.0  0.0   2384   768 pts/0    S+   Nov04   0:00 /bin/sh -c /root/env-python3/bin/ptf --test-dir ptftests/py3 copp_tests.BGPTest --qlen=100000 --platform nn -t 'peerip=u'"'"'10.0.0.6'"'"';verbose=False;myip=u'"'"'10.0.0.7'"'"';send_rate_limit=2000;target_port=4;has_trap=True' --device-socket 0-4@tcp://127.0.0.1:10900  --device-socket 1-4@tcp://10.240.107.52:10900
```

This is 2 days later:
```
>date
Mon Nov  6 12:48:46 PST 2023
```

Here is the code which is missing a timeout:
https://github.com/sonic-net/sonic-mgmt/blob/master/tests/copp/test_copp.py#L263

It looks like `ptf_runner` function can take a `timeout` argument which will then set `--test-case-timeout {}`

**Comment by harshsikhwal** [comment]
Hi @arista-nwolfe 

Is there any specific reason on why the PTF docker is crashing? I see from the logs that ptf docker receives termination signal but not totally sure why thats happening.

**Comment by arista-nwolfe** [comment]
> Hi @arista-nwolfe
> 
> Is there any specific reason on why the PTF docker is crashing? I see from the logs that ptf docker receives termination signal but not totally sure why thats happening.

Hi @harshsikhwal, I don't recall the specific details of the crash but based on my description I believe it must've been a crash on the device not the test server so it wouldn't have been the PTF docker crashing.

If I reproduce the issue again I'll add more details about the crash, but I believe this issue is more about the ptf process living forever, anything could go wrong on the device to prevent the ptf process from completing.

**Comment by harshsikhwal** [comment]
I see that the ptf docker issues a lot of SIGTERM in its logs but I am not very certain on this behavior: specifically when I run this test. Do update with your findings and I will do the same.

**Comment by arista-nwolfe** [comment]
I haven't seen this failure in a while and I wasn't able to reproduce it.
I'll reopen if I see it again and provide more details.
