### ISSUE TITLE
sonic-mgmt pre-test sanity check recovery attempt doesn't work for process not running

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#10889]
**Description**

The current `adaptive_recover` recovery action for a pre-test sanity check fail due to a process not running is `config_reload`, however this isn’t able to restore the downed process.  E.g. an orchagent crash in a test will cause multiple subsequent pre-test sanity check fails (and unsuccessful attempts to recover) in a sonic-mgmt run, until a test is reached that performs a reboot.

Applying ‘reboot’ as the recovery action for process-related issues would allow the DUT to recover and testing to continue.

**Steps to reproduce the issue:**
1. Run sonic-mgmt tests while processes on DUT are not healthy
2.
3.

**Describe the results you received:**
`adaptive_recover` does not restore DUT in case hat a process (like orchagent) is down

**Describe the results you expected:**
`adaptive_recover` should restore DUT to working state

**Additional information you deem important:**

**Comment by rlhui** [comment]
@veronica-arista  will close it as it's not seen anymore

**Comment by veronica-arista** [comment]
could not reproduce in latest test runs, closing
