### ISSUE TITLE
[Mellanox] test_unicast_ip_incorrect_eth_dst began to fail in latest 202305 image

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#10897]
**Description**

There seems to be some behavior change in latest 202305 image. Test `test_unicast_ip_incorrect_eth_dst` began to fail in latest 202305 image.
The test was passing in 202305.09 image.

**Steps to reproduce the issue:**
1. Run test case `test_unicast_ip_incorrect_eth_dst`
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

```
admin@str2-msn2700-spy-1:~$ show ver

SONiC Software Version: SONiC.20230531.10
SONiC OS Version: 11
Distribution: Debian 11.8
Kernel: 5.10.0-23-2-amd64
Build commit: bd152fdc10
Build date: Sun Nov 26 04:53:53 UTC 2023
Built by: cloudtest@af2b667cc000001

Platform: x86_64-mlnx_msn2700-r0
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
@roy-sror It seems to be a regression in latest 202305 image. Please take a look. Thanks!

**Comment by roy-sror** [comment]
@bingwang-ms  - I suggest reporting such issues on our triage meeting rather than via Github since it's a platform-specific failure, not a generic sonic issue. This failure was identified by our regression as well, and a fix will be upstreamed in a few days for 202305.
