### ISSUE TITLE
Chassis :  Add randomization to DUT/ASIC selection while picking source/destination ports for QoS/PFC testing

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-mgmt#11009]
**Description**
Currently function - select_src_dst_dut_and_asic selects dut=0/1 and asic 0/1 for different combinations of multi asis/dut testing. We should enhance this logic to randomly select dut/asic from available line cards so to cover all different scenarios.

![image](https://github.com/sonic-net/sonic-mgmt/assets/46945843/cddb80e5-30b2-4314-b02f-bec089550bb2)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by arlakshm** [comment]
This PR Fixes the randomization of Dut https://github.com/sonic-net/sonic-mgmt/pull/14746

**Comment by rlhui** [comment]
@arlakshm , thanks, closing this.
