### ISSUE TITLE
mvrf/test_mgmtvrf.py is not fully multi-dut compliant

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#11034]
**Description**

mvrf/test_mgmtvrf.py is not fully multi-dut compliant

In the setup, it picks up a random dut and configures managment vrf. In the test too it does the same i.e. randomly picks up the dut and runs the test. So the test passes sometimes and fails sometime.
 
If run against a single dut - all testcases passes consistently

**Comment by abdosi** [comment]
mvrf/test_mgmtvrf.py is skipped for T2. so closing for now,
