### ISSUE TITLE
Missing test coverage for 'pfcwd show stats' command

### ISSUE THREAD

**Issue by kenneth-arista** [sonic-net/sonic-mgmt#11169]
As discovered in the sonic-buildimage issue https://github.com/sonic-net/sonic-buildimage/issues/17434, sonic-mgmt is missing test coverage for the `pfcwd show stats` command.

**Comment by kenneth-arista** [comment]
@arlakshm @ysmanman for visibility

**Comment by rlhui** [comment]
test case added.
