### ISSUE TITLE
Log rotation function is failing

### ISSUE THREAD

**Issue by kaushiksrivatsav** [sonic-net/sonic-mgmt#11179]
**Description**

syslog/test_logrotate.py is failing because of an erorr _No logrotate happens, there should be one time logrotate executed_

**LOGS:**
`syslog/test_logrotate.py::test_logrotate_small_size
------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------
12:28:11 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/AzDevOps/202305/sonic-mgmt/tests/syslog/test_logrotate.py", line 230, in test_logrotate_small_size
    validate_logrotate_function(duthost, rotate_small_threshold)
  File "/var/AzDevOps/202305/sonic-mgmt/tests/syslog/test_logrotate.py", line 166, in validate_logrotate_function
    assert syslog_number_origin + 1 == syslog_number_with_rotate, \
AssertionError: No logrotate happens, there should be one time logrotate executed

FAILED                                                                                                                                                                           [100%]

======================================================================================= FAILURES =======================================================================================
______________________________________________________________________________ test_logrotate_small_size _______________________________________________________________________________

rand_selected_dut = <MultiAsicSonicHost str-DUT-acs-1>, simulate_small_var_log_partition = None

    @pytest.mark.disable_loganalyzer
    def test_logrotate_small_size(rand_selected_dut, simulate_small_var_log_partition):
        """
        Test case of logrotate under a simulated small size /var/log, test steps are listed

        Create a temp device which is around 100MB large, then mount it to /var/log
        Execute config reload to active the mount
        Stop logrotate cron job, make sure no logrotate executes during this test
        Check current syslog.x file number and save it
        Create a temp file with size of rotate_size * 90%, and rename it as 'syslog', run logrotate command
        There would be no logrotate happens - by checking the 'syslog.x' file number not increased
        Create a temp file with size of rotate_size * 110%, and rename it as 'syslog', run logrotate command
        There would be logrotate happens - by checking the 'syslog.x' file number increased by 1
        Reboot the dut to recover original /var/log mount

        :param rand_selected_dut: The fixture returns a randomly selected DUT
       :param simulate_small_var_log_partition: The fixture simulates a small var log partition
        """
        duthost = rand_selected_dut
        rotate_small_threshold = get_threshold_based_on_memory(duthost)
>       validate_logrotate_function(duthost, rotate_small_threshold)

duthost    = <MultiAsicSonicHost str-DUT-acs-1>
rand_selected_dut = <MultiAsicSonicHost str-DUT-acs-1>
rotate_small_threshold = '1024K'
simulate_small_var_log_partition = None

syslog/test_logrotate.py:230:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

duthost = <MultiAsicSonicHost str-DUT-acs-1>, logrotate_threshold = '1024K'

    def validate_logrotate_function(duthost, logrotate_threshold):
        """
        Validate logrotate function
        :param duthost: DUT host object
        :param logrotate_threshold: logrotate threshold, such as 16M or 1024K
        """
        with allure.step('Run logrotate with force option to prepare clean syslog environment'):
            run_logrotate(duthost, force=True)

        with allure.step('There should be no logrotate process when rsyslog size is smaller than threshold {}'.format(
                logrotate_threshold)):
            syslog_number_origin = get_syslog_file_count(duthost)
            logger.info('There are {} syslog gz files'.format(syslog_number_origin))
            create_temp_syslog_file(duthost, multiply_with_unit(logrotate_threshold, 0.9))
            run_logrotate(duthost)
            syslog_number_no_rotate = get_syslog_file_count(duthost)
            logger.info('There are {} syslog gz files after running logrotate'.format(syslog_number_no_rotate))
            assert syslog_number_origin == syslog_number_no_rotate, \
                'Unexpected logrotate happens, there should be no logrotate executed'

        with allure.step('There will be logrotate process when rsyslog size is larger than threshold {}'.format(
                logrotate_threshold)):
            create_temp_syslog_file(duthost, multiply_with_unit(logrotate_threshold, 1.1))
            run_logrotate(duthost)
            syslog_number_with_rotate = get_syslog_file_count(duthost)
            logger.info('There are {} syslog gz files after running logrotate'.format(syslog_number_with_rotate))
>           assert syslog_number_origin + 1 == syslog_number_with_rotate, \
                'No logrotate happens, there should be one time logrotate executed'
E           AssertionError: No logrotate happens, there should be one time logrotate executed

duthost    = <MultiAsicSonicHost str-DUT-acs-1>
logrotate_threshold = '1024K'
syslog_number_no_rotate = 1
syslog_number_origin = 1
syslog_number_with_rotate = 1

syslog/test_logrotate.py:166: AssertionError
=================================================================================== warnings summary ===================================================================================
../../../../../usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18
  /usr/local/lib/python3.8/dist-packages/_yaml/__init__.py:18: DeprecationWarning: The _yaml extension module is now located at yaml._yaml and its location is subject to change.  To use the LibYAML-based parser and emitter, import from `yaml`: `from yaml import CLoader as Loader, CDumper as Dumper`.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
-------------------------------------------------------- generated xml file: /var/AzDevOps/202305/sonic-mgmt/tests/logs/tr.xml ---------------------------------------------------------
=============================================================================== short test summary info ================================================================================
FAILED syslog/test_logrotate.py::test_logrotate_small_size - AssertionError: No logrotate happens, there should be one time logrotate executed
================================================================== 1 failed, 1 passed, 1 warning in 880.52s (0:14:40) ==================================================================
INFO:root:Can not get Allure report URL. Please check logs
AzDevOps@9a6fe1272cb5:~/202305/sonic-mgmt/tests$

`

    **Output of `show version`:**

 ```
/home/admin# show version
SONiC Software Version: SONiC.bookworm.0-dirty-20231122.094720
SONiC OS Version: 12
Distribution: Debian 12.2
Kernel: 6.1.0-11-2-arm64
Build commit: 2a86d1118
Build date: Wed Nov 22 09:48:03 UTC 2023 ```

**Comment by wen587** [comment]
Done some check on this test failure and found that `test_logrotate_small_size` is pasing on 202305 branch.
However it keep failing in 202311 and master branch.

1. 202305

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


StartTimeUTC | OSVersion | TestCase | Result
-- | -- | -- | --
2024-03-21T09:01:28Z | 20230531.22 | test_logrotate_small_size | success
2024-03-14T16:10:24Z | 20230531.20 | test_logrotate_small_size | success
2024-03-14T09:01:41Z | 20230531.21 | test_logrotate_small_size | success
2024-03-02T09:01:19Z | 20230531.19 | test_logrotate_small_size | success
2024-02-29T02:58:00Z | 20230531.18 | test_logrotate_small_size | success
2024-02-07T12:01:40Z | 20230531.17 | test_logrotate_small_size | success
2024-02-02T12:02:01Z | 20230531.16 | test_logrotate_small_size | success
2024-02-01T12:01:42Z | 20230531.15 | test_logrotate_small_size | success



</div>


</body>

</html>


2. 202311

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


StartTimeUTC | OSVersion | TestCase | Result
-- | -- | -- | --
2024-03-21T12:01:34Z | 20231110.06 | test_logrotate_small_size | failure
2024-02-28T04:02:13Z | 20231105.05 | test_logrotate_small_size | failure
2024-02-07T04:02:37Z | 20231105.04 | test_logrotate_small_size | failure
2024-01-25T04:02:05Z | 20231105.01 | test_logrotate_small_size | failure



</div>


</body>

</html>

3. master

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


StartTimeUTC | OSVersion | TestCase | Result
-- | -- | -- | --
2024-03-17T10:01:33Z | master.499617-a33330941 | test_logrotate_small_size | failure
2024-03-05T04:01:59Z | master.487454-9fef78c4f | test_logrotate_small_size | failure
2024-02-27T08:03:21Z | master.479015-de2ee9f96 | test_logrotate_small_size | failure
2024-02-11T10:01:36Z | master.475016-34bdfc8b3 | test_logrotate_small_size | failure
2024-02-09T10:02:17Z | master.473616-5a2058941 | test_logrotate_small_size | failure
2024-02-04T10:01:21Z | master.469905-665184ee4 | test_logrotate_small_size | failure
2024-02-01T04:01:30Z | master.467438-77384494b | test_logrotate_small_size | failure
2024-01-28T10:01:20Z | master.464481-235cf3e66 | test_logrotate_small_size | failure
2024-01-26T02:01:43Z | master.462943-1fb9732f4 | test_logrotate_small_size | failure
2024-01-25T04:01:55Z | master.462237-c693e75f0 | test_logrotate_small_size | failure
2024-01-22T01:07:20Z | master.459945-da0f4ace7 | test_logrotate_small_size | failure



</div>


</body>

</html>

**Comment by wen587** [comment]
Hi, I did a initial triage and found that start service of `logrotate-config` doesn't take effect in branc of `202311` and `master`. It result to the rotate size was left as that set in `test_logrotate_normal_size` which is 16M.

See below for example:
- 202311:
```
admin@str-7260cx3-acs-2:~$ show ver
 
SONiC Software Version: SONiC.20231110.06
 
admin@str-7260cx3-acs-2:~$ sudo systemctl status logrotate-config
● logrotate-config.service - Update logrotate configuration
     Loaded: loaded (/lib/systemd/system/logrotate-config.service; enabled-runtime; vendor preset: enabled)
     Active: active (exited) since Fri 2024-03-22 04:56:08 UTC; 2min 29s ago
    Process: 88802 ExecStart=/usr/bin/logrotate-config.sh (code=exited, status=0/SUCCESS)
   Main PID: 88802 (code=exited, status=0/SUCCESS)
 
Mar 22 04:56:08 str-7260cx3-acs-2 systemd[1]: Starting Update logrotate configuration...
Mar 22 04:56:08 str-7260cx3-acs-2 systemd[1]: Finished Update logrotate configuration.

admin@str-7260cx3-acs-2:~$ sudo service logrotate-config start

admin@str-7260cx3-acs-2:~$ sudo systemctl status logrotate-config
● logrotate-config.service - Update logrotate configuration
     Loaded: loaded (/lib/systemd/system/logrotate-config.service; enabled-runtime; vendor preset: enabled)
     Active: active (exited) since Fri 2024-03-22 04:56:08 UTC; 2min 45s ago    <==== Active didn't refresh after start.
    Process: 88802 ExecStart=/usr/bin/logrotate-config.sh (code=exited, status=0/SUCCESS)
   Main PID: 88802 (code=exited, status=0/SUCCESS)
 
Mar 22 04:56:08 str-7260cx3-acs-2 systemd[1]: Starting Update logrotate configuration...
Mar 22 04:56:08 str-7260cx3-acs-2 systemd[1]: Finished Update logrotate configuration.
```
- 202305
```
admin@str3-7260cx3-acs-14:~$ show ver
 
SONiC Software Version: SONiC.20230531.20
 
admin@str3-7260cx3-acs-14:/var/log$ sudo systemctl status logrotate-config
● logrotate-config.service - Update logrotate configuration
     Loaded: loaded (/lib/systemd/system/logrotate-config.service; enabled-runtime; vendor preset: enabled)
     Active: inactive (dead) since Fri 2024-03-22 04:46:49 UTC; 15min ago
    Process: 35279 ExecStart=/usr/bin/logrotate-config.sh (code=exited, status=0/SUCCESS)
   Main PID: 35279 (code=exited, status=0/SUCCESS)
 
Mar 22 04:46:48 str3-7260cx3-acs-14 systemd[1]: Starting Update logrotate configuration...
Mar 22 04:46:49 str3-7260cx3-acs-14 systemd[1]: logrotate-config.service: Succeeded.
Mar 22 04:46:49 str3-7260cx3-acs-14 systemd[1]: Finished Update logrotate configuration.

admin@str3-7260cx3-acs-14:/var/log$ sudo service logrotate-config start

admin@str3-7260cx3-acs-14:/var/log$ sudo systemctl status logrotate-config
● logrotate-config.service - Update logrotate configuration
     Loaded: loaded (/lib/systemd/system/logrotate-config.service; enabled-runtime; vendor preset: enabled)
     Active: inactive (dead) since Fri 2024-03-22 05:02:28 UTC; 1s ago      <==== refresed after start
    Process: 42116 ExecStart=/usr/bin/logrotate-config.sh (code=exited, status=0/SUCCESS)
   Main PID: 42116 (code=exited, status=0/SUCCESS)
 
Mar 22 05:02:28 str3-7260cx3-acs-14 systemd[1]: Starting Update logrotate configuration...
Mar 22 05:02:28 str3-7260cx3-acs-14 systemd[1]: logrotate-config.service: Succeeded.
Mar 22 05:02:28 str3-7260cx3-acs-14 systemd[1]: Finished Update logrotate configuration.
```

**Comment by wen587** [comment]
Suspect feature issue. @qiluo-msft , please help assign to stakeholder to fix.

**Comment by qiluo-msft** [comment]
@liat-grozovik @echuawu @roy-sror Could you help check?

**Comment by congh-nvidia** [comment]
Hi @qiluo-msft , this issue has been triaged by @dgsudharsan, and I have created a PR for the fix, please review: https://github.com/sonic-net/sonic-mgmt/pull/12140. Thank.
