### ISSUE TITLE
pytest_assert syntax error

### ISSUE THREAD

**Issue by qiluo-msft** [sonic-net/sonic-mgmt#11408]
>common_password_diff [](http://example.com/codeflow?start=50&length=20)

The 2nd parameter should be a string, not an array.

_Originally posted by @qiluo-msft in https://github.com/sonic-net/sonic-mgmt/pull/6453#discussion_r1468079159_

**Comment by qiluo-msft** [comment]
@davidpil2002 Could you help?

**Comment by davidpil2002** [comment]
> @davidpil2002 Could you help?

sorry for late response, was on vacation, you are correct, and I see that someone fixed it 2 weeks ago:
https://github.com/sonic-net/sonic-mgmt/pull/11377

I think you can close this issue.
