### ISSUE TITLE
snappi_tests: packet analysis fails due to invalid frame

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#11714]
**Description**

snappi_tests/pfc/test_valid_pfc_frame_with_snappi.py::test_valid_pfc_frame fails since a captured packet is not complete, or invalid.

`
t.SnappiPortConfig object at 0x7f2d38be8070>]
        port_id    = 3
        prio_dscp_map = {0: [8], 1: [0, 1, 10, 11, 12, 13, ...], 2: [5], 3: [3], ...}
        snappi_extra_params = <tests.common.snappi_tests.snappi_test_params.SnappiTestParams object at 0x7f2d38c766d0>
        speed_gbps = 100
        speed_str  = 'speed_100_gbps'
        switch_flow_stats = {'rx_frames': {3: [0, 0, 0, 0, 0, 0, ...], 4: [0, 0, 0, 0, 0, 0, ...]}, 'tx_frames': {3: [0, 4608, 4608, 4608, 4608, 4608, ...], 4: [4564, 4564, 4564, 4564, 4564, 4564, ...]}}
        test_flow_rate_percent = 22
        test_prio_list = [3, 4]
        test_traffic_pause = True
        testbed_config = <snappi.snappi.Config object at 0x7f2d387584c0>
        tgen_flow_stats = <snappi.snappi.FlowMetricIter object at 0x7f2d31ea7a40>
        valid_pfc_frame_test = True
common/snappi_tests/read_pcap.py:33: in validate_pfc_frame
    eth = dpkt.ethernet.Ethernet(buf)
        SAMPLE_SIZE = 15000
        UTIL_THRESHOLD = 0.8
        _          = 1708270802.0195577
        buf        = b''
        curPFCPktCount = 6824
        curPktCount = 6824
        dest_mac   = '01:80:c2:00:00:01'
        eth        = Ethernet(dst=b'\x01\x80\xc2\x00\x00\x01', src=b"\x80'l\xde\xae\xb8", type=34824, data=b'\x01\x01\x00\x18\x00\x00\x00\x...x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x003\xf45\x81')
        f          = <_io.BufferedReader name='PFC_Capture.pcapng'>
        pcap       = <dpkt.pcapng.Reader object at 0x7f2d38634190>
        pfc_packet = <tests.common.snappi_tests.pfc_packet.PFCPacket object at 0x7f2d3872e820>
        pfc_pcap_file = 'PFC_Capture.pcapng'
/usr/local/lib/python3.8/dist-packages/dpkt/ethernet.py:84: in __init__
    dpkt.Packet.__init__(self, *args, **kwargs)
        args       = (b'',)
        kwargs     = {}
        self       = <[AttributeError('dst') raised in repr()] Ethernet object at 0x7f2d386b10e0>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError('dst') raised in repr()] Ethernet object at 0x7f2d386b10e0>, args = (b'',), kwargs = {}

    def __init__(self, *args, **kwargs):
        """Packet constructor with ([buf], [field=val,...]) prototype.

        Arguments:

        buf -- optional packet buffer to unpack

        Optional keyword arguments correspond to members to set
        (matching fields in self.__hdr__, or 'data').
        """
        self.data = b''
        if args:
            try:
                self.unpack(args[0])
            except struct.error:
                if len(args[0]) < self.__hdr_len__:
>                   raise NeedData('got %d, %d needed at least' % (len(args[0]), self.__hdr_len__))
E                   dpkt.dpkt.NeedData: got 0, 14 needed at least

args       = (b'',)
kwargs     = {}
self       = <[AttributeError('dst') raised in repr()] Ethernet object at 0x7f2d386b10e0>

/usr/local/lib/python3.8/dist-packages/dpkt/dpkt.py:163: NeedData
`
<img width="1792" alt="Screenshot 2024-02-18 at 2 56 24 PM" src="https://github.com/sonic-net/sonic-mgmt/assets/58446052/9269bf90-33d8-42e0-8b41-3c85a8741f5e">

Pls see the attached wireshark screenshot of the same packet.

**Steps to reproduce the issue:**
1. Run snappi_tests/pfc/test_valid_pfc_frame_with_snappi.py::test_valid_pfc_frame.

**Describe the results you received:**
The packet analysis code is failing.

**Describe the results you expected:**
The test should pass.

**Additional information you deem important:**
I am not sure if this is DUT or Ixia problem, so I am asking Ixia team for help. @kamalsahu0001 , @selldinesh , and @isgmano : for viz.

**Comment by abdosi** [comment]
@selldinesh can you please help look into this. We want to unblock any issue regarding ixia testing so that we can make progress.

**Comment by developfast** [comment]
This is not a test issue. The DUT sent a junk packet (from the screenshot above) and the test failed since this is not a PFC pause packet.

**Comment by rraghav-cisco** [comment]
We are internally checking this issue. Closing.
