### ISSUE TITLE
Reboot Tests Fail on Feb 29 during Leap Year due to bug

### ISSUE THREAD

**Issue by jongorel** [sonic-net/sonic-mgmt#11816]
**Description**

Currently, all sonic azure pipeline builds on any PR are failing during reboot tests.  This will be remedied once it is no longer February 29th, as it is a leap year specific failure, but will continue to happen every 4 years if not fixed.  Failure is occuring while running test_warm_reboot due to a DateTime parse error:

=================================== FAILURES ===================================
_______________________ test_warm_reboot[single-vlab-01] _______________________

timestamp = Feb 29 00:49:50.629331

    def _parse_timestamp(timestamp):
        try:
>           time = datetime.strptime(timestamp, FMT)

timestamp  = Feb 29 00:49:50.629331

platform_tests/conftest.py:39:

This appears to be happenings because there are numerous times that a date/time is stripped down to just a Month/Day/Time format before being passed to _parse_timestamp.  DateTime automatically assigns the year 1900 to any string that omits the year, and 1900 was not a leap year.  This is causing the datetime parse to fail as Feb 29 is not a valid day in a non leap year.

The specific error in my pipeline run is coming from ` reboot_time = _parse_timestamp(re.split(delim, message)` in get_kexec_time() method, but could also be caused by methods Get_State_Times(time variable, line 113) or analyze_sairedis_rec (log_time variable, line 337) within platform_tests/conftest.py, as both of these methods strip a timestamp down to just Month/Day/Time format before passing the timestamp to _parse_timestamp.

Full stack trace of error can be found on line 43 of the pipeline logs [here](https://elastictest.org/scheduler/testplan/65dfc194651b6525531c57d3?testcase=platform_tests%2Ftest_advanced_reboot.py%3A%3Atest_warm_reboot&type=console)

**Steps to reproduce the issue:**
1.  Put up any SONIC PR that automates a pipeline run before EOD Feb 29
2.  Test will fail after 2 hours due to DateTime parse exception during reboot testing.

**Describe the results you received:**

All PR builds failing, datetime parse not working

**Describe the results you expected:**

Valid PR builds to succeed, datetime parse to work as expected

**Comment by bingwang-ms** [comment]
Hi @yejianquan, can you please help check this issue?

**Comment by bingwang-ms** [comment]
@wangxin for viz.

**Comment by yejianquan** [comment]
Assign to myself and will reassign in the future.
