### ISSUE TITLE
config_reload.py does not handle multi-asic for running_golden_config json file loading

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-mgmt#11945]
**Description**
Durign presanity recovery, when recovery is triggered with golden_config, config reloads command fails for multi-asics system.

https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/config_reload.py#L130

During sonic-mgmgt tests, if sanity precheck fails, the scripts try to recover the setup by executing ‘config reload’ with running_golden_config files saved.

the command executed is 'config reload -f -l /etc/sonic/running_golden_config.json'

This command works fine on single asic systems but does not work on multi-asic cards.

For multi asic cards, the config reload expects one global config file and one namespace config file for each namespace:

e.g: for 2 asic LC:

config reload -f -l /etc/sonic/running_golden_config.json,/etc/sonic/running_golden_config0.json,/etc/sonic/running_golden_config2.json

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anamehra** [comment]
Hi @rlhui , @abdosi , please assign this to me and add chassis label.

**Comment by abdosi** [comment]
@anamehra : can we close this ?
