### ISSUE TITLE
scp/test_scp_copy.py uses user name, directories as admin, instead of generic user name..

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#11969]
**Description**

test_scp.py uses user name, directories as admin, instead of generic user name..
Different vendors use different sonicadmin_user name, that fails this test. 

**Steps to reproduce the issue:**
1. run the scp/test_scp.py with sonicadmin_user other than "admin".

**Describe the results you received:**
The SCP tests fails, and its expected file is not copied to the /home/admin directory, which is not there with a different user id.

**Describe the results you expected:**
To use sonicadmin_user name in the scp/test_scp.py instead of hardcoded /home/admin.

**Comment by rajendrat** [comment]
viz @abdosi @vperumal

**Comment by abdosi** [comment]
PR to fix this has been merged.
