### ISSUE TITLE
T2 system_health/test_watchdog.py require multi asic support

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#12019]
**Description**
Currently system_health/test_watchdog.py is failing in mutli asic switches.

This test tries to Pause orchagent service with 'kill -stop' command and check if the watchdog can send alert.
But this is validated specific to swss. But in multi-asic switches, there are multiple instance of swss is running, script needs to be enhanced to supported in T2/Muli-asic platforms.

**Steps to reproduce the issue:**
1. Running  system_health/test_watchdog.py test
2.
3.

**Describe the results you received:**
Test failure, as the test looks at a docker swss, which is not running in mutl-asic system.

def test_orchagent_watchdog
...
result = duthost.shell(
                        r"docker exec -i swss sh -c 'test -f /etc/supervisor/watchdog_processes && echo exist'",
...

**Describe the results you expected:**
To look at specifically to swss with different namespaces.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rajendrat** [comment]
viz @abdosi @vperumal

**Comment by abdosi** [comment]
need to enhance for multi-asic.

**Comment by abdosi** [comment]
fixed via: https://github.com/sonic-net/sonic-mgmt/pull/12634
