### ISSUE TITLE
test_osbuild_version failing because unable to merge without fix 

### ISSUE THREAD

**Issue by zbud-msft** [sonic-net/sonic-mgmt#12021]
**Description**

gnmi submodule update is failing because of PR checker test outdated
PR checker test not able to be updated and is unable to be merged because fix is not in
will have to skip test_os_build_version testcase, merge fix, then unskip test.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by zbud-msft** [comment]
https://github.com/sonic-net/sonic-buildimage/pull/18258

**Comment by StormLiangMS** [comment]
still hit this issue.
