### ISSUE TITLE
[Vxlan ECMP] The test cases in module Test_VxLAN_entropy  are failing due to "'str' object has no attribute 'decode"

### ISSUE THREAD

**Issue by congh-nvidia** [sonic-net/sonic-mgmt#12147]
**Description**

**Steps to reproduce the issue:**
1. Run the test vxlan/test_vxlan_ecmp.py::Test_VxLAN_entropy, need to add "--include_long_tests=True" pytest option, otherwise the test will be skipped.
2.
3.

**Describe the results you received:**
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "/root/env-python3/bin/ptf --test-dir ptftests/py3 vxlan_traffic.VXLAN --platform-dir ptftests --qlen=1000 --platform remote -t 'topo_file='\"'\"'/tmp/vxlan_topo_info.json'\"'\"';config_file='\"'\"'/tmp/vxlan_configs.entropy-v4_in_v4-1711343306.3481257.json'\"'\"';t0_ports=['\"'\"'Ethernet100'\"'\"'];t2_ports=[0, 1];dut_mac='\"'\"'fc:6a:1c:4e:8d:40'\"'\"';vxlan_port=4789;expect_encap_success=True;packet_count=1000;random_dport=True;random_sport=True;random_src_ip=True;tolerance=0.75;downed_endpoints=['\"'\"'100.0.16.1'\"'\"', '\"'\"'100.0.18.1'\"'\"', '\"'\"'100.0.21.1'\"'\"', '\"'\"'100.0.19.1'\"'\"']' --relax --debug info --log-file /tmp/vxlan-tests.entropy.v4_in_v4.2024-03-25-07:08:34.log", "delta": "0:00:01.963960", "end": "2024-03-25 05:08:37.048673", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2024-03-25 05:08:35.084713", "stderr": "vxlan_traffic.VXLAN ... ERROR\n\n======================================================================\nERROR: vxlan_traffic.VXLAN\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"ptftests/py3/vxlan_traffic.py\", line 224, in runTest\n    random_src_ip=self.random_src_ip)\n  File \"ptftests/py3/vxlan_traffic.py\", line 352, in test_encap\n    \"v4\", hostid=3, netid=170)\n  File \"ptftests/py3/vxlan_traffic.py\", line 93, in get_ip_address\n    first_octet, second_octet, third_octet, hostid).decode()\n**AttributeError: 'str' object has no attribute 'decode'**\n\n----------------------------------------------------------------------\nRan 1 test in 0.004s\n\nFAILED (errors=1)", "stderr_lines": ["vxlan_traffic.VXLAN ... ERROR", "", "======================================================================", "ERROR: vxlan_traffic.VXLAN", "----------------------------------------------------------------------", "Traceback (most recent call last):", "  File \"ptftests/py3/vxlan_traffic.py\", line 224, in runTest", "    random_src_ip=self.random_src_ip)", "  File \"ptftests/py3/vxlan_traffic.py\", line 352, in test_encap", "    \"v4\", hostid=3, netid=170)", "  File \"ptftests/py3/vxlan_traffic.py\", line 93, in get_ip_address", "    first_octet, second_octet, third_octet, hostid).decode()", "AttributeError: 'str' object has no attribute 'decode'", "", "----------------------------------------------------------------------", "Ran 1 test in 0.004s", "", "FAILED (errors=1)"], "stdout": "Using packet manipulation module: ptf.packet_scapy\n\n******************************************\nATTENTION: SOME TESTS DID NOT PASS!!!\n\nThe following tests errored:\nVXLAN\n\n******************************************", "stdout_lines": ["Using packet manipulation module: ptf.packet_scapy", "", "******************************************", "ATTENTION: SOME TESTS DID NOT PASS!!!", "", "The following tests errored:", "VXLAN", "", "******************************************"]}

**Describe the results you expected:**
Test should pass

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by volodymyrsamotiy** [comment]
@prsunny, could you please help to check or assign someone? Thanks!

**Comment by siqbal1986** [comment]
Ack. Seems to be a python 3 migration issue. Since this test doesn't run very often it hasn't surface in our runs.
I'll create a fix

**Comment by congh-nvidia** [comment]
Hi @siqbal1986, I'm running on master but we are still using the python3 venv in sonic-mgmt container.

**Comment by siqbal1986** [comment]
PR merged
