### ISSUE TITLE
snappi_tests/multidut tests' arguments are not properly included.

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#12516]
All of these tests fail since the required fixtures are not included in the arguments:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/rraghav/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/rraghav/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 34:45.2 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 21 | test_pfc_pause_single_lossy_prio[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic] | failure | 34:36.0 | AttributeError: 'function' object has no   attribute 'keys' | 9.19
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 34:48.6 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 97 | test_pfc_pause_multi_lossy_prio[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic] | failure | 34:45.2 | AttributeError: 'function' object has no attribute 'keys' | 3.456
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 34:52.2 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 173 | test_pfc_pause_single_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-warm] | failure | 34:48.6 | AttributeError: 'function' object has no attribute 'keys' | 3.527
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 34:55.9 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 173 | test_pfc_pause_single_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-cold] | failure | 34:52.2 | AttributeError: 'function' object has no attribute 'keys' | 3.697
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 34:59.4 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 173 | test_pfc_pause_single_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-fast] | failure | 34:55.9 | AttributeError: 'function' object has no attribute 'keys' | 3.521
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 35:03.0 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 262 | test_pfc_pause_multi_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-warm] | failure | 34:59.4 | AttributeError: 'function' object has no attribute 'keys' | 3.569
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 35:06.5 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 262 | test_pfc_pause_multi_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-cold] | failure | 35:03.0 | AttributeError: 'function' object has no attribute 'keys' | 3.486
snappi_tests.multidut.pfc.test_multidut_pfc_pause_lossy_with_snappi | 39:45.1 | FALSE | snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py | 262 | test_pfc_pause_multi_lossy_prio_reboot[yy39top-lc4-linecard_configuration_set0-chassis_single_line_card_multi_asic-fast] | failure | 35:06.5 | AttributeError: 'function' object has no attribute 'keys' | 278.634

</body>

</html>
 
 We need to include the two fixtures as below for all of them:
```
+++ b/sonic-mgmt/tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossy_with_snappi.py
@@ -27,6 +27,8 @@ def test_pfc_pause_single_lossy_prio(snappi_api,                # noqa: F811
                                      duthosts,
                                      line_card_choice,
                                      linecard_configuration_set,
+                                     prio_dscp_map,
+                                     lossless_prio_list,
                                      get_multidut_snappi_ports):  # noqa: F811
```

**Comment by rraghav-cisco** [comment]
@selldinesh , @isgmano and @kamalsahu0001 : for viz.

**Comment by selldinesh** [comment]
@rraghav-cisco the fix is available in PR https://github.com/sonic-net/sonic-mgmt/pull/12004
