### ISSUE TITLE
[Bug]: [Snappi] Reboot and swss reboot logic needs to be adjusted for multidut scenario

### ISSUE THREAD

**Issue by amitpawar12** [sonic-net/sonic-mgmt#12904]
### Issue Description

Test Script- tests/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py

(1)
Test case: test_pfcwd_basic_single_lossless_prio_reboot

Code:
 ```
   for duthost in dut_list:
        logger.info("Issuing a {} reboot on the dut {}".format(reboot_type, duthost.hostname))
        reboot(duthost, localhost, reboot_type=reboot_type, safe_reboot=True)
        logger.info("Wait until the system is stable")
        pytest_assert(wait_until(300, 20, 0, duthost.critical_services_fully_started),
                      "Not all critical services are fully started")
```
Issue: if the test case is being executed on single line card (single or multiple ASIC), same DUT will be rebooted twice and hence longer testcase execution.

(2)
Test case - test_pfcwd_basic_single_lossless_prio_service_restart

Code:
```
@pytest.mark.parametrize('restart_service', ['swss'])
----
    for duthost in dut_list:
        logger.info("Issuing a restart of service {} on the dut {}".format(restart_service, duthost.hostname))
        duthost.command("systemctl reset-failed {}".format(restart_service))
        duthost.command("systemctl restart {}".format(restart_service))
        logger.info("Wait until the system is stable")
        pytest_assert(wait_until(300, 20, 0, duthost.critical_services_fully_started),
                      "Not all critical services are fully started")
```

Issue:
for multi-asic environment, we do not have swss service but swss@0 and swss@1 service. With single linecard, we will end up restarting the same swss process twice. 

### Results you see

=> sudo systemctl status swss
● swss.service - switch state service
     Loaded: loaded (/lib/systemd/system/swss.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
=> sudo systemctl status swss@0
● swss@0.service - switch state service
     Loaded: loaded (/lib/systemd/system/swss@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/swss@0.service.d
             └─auto_restart.conf
     Active: active (running) since Mon 2024-05-20 17:26:39 UTC; 2h 9min ago
 ----- curtailed output --------

### Results you expected to see

For reboot testcases:
We should add a check to see if duthost1.hostname == duthost2.hostname, and if not, then reboot both, else just do a single reboot (of either duthost1 or duthost2).

For swss restart testcases, we can find the dut<->asic mapping of the interfaces used and restart swss process based on that mapping.

### Is it platform specific

generic

**Comment by sdszhang** [comment]
Issue 2 is fixed in #13483. @amitpawar12 do we need another PR for issue 1?
