### ISSUE TITLE
bfd/test_bfd_static_route.py: fails on single asic systems with `/etc/sonic/config_db0.json': No such file or directory`

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-mgmt#12948]
### Issue Description

`bfd/test_bfd_static_route.py` assumes that config_db.json is a mulit-asic system.
If it's a single asic it will use the wrong file name

This test was added recently in https://github.com/sonic-net/sonic-mgmt/pull/9714

### Results you see

`"stderr_lines": ["cp: cannot stat '/etc/sonic/config_db0.json': No such file or directory"]`

### Results you expected to see

No failure on single-asic systems

### Is it platform specific

generic

**Comment by vperumal** [comment]
@abdosi - Kindly help approve and merge https://github.com/sonic-net/sonic-mgmt/pull/13356
