### ISSUE TITLE
[test gap]: Subnet decap TC1 - Verify IPinIP packet targeting at VLAN subnet is decapsulated (T0 only) 

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#13120]
### Issue Description

This is a new test case to cover subnet decap feature.
Test plan is https://github.com/sonic-net/sonic-mgmt/pull/12990

### Results you see

This is a test gap.

### Results you expected to see

This is a test gap.

### Is it platform specific

generic

**Comment by xwjiang-ms** [comment]
PR created: https://github.com/sonic-net/sonic-mgmt/pull/14720

**Comment by xwjiang-ms** [comment]
PR merged. close this issue
