### ISSUE TITLE
[Snappi]: Snappi does not capture PCAPs for ECN red-accuracy testcase on 400Gbps port when num_iteration > 1

### ISSUE THREAD

**Issue by amitpawar12** [sonic-net/sonic-mgmt#13303]
### Issue Description

Test case - tests/snappi_tests/multidut/ecn/test_multidut_red_accuracy_with_snappi.py

In this test case, the num_iterations runs the same loop of traffic and captures PCAP in each iteration. After the run, it determines the probability of the packet being ECN marked based on cumulative average marking during the test.

However for 400Gbps ports, the packets are captured for the first iteration. After that each iteration returns empty PCAP. Test aborts because it checks for the packet captured against number of packets set.

@kamalsahu0001

### Results you see

Empty PCAPs after first iteration on 400Gbps ports.

### Results you expected to see

Each iteration should capture the packets and determine if they are ECN marked or not.

### Is it platform specific

generic

**Comment by amitpawar12** [comment]
This issue is now seen with 4x100Gbps ports and I have opened an IXIA support ticket to track the same.

Thanks,
-A

**Comment by kamalsahu0001** [comment]
Issue reproduced locally. Currently investigating the issue.

**Comment by kamalsahu0001** [comment]
Fix was provided and it worked for Nokia team. Cisco team created their own cases for ECN and not using this test. So, we can close this issue.
