### ISSUE TITLE
[Test Gap][reboot healthy][any]: Check the reboot healthy via console

### ISSUE THREAD

**Issue by Pterosaur** [sonic-net/sonic-mgmt#13459]
### Test Gap Description

Raise an issue: https://github.com/sonic-net/sonic-buildimage/issues/19399 on sonic-buildimage

### Test Plan

Check the console output without any failure message after reboot

### Test environment

kvm

**Comment by yxieca** [comment]
@wangxin can you help triage and add to @StormLiangMS's test gap tracking?
