### ISSUE TITLE
[Bug]: testQosSaiHeadroomPoolSize does not take into account cable length, speed, headroom size 

### ISSUE THREAD

**Issue by SavchukRomanLv** [sonic-net/sonic-mgmt#13478]
### Issue Description

Test  testQosSaiHeadroomPoolSize calculates all numbers assuming all ingress ports share the same speed, cable length tuple. However, the speed, and cable length tuple could not be the same among all the ingress ports. It calculates the numbers based on a larger headroom but applies it on a smaller headroom, causing drop.

### Results you see

TC fails with error message "There are some unexpected 95 packet drop", 
number of packets can be random, depends on cable 

### Results you expected to see

TC passed, covers scenario when Testbed has different cables connected to setup

### Is it platform specific

generic

**Comment by bingwang-ms** [comment]
The issue is caused by cable length change. It's a testbed issue. Will fix the configuration to address the issue.
