### ISSUE TITLE
[Test Gap][reload config test on Cisco 8000][All Topos]Enable test_reload_configuration_checks on Cisco 8000

### ISSUE THREAD

**Issue by cyw233** [sonic-net/sonic-mgmt#13494]
### Test Gap Description

Currently, the `platform_tests/test_reload_config.py::test_reload_configuration_checks` test case is skipped on Cisco 8000 for most releases, because Cisco platform has flaky timing issue. We should enhance the `reboot()` function ([link](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_reload_config.py#L148)) in the test to support it on Cisco 8000.

**Comment by yxieca** [comment]
@cyw233 who will take the enhancement work? This is an image issue?

**Comment by cyw233** [comment]
Hi @yxieca, I will take care of this. We have an ADO in our board to track this. Not sure if this is an image issue or not, will need some time to investigate before making the enhancement. Thanks

**Comment by augusdn** [comment]
Assigning to myself for hackathon task
