### ISSUE TITLE
[Snappi]: PFCWD and PFC-oversubscription testcases should use the common functions defined in common/snappi_tests folder.

### ISSUE THREAD

**Issue by amitpawar12** [sonic-net/sonic-mgmt#13491]
### Issue Description

Some of the PFCWD testcases and PFC oversubscription testcases are using their own basic-helper file which does - creation of traffic flow template, start the traffic and verify the results.

However,  in tests/common/snappi_tests/ folder, there are common functions added to do the same. The fixes made in this common infrastructure will be propagated to all the testcases. 

Classis example is change in queue<->priority mapping if the IXIA chassis has 4 queues. This change made in common infrastructure will be propagated to all the tests. 

Now, we have to add these changes in individual basic-helper files for the tests mentioned above.

### Results you see

Each testcase has its own individual helper file, doing almost the same thing  - creating traffic template, running the tests. We need to now explicitly adjust for IXIA queue<->priority mapping.

### Results you expected to see

Using common infrastructure for the generating traffic flow templates, running tests and verifying results.

### Is it platform specific

generic

**Comment by yxieca** [comment]
@yejianquan @developfast @kperumalbfn @selldinesh  Who is the right owner of this issue?

**Comment by sdszhang** [comment]
@selldinesh Can you comment on this, and close it if no further action needed.

**Comment by selldinesh** [comment]
This PR is good to close
