### ISSUE TITLE
HeadroomPoolSize and  LossyQueueTest failing with new vsq thresholds params for Nokia-IXR7250E-36x400G & 100G hwsku

### ISSUE THREAD

**Issue by ansrajpu-git** [sonic-net/sonic-mgmt#13503]
With the introduction of new vsq threshold profile for broadcom-dnx chassis (ref# https://github.com/sonic-net/sonic-buildimage/pull/18239) below test cases failing. Hence skipping these test cases for Nokia-IXR7250E-36x400G hwsku , broadcom-dnx chassis.

**- testQosSaiHeadroomPoolSize &,testQosSaiHeadroomPoolWatermark** 
With the introduction of dynamic buffer, the shared buffer per vsq is calculated on the basis of remaining buffer.Hence, as per the current implementation of the test cases the  PFC frames are triggered sooner for the each  vsq  shared buffer filled after the first vsq .And hence not allowing to fill the shared buffer completely per vsq
![image](https://github.com/sonic-net/sonic-mgmt/assets/113939367/09c6e193-d407-4e90-a153-bfcc0d19488c)
 

**-  testQosSaiLossyQueue** 
With the introduction of new vsq threshold values for Lossy traffic FADT Max threshold has a higher value than the FADT xoff  threshold. The PFC frames starts coming even before the threshold is reached for shared buffer pool
![image](https://github.com/sonic-net/sonic-mgmt/assets/113939367/e4d7ec15-b3dd-4518-8bf1-4c408efe4bd1)
 
![image](https://github.com/sonic-net/sonic-mgmt/assets/113939367/b42ea80a-b209-4dd4-9bf1-8611d876c764)
==>FADT max threshold : 268435456/2  = 134,217,728
==>Pool 0 : 2430208000/64 = 37,972,000

**Comment by yxieca** [comment]
@ansrajpu-git do you think this is an image issue or test issue? Sounds like the dut is not behavior as expected? In such case, this is an image issue, do you agree?

**Comment by ansrajpu-git** [comment]
With the new dynamic buffer profile for t2 broadcom-dnx chassis:
1.The Lossy queue test is resolved by the PR # https://github.com/sonic-net/sonic-buildimage/pull/19653
2. For HeadoomPoolsize test a new testcase is needed to verify the headroom buffer with dynamic buffer thresholds.Issue https://github.com/sonic-net/sonic-mgmt/issues/13688 is created for the same.
Hence closing this issue.
