### ISSUE TITLE
[Bug]: sshd not started in docker ptf container 

### ISSUE THREAD

**Issue by SavchukRomanLv** [sonic-net/sonic-mgmt#13545]
### Issue Description

After 5/30/24 latest docker ptf image had problem to connect via ssh to docker ptf container

### Results you see

**add-topo fails with at step vm_set : wait until ptf is reachable** 
Timeout when waiting for docker_ptf_ip :22 

From docker ptf logs:
cat /tmp/sshd.err.log
**/run/sshd must be owned by root and not group or world-writable.**

This means problem with permissions, possible fix:
sudo chown root:root /run/sshd
sudo chmod 755 /run/sshd

Start sshd:
service ssh start

### Results you expected to see

User able to connect to docker ptf container

### Is it platform specific

generic

### Relevant log output

```shell
cat /tmp/sshd.err.log
**/run/sshd must be owned by root and not group or world-writable.**
```

**Comment by bingwang-ms** [comment]
Hi @wangxin , could you please help take a look?

**Comment by opcoder0** [comment]
@SavchukRomanLv I got the `docker-ptf:latest` image from July 20th 2024 and have not seen the issue with add-topo and logging in via ssh after that. I also see the permissions in the docker-ptf container is not writable to the world -

<img width="382" alt="docker_ptf" src="https://github.com/user-attachments/assets/2979b653-8865-45e1-950b-1edbdc6e1990">

I plan to try this test with the images built from source. I can post an update on that in a day or two.

Can you confirm if you built the docker-ptf image from source or was that from the docker registry ?

**Comment by SavchukRomanLv** [comment]
Hi @opcoder0  we are building docker ptf from a source. 
An here are permissions it's being built: 

drwxrwxrwt 2 root        root        4096 May 13 00:00 lock
drwxrwxr-x 2 root        root        4096 Jul 27 14:48 sshd

**Comment by SavchukRomanLv** [comment]
Hi @opcoder0 any update here?

**Comment by vperumal** [comment]
@wangxin @yxieca  - Can you please take a look - I am seeing the same issue that @SavchukRomanLv reported. This is with latest Sept 6th docker ptf image
root@a16ad7ced0d6:~# cat /tmp/sshd.err.log
/run/sshd must be owned by root and not group or world-writable.
/run/sshd must be owned by root and not group or world-writable.
/run/sshd must be owned by root and not group or world-writable.
/run/sshd must be owned by root and not group or world-writable.
root@a16ad7ced0d6:~# sudo chown root:root /run/sshd
bash: sudo: command not found
root@a16ad7ced0d6:~# chown root:root /run/sshd
root@a16ad7ced0d6:~# chmod 755 /run/sshd
root@a16ad7ced0d6:~# service ssh start
[ ok ] Starting OpenBSD Secure Shell server: sshd.
root@a16ad7ced0d6:~# service ssh status
[ ok ] sshd is running.
root@a16ad7ced0d6:~# exit

**Comment by vperumal** [comment]
FYI @yejianquan @abdosi

**Comment by wangxin** [comment]
@opcoder0  Can you check if this issue is related with your recent change to PTF docker file?

**Comment by opcoder0** [comment]
> Hi @opcoder0 we are downloading from community And here are permissions after deploy ptf:
> 
> drwxrwxrwt 2 root root 4096 May 13 00:00 lock drwxrwxr-x 2 root root 4096 Jul 27 14:48 sshd

Hi @SavchukRomanLv 

Can you please clarify with more details ? Are you getting a built docker image from a registry or are you building from the GH source and seeing this issue?

**Comment by SavchukRomanLv** [comment]
Hi @opcoder0 
Hi @opcoder0 we are downloading from community
And here are permissions after deploy ptf:
drwxrwxrwt 2 root root 4096 May 13 00:00 lock
drwxrwxr-x 2 root root 4096 Jul 27 14:48 sshd

**Comment by opcoder0** [comment]
@SavchukRomanLv thank you. Sorry but I haven't accessed an image from the community before. Can you confirm if you meant it is from here - https://sonic-net.github.io/SONiC/sonic_latest_images.html ? I did not see a docker-ptf image here.

**Comment by opcoder0** [comment]
> I will build from latest source and get back to you in about a days' time.

@SavchukRomanLv I built `docker-ptf` image from the source and successfully added that to a topology and I haven't been able to see the issue described above. I will require more information on the download location of the image you're using to troubleshoot this issue.

**Comment by opcoder0** [comment]
I think I see the issue. It appears to be with the ones downloaded via artifacts. I'll investigate further and provide an update/fix soon.

<img width="386" alt="image" src="https://github.com/user-attachments/assets/55887996-e9c4-4f80-a00f-35e5c9b12eb4">

**Comment by opcoder0** [comment]
There appears to be an issue with the build environment and not the code. I have reached out to the team who might be able to assist further / fix the issue. I'll add them here once I receive confirmation.
