### ISSUE TITLE
add the priority<->queue mapping support for the PFC oversubscription testcases

### ISSUE THREAD

**Issue by sdszhang** [sonic-net/sonic-mgmt#13737]
Per discussion in #13546,  
please also add the priority<->queue mapping support for the PFC oversubscription testcases:

tests/snappi_tests/multidut/pfc/files/lossless_response_to_external_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/lossless_response_to_throttling_pause_storms_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_fluctuating_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossless_lossy_helper.py
tests/snappi_tests/multidut/pfc/files/m2o_oversubscribe_lossy_helper.py

Regards
Shawn

**Comment by amitpawar12** [comment]
I have raised issue - #13687 for the same.

**Comment by sdszhang** [comment]
Thanks @amitpawar12 , closing this one as duplicated.
