### ISSUE TITLE
[Snappi] - Support to clear the fabric counters and check them before and after the test.

### ISSUE THREAD

**Issue by amitpawar12** [sonic-net/sonic-mgmt#14095]
### Issue Description

One of the validations missing in the Snappi test is to check the CRC and uncorrectable FEC errors before and after the test.

This issue is addressing need to have mechanism to clear the counters before the test. Once cleared, then check the counters before and after the test. 

The check should ASSERT if the counters are non-zero.

This check could be done for both the line-cards and supervisor card.

### Results you see

Currently, there is no mechanism to check the fabric counters. 

### Results you expected to see

Testcases should have mechanism to fabric counters before and after the test. Test should assert if the counters are non-zero.

### Is it platform specific

generic

**Comment by kenneth-arista** [comment]
@jfeng-arista for awareness

**Comment by amitpawar12** [comment]
Function to clear and check the fabric counters is added. Will raise different issue if this needs to be integrated into the test-script.

The issue is addressed via PR #14097 and #14643.

Closing this issue.

Thanks,
-A
