### ISSUE TITLE
[Bug]: golden config infra test fails due to sanity checks after load_minigraph

### ISSUE THREAD

**Issue by mhen1** [sonic-net/sonic-mgmt#14327]
### Issue Description

The golden config infra test case (test_config_reload_with_rendered_golden_config.py) renders a temporary golden_config.json file using templates from the test, and then uses the command "config load_minigraph -y &>/dev/null -o -p /etc/sonic/golden_config_db.json" to apply the config to the DUT. The purpose of the test is to make sure the configurations in the temporary .json file are added to the running config, but it changes the entire configuration on the switch, which could lead to failures. For example, after running the command, the splits on the ports of the switches are different, and auto_neg configuration is different, and this different configuration could lead to failures of sanity checks like checking that interfaces are down.

### Results you see

Not all interfaces of the DUT come up after load minigraph due to invalid configurations from the command.

### Results you expected to see

All interfaces come up

### Is it platform specific

mellanox

### Output of `show version`

```shell
SONiC Software Version: SONiC.202405_RC.16-8c5f02079_Internal
SONiC OS Version: 12
Distribution: Debian 12.6
Kernel: 6.1.0-11-2-amd64
Build commit: 046c106f7
Build date: Wed Aug 28 10:57:10 UTC 2024
Built by: sw-r2d2-bot@r-build-sonic-ci03-242

Platform: x86_64-nvidia_sn5600-r0
HwSKU: ACS-SN5600
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2321XZ0JKW
Model Number: MSN-9N402-00RI-5CR
Hardware Revision: A1
Uptime: 11:28:36 up  9:24,  1 user,  load average: 1.50, 1.61, 1.60
Date: Thu 29 Aug 2024 11:28:36

Docker images:
REPOSITORY                                            TAG                               IMAGE ID       SIZE
docker-orchagent                                      202405_RC.16-8c5f02079_Internal   1701d14eddac   356MB
docker-orchagent                                      latest                            1701d14eddac   356MB
docker-teamd                                          202405_RC.16-8c5f02079_Internal   08c4d82a8f06   343MB
docker-teamd                                          latest                            08c4d82a8f06   343MB
docker-fpm-frr                                        202405_RC.16-8c5f02079_Internal   2248b30f2ea5   374MB
docker-fpm-frr                                        latest                            2248b30f2ea5   374MB
docker-sflow                                          202405_RC.16-8c5f02079_Internal   56ca25705952   344MB
docker-sflow                                          latest                            56ca25705952   344MB
docker-nat                                            202405_RC.16-8c5f02079_Internal   7bf1a7d327e7   345MB
docker-nat                                            latest                            7bf1a7d327e7   345MB
docker-syncd-mlnx                                     202405_RC.16-8c5f02079_Internal   779f8eb1e8fd   847MB
docker-syncd-mlnx                                     latest                            779f8eb1e8fd   847MB
docker-dhcp-relay                                     latest                            35daad25a889   324MB
docker-snmp                                           202405_RC.16-8c5f02079_Internal   aa84c219a537   354MB
docker-snmp                                           latest                            aa84c219a537   354MB
docker-macsec                                         latest                            8f75e83df31b   345MB
docker-sonic-mgmt-framework                           202405_RC.16-8c5f02079_Internal   5c42b831d74f   400MB
docker-sonic-mgmt-framework                           latest                            5c42b831d74f   400MB
docker-platform-monitor                               202405_RC.16-8c5f02079_Internal   62f29f25dbda   441MB
docker-platform-monitor                               latest                            62f29f25dbda   441MB
docker-router-advertiser                              202405_RC.16-8c5f02079_Internal   63b83388805f   314MB
docker-router-advertiser                              latest                            63b83388805f   314MB
docker-lldp                                           202405_RC.16-8c5f02079_Internal   65e9705b953b   360MB
docker-lldp                                           latest                            65e9705b953b   360MB
docker-database                                       202405_RC.16-8c5f02079_Internal   cd334db3d79c   323MB
docker-database                                       latest                            cd334db3d79c   323MB
docker-sonic-gnmi                                     202405_RC.16-8c5f02079_Internal   1c4381c1963e   398MB
docker-sonic-gnmi                                     latest                            1c4381c1963e   398MB
docker-eventd                                         202405_RC.16-8c5f02079_Internal   4d98eefa17b3   314MB
docker-eventd                                         latest                            4d98eefa17b3   314MB
docker-mux                                            202405_RC.16-8c5f02079_Internal   de1d033aac20   366MB
docker-mux                                            latest                            de1d033aac20   366MB
```

**Comment by mhen1** [comment]
Hey, @yejianquan 
To your attention.

**Comment by yejianquan** [comment]
Hi @wen587 , I double checked on a recent nightly test on Cisco 8800 202405, 
the testbed are found unhealthy after test_config_reload_with_rendered_golden_config.py.
Please take a look at this issue

**Comment by wen587** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/14421

**Comment by mhen1** [comment]
Hey @wen587,
The issue I described is different than the one @yejianquan mentioned (which I assume is the reason for the PR #14421). The test changes the entire configuration on the switch with the command "config load_minigraph -y &>/dev/null -o -p /etc/sonic/golden_config_db.json" (seems like a revert to the default configuration), and then tries to validate all interfaces are still up. This is not always the case since the command affects the general configuration like port splits and auto-neg, which might lead to some interfaces being down.

**Comment by wen587** [comment]
Hi @mhen1 , I don't get it. The temp golden_config_db.json rendered in this test didn't modify any existing tables.
[golden_config_override_with_general_template](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py#L86) actually render a {} golden config, which will do nothing to the full config.
[golden_config_override_with_specific_template](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py#L99) actually render a new table called [NEW_FEATURE ](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/golden_config_infra/templates/sample_golden_config_db.j2)which will do nothing to existing tables.

And after test, the CONFIG_DB has been replaced with original one to make sure nothing is changed before and after test. 
Did you try mually run this command with provided golden config? I don't think this will test will up or down some interfaces.

**Comment by mhen1** [comment]
Hey, please see the following scenario as example for configuration change:
config interface speed Ethernet80 50000
show interfaces status Ethernet80

  Interface            Lanes    **Speed**    MTU    FEC    Alias             Vlan    Oper    Admin             Type    Asym PFC
Ethernet80  160,161,162,163      **50G**   9100     rs    etp21  PortChannel1011    down       up  QSFP28 or later         off

cat /etc/sonic/golden_config_db.json
{}

config load_minigraph -y &>/dev/null -o -p /etc/sonic/golden_config_db.json

show interfaces status Ethernet80
  Interface            Lanes    **Speed**    MTU    FEC    Alias             Vlan    Oper    Admin             Type    Asym PFC
Ethernet80  160,161,162,163     **100G**   9100     rs    etp21  PortChannel1011      up       up  QSFP28 or later         off

 
As you can see, applying the empty golden_config_db.json on the switch via config load_minigraph does indeed change some of the configurations (reverts the speed to default, in this case). Is this the expected scenario?

In our case, this sort of change (also changes ports auto-neg and splits) lead to ports being down during the check [check_intf_up_ports=True](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py#L89).

**Comment by wen587** [comment]
Hi @mhen1 , yes, the speed is expected to change. Because `load_minigraph` will revert all config to default even without golden Config override.
The speed will revert back even you run `config load_minigraph -y`
Can I know your scenario? If you want the speed change persist in your test, it should be setup during test setup and revert to original after test done.

**Comment by mhen1** [comment]
> [golden_config_override_with_general_template](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py#L86) actually render a {} golden config, which will do nothing to the full config.

Ok, so what you said here is incorrect and the configuration will be different, right? If that's the case, I don't think we should have a check that interfaces are up, since there are cases when the switch cannot work properly with default configurations. Our scenario is we expect auto-neg to be enabled on certain ports, but it is disabled after the command runs - this makes the ports be in down state.
see the example here:

show interfaces autoneg status

  Interface    **Auto-Neg Mode**    Speed    Adv Speeds    Rmt Adv Speeds    Type    Adv Types    **Oper**    Admin
  Ethernet0          enabled     400G           N/A               N/A     N/A          N/A      up       up
  Ethernet8          enabled     400G           N/A               N/A     N/A          N/A      up       up
 Ethernet16         disabled     100G           N/A               N/A     N/A          N/A    down     down
 Ethernet24         disabled     100G           N/A               N/A     N/A          N/A    down     down
 Ethernet32          enabled     400G           N/A               N/A     N/A          N/A      up       up
 ... 
Ethernet120          **enabled**     400G           N/A               N/A     N/A          N/A      **up**       up
Ethernet128          **enabled**     400G           N/A               N/A     N/A          N/A      **up**       up
...
cat /etc/sonic/golden_config_db.json
{}
config load_minigraph -y &>/dev/null -o -p /etc/sonic/golden_config_db.json

show interfaces autoneg status
  Interface    **Auto-Neg Mode**    Speed    Adv Speeds    Rmt Adv Speeds    Type    Adv Types    **Oper**    Admin
  Ethernet0         disabled     400G           N/A               N/A     N/A          N/A      up       up
  Ethernet8         disabled     400G           N/A               N/A     N/A          N/A      up       up
 Ethernet16         disabled     100G           N/A               N/A     N/A          N/A    down     down
 Ethernet24         disabled     100G           N/A               N/A     N/A          N/A    down     down
 Ethernet32         disabled     400G           N/A               N/A     N/A          N/A      up       up
 ...
Ethernet120         **disabled**     400G           N/A               N/A     N/A          N/A    **down**       up
Ethernet128         **disabled**     400G           N/A               N/A     N/A          N/A    **down**       up
 ...

**Comment by wen587** [comment]
@mhen1 , sorry I need more clarification.
1.are you setup your own test env by the command of config_reload_minigraph_with_rendered_golden_config_override? or you are running another test independent with the infra test.
2.from the code of check_intf_up, it didn't run any up command. It just wait extra time: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/config_reload.py#L210-L211, which means that even you don't set flag true, it will also up ports some time later. In this case, how do you make sure your test is stable.
3.Did you try run your test without the infra test? Because I do see other test has also set this flag. Why your test is not impacted by those test? e.g. https://github.com/sonic-net/sonic-mgmt/blob/master/tests/acl/test_acl_outer_vlan.py#L261

**Comment by mhen1** [comment]
Hey @wen587,
I'm running the test file "tests/golden_config_infra/test_config_reload_with_rendered_golden_config.py" as a whole. 
I will try to clarify the issue I described.
The problem isn't with the check_intf_up flag itself. The flag is meant to check that all interfaces in admin state up are also in oper state up after a reload.
The issue is that during the test, when we apply the golden_config (using config load minigraph), it also resets the DUT to its default settings (as you verified). One of these resets might affect auto-neg settings on some ports.
For some of our ports, auto-neg needs to be disabled for them to achieve oper status up. When auto-neg gets changed during the reload, the check_intf_up fails because it expects all the admin up ports to be oper up, but they aren't, due to the auto-neg change.
That's why I suggested setting the flag to False. If the test's main goal is just to verify the new config tables, then checking the port status might be unnecessary. The test passes on our systems when using this change:
config_reload_minigraph_with_rendered_golden_config_override(
    duthost, safe_reload=True, check_intf_up_ports=**False**
)

**Comment by wen587** [comment]
Hi @mhen1 , I still don't think it is a golden config issue. {} will not change any table of the full configuration. 
Here I want to clarify one thing, the Golden Config override will only modify table that exists in golden_config_db.json, if it is {} in golden config, it will just bypass all the override.

When we run 
`config_reload_minigraph_with_rendered_golden_config_override(duthost, safe_reload=True, check_intf_up_ports=False)` with `{}` in Golden Config.
The final config is the same as `config_reload(duthost, config_source='minigraph', safe_reload=True, check_intf_up_ports=True)` without override.

My doubt is that if this golden infra test will fail in your testbed because some ports are not oper up, it should also fail with other tests that has flag of `check_intf_up_ports=True`, such as [test_traffic_shift.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/bgp/test_traffic_shift.py#L590-L591), [nat conftest.py](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/nat/conftest.py#L210)

Could you check if any of two test also fail in your testbed setup?
