### ISSUE TITLE
[Bug]: test_authorization_tacacs_only fails on chassis supervisor due to unsupported commands

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#14506]
### Issue Description

`test_authorization_tacacs_only` checks a list of commands to ensure proper permissions through tacas auth.  Some of these commands fail when executed on the supervisor of our chassis (they work correctly on linecards):

```
show ip bgp neighbor
show ip bgp summary
show ipv6 bgp neighbor
show ipv6 bgp summary
show muxcable firmware
```

A recent change enabled `show ip bgp neighbor` and `show ip bgp summary` to run on the supervisor, but now they trigger the command execution on each of the linecards, prompting for password.  If running the command manually, the results are as expected, but executed by `test_authorization_tacacs_only`, the test gets stuck on the prompt.

```
root@nfc405:~# show ip bgp neighbor
Since the current device is a chassis supervisor, this command will be executed remotely on all linecards
Password for username 'root':
```

`show ipv6 bgp neighbor`, `show ipv6 bgp summary`, and `show muxcable firmware` currently fail when executed on the supervisor:

```
root@nfc405:~# show ipv6 bgp neighbor
Error response from daemon: Container c6742f35ae99361ef1639178eb38024a5d1f2c4e074563c53f9d73d7049d0321 is not running

root@nfc405:~# show ipv6 bgp summary

IPv6 Unicast Summary:
Usage: show ipv6 bgp summary [OPTIONS]
Try "show ipv6 bgp summary -h" for help.

Error: router_info missing in the bgp_summary
root@nfc405:~# show muxcable firmware
Failed to get port config
```

Will these commands also be updated to work like `show ip bgp neighbor` and get the info from the linecards?  Would it make sense to skip these commands when `test_authorization_tacacs_only` runs on the supervisor?

### Results you see

see description

### Results you expected to see

test_authorization_tacacs_only should pass on supervisor and linecards

### Is it platform specific

generic

**Comment by rlhui** [comment]
@veronica-arista  please rerun with latest 202405 to get latest result, also @BYGX-wcr please help here as well.  We'd like to see this test case including these bgp commands that are newly added to sup and can pass for chassis.

**Comment by BYGX-wcr** [comment]
@veronica-arista , currently we haven't added the support for direct execution of ```show ipv6 bgp neighbor```, ```show ipv6 bgp summary```, and ```show muxcable firmware```. We will add the support later. Now you can skip those commands or use rexec command to execute those commands on chassis supervisor. Besides, to make the all rexec commands work, the test cases need to be enhanced to be able to input passwords of linecards

**Comment by BYGX-wcr** [comment]
Since the fix PR is already merged, I closed this Issue.
