### ISSUE TITLE
[Test Gap][arp_update][t0] Missing test for kernel/ASIC neighbor mismatch

### ISSUE THREAD

**Issue by theasianpianist** [sonic-net/sonic-mgmt#14525]
### Test Gap Description

It is possible for neighbor entries in the kernel and in ASIC_DB to fall out of sync, resulting in two different MACs for the same IP which disrupts traffic. We need to verify that SONiC can automatically detect/recover from this situation.

### Test Plan

Add a new test case to force a kernel/ASIC_DB mismatch, then verify that the mismatch is automatically detected and the neighbor is flushed.

**Comment by prsunny** [comment]
Reference example: 

ARP in kernel:
10.106.36.118  **00:00:00:05:e8:4f**  PortChannel26    - 
 

ARP in DB:
127.0.0.1:6379> hgetall "NEIGH_TABLE:PortChannel26:10.106.36.118" 
1) "neigh" 
**2) "00:00:00:00:5d:31"** 
3) "family" 
4) "IPv4"
