### ISSUE TITLE
[Bug]: counterpoll watermark test does not support multi-asic

### ISSUE THREAD

**Issue by liamkearney-msft** [sonic-net/sonic-mgmt#14753]
### Issue Description

counterpoll watermark tests fail on multi-asic linecards as they do not look at the namespaced database containers. Refactor the tests to support multi-asic

### Results you see

COUNTER_DB is not detected as populated in multi asic devices because the test does not look at the database container for each asic

### Results you expected to see

COUNTER_DB is populated for each individual linecard, test should look at the proper database container

### Is it platform specific

generic

**Comment by auspham** [comment]
Hi @liamkearney-msft I'm working on this. Will get your PR review
