### ISSUE TITLE
[Bug]: [202405] lldp/test_lldp_syncd.py failing on 202405 branch due to mising hget_all() function

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#14816]
### Issue Description

Ran the newly added lldp/test_lldp_syncd.py (https://github.com/sonic-net/sonic-mgmt/pull/14658) and ran into `E       AttributeError: 'SonicDbCli' object has no attribute 'hget_all'`

The cause is that the `hget_all()` function from `tests/common/helpers/sonic_db.py` is present in the master branch but not merged to 202405 branch.  Looks like the PR that added this function to master (https://github.com/sonic-net/sonic-mgmt/pull/13574) was approved for 202405 but is no longer due to merge conflict.  Can we get this resolved and merged to fix this issue?

### Results you see

lldp/test_lldp_syncd.py fails with `E       AttributeError: 'SonicDbCli' object has no attribute 'hget_all'`

### Results you expected to see

`hget_all` function should exist in 202405

### Is it platform specific

generic

**Comment by ZhaohuiS** [comment]
hget_all was removed by https://github.com/sonic-net/sonic-mgmt/pull/14565/files#diff-6d2fdf2c5daf541ff69fc9749a3424ca913066ed02ee24973ff4d8c85a51ec5b
It's added back in https://github.com/sonic-net/sonic-mgmt/pull/14846, which is in review.
