### ISSUE TITLE
[Test Gap]: Chassis: Route Consistency across linecards upon process Crash

### ISSUE THREAD

**Issue by deepak-singhal0408** [sonic-net/sonic-mgmt#14983]
### Test Gap Description

When Process Crashes(swss/syncd) on Linecard A, All the local links go down, which means all the eBGP sessions go down and will inturn have route withdraws, which will get propagated to remote linecards, Say Linecard B.

Due to autorestart feature, the process crash should recover and the links should come up, ebgp sessions should get established, and the same amount of routes should be learnt back.

### Test Plan

New test case to check/compare route snapshots before and after process crash on all linecards of a chassis.
Below file has couple of test cases for route_consistency(advertise/withdraw/bgp shut noshut)
Reference: https://github.com/sonic-net/sonic-mgmt/blob/master/tests/route/test_route_consistency.py

### Test environment

SONiC T2 Chassis

**Comment by deepak-singhal0408** [comment]
MSFT ADO: 29852608

**Comment by BYGX-wcr** [comment]
Already resolved.
