### ISSUE TITLE
[Bug]: test_drop_packets/test_unicast_ip_incorrect_eth_dst: Drop Counter mismatch for Port channel when the member of the PC are different core of the ASIC 

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-mgmt#15051]
### Issue Description

[Bug]: test_drop_packets/test_unicast_ip_incorrect_eth_dst - Drop Counter mismatch for Port Channel when members belong to different ASIC cores.

Description: The test case expects broadcast packets to be dropped. However, when a Port Channel is randomly selected, and its members span different cores of the ASIC, the drop counter does not accurately reflect the packet drops as expected

### Results you see

The Drop Counter in show int counter doesn't get updated

### Results you expected to see

The Drop Counter in show int counter should get updated

### Is it platform specific

generic

### Output of `show version`

```shell
Master/2405
```

**Comment by saksarav-nokia** [comment]
This is seen in BCM DNX platform with Nokia chassis.Created a BCM csp CS00012373986 .
 Please assign this issue to me

**Comment by saksarav-nokia** [comment]
BCM has submitted the fix in SAI 11.2.16.1

**Comment by saksarav-nokia** [comment]
@vikshaw-Nokia , could you please verify with latest image and close this since the fix is already committed.

**Comment by vikshaw-Nokia** [comment]
Fixed
