### ISSUE TITLE
[Bug]: eth0 in 'show lldp table'

### ISSUE THREAD

**Issue by ghost** [sonic-net/sonic-mgmt#15089]
### Issue Description

@ZhaohuiS 

**test_lldp_syncd.py testsuite was created by this PR https://github.com/sonic-net/sonic-mgmt/pull/14216.**

test_lldp_entry_table_after_lldp_restart() testcase is calling verify_lldp_table() to check if eth0 is there after lldp restarted.

Snippet:
def test_lldp_entry_table_after_lldp_restart(
    duthosts, enum_rand_one_per_hwsku_frontend_hostname, db_instance
):
    duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
    lldp_entry_keys = get_lldp_entry_keys(db_instance)
    show_lldp_table_int_list = get_show_lldp_table_output(duthost)
    lldpctl_output = get_lldpctl_output(duthost)

    # Restart the LLDP service
    duthost.shell("sudo systemctl restart lldp")
    result = wait_until(
        60, 2, 5, verify_lldp_table, duthost    **=>verify_lldp_table will check if eth0 in show output and return false into result and failed the pytest_assert() below**
    pytest_assert(result, "eth0 is still not in output of show lldp table")
    )
…

def verify_lldp_table(duthost):
    # based on experience, eth0 shows up at last  **=>code-owner's comment**
    output = duthost.shell("show lldp table")["stdout"]
    if "eth0" in output:
        return True
    else:
        return False

### Results you see

    def test_lldp_entry_table_after_lldp_restart(
        duthosts, enum_rand_one_per_hwsku_frontend_hostname, db_instance
    ):
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        lldp_entry_keys = get_lldp_entry_keys(db_instance)
        show_lldp_table_int_list = get_show_lldp_table_output(duthost)
        lldpctl_output = get_lldpctl_output(duthost)
    
        # Restart the LLDP service
        duthost.shell("sudo systemctl restart lldp")
    #    pdb.set_trace()
        result = wait_until(
            60, 2, 5, verify_lldp_table, duthost
        )  # Adjust based on LLDP service restart time
&gt;       pytest_assert(result, "eth0 is still not in output of show lldp table")
E       Failed: eth0 is still not in output of show lldp table

### Results you expected to see

verify_lldp_table() shouldn't be checking eth0 as an expected interface to determine if lldp restart is completed since not all topology may necessary to have eth0.

### Is it platform specific

generic

**Comment by ZhaohuiS** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/15098 to address this issue

**Comment by ZhaohuiS** [comment]
PR https://github.com/sonic-net/sonic-mgmt/pull/15098 to address this issue.
Close it
