### ISSUE TITLE
[Bug]:  tacacs/test_authorization::test_authorization_tacacs_only fails on Supervisor card because it is checking for show ip bgp neighbor

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#15133]
### Issue Description

The issue is the command on supervisor expects a password. Since it is being run on the supervisor. The testcase doesn't support that feature, hence it fails

Since the current device is a chassis supervisor, this command will be executed remotely on all linecards
Password for username 'cisco':

### Results you see

for subcommand in commands:
            exit_code, stdout, stderr = ssh_run_command(remote_user_client, subcommand)
>           pytest_assert(exit_code == 0)
E           Failed: None

check_tacacs = None
commands   = ['show interfaces counters -a -p 3', 'show ip bgp neighbor', 'show ipv6 bgp neighbor', 'touch testfile', 'chmod +w testfile', 'echo "test" > testfile', ...]
duthost    = <MultiAsicSonicHost aaa14-rp>
duthosts   = [<MultiAsicSonicHost aaa14-lc0>, <MultiAsicSonicHost aaa14-lc1>, <MultiAsicSonicHost aaa14-lc2>, <MultiAsicSonicHost aaa14-rp>]
enum_rand_one_per_hwsku_hostname = 'aaa14-rp'
exit_code  = 1
gnmi_is_running = True
remote_rw_user_client = <paramiko.client.SSHClient object at 0x7f40afee7670>
remote_user_client = <paramiko.client.SSHClient object at 0x7f40bd488e50>
setup_authorization_tacacs = None
stderr     = <paramiko.ChannelFile from <paramiko.Channel 4 (closed) -> <paramiko.Transport at 0xae962fa0 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>>>
stdout     = <paramiko.ChannelFile from <paramiko.Channel 4 (closed) -> <paramiko.Transport at 0xae962fa0 (cipher aes128-ctr, 128 bits) (active; 0 open channel(s))>>>
subcommand = 'show ip bgp neighbor'
telemetry_is_running = False

### Results you expected to see

Either add support for password or remove the test for Supervisor

### Is it platform specific

generic

**Comment by vperumal** [comment]
FYI @abdosi @yejianquan

**Comment by yejianquan** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/15156 should fix this failure, will close it after the newest test passes

**Comment by yejianquan** [comment]
tacacs/test_authorization.py::test_authorization_tacacs_only[**-lc1-1] PASSED [  3%]
tacacs/test_authorization.py::test_authorization_tacacs_only_some_server_down[**-lc1-1] PASSED [  6%]
tacacs/test_authorization.py::test_authorization_tacacs_only_then_server_down_after_login[**-lc1-1] PASSED [  9%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local[**-lc1-1] SKIPPED [ 12%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local_then_server_down_after_login[**-lc1-1] SKIPPED [ 15%]
tacacs/test_authorization.py::test_authorization_local[**-lc1-1] PASSED [ 18%]
tacacs/test_authorization.py::test_bypass_authorization[**-lc1-1] PASSED [ 21%]
tacacs/test_authorization.py::test_backward_compatibility_disable_authorization[**-lc1-1] PASSED [ 24%]
tacacs/test_authorization.py::test_tacacs_authorization_wildcard[**-lc1-1] PASSED [ 27%]
tacacs/test_authorization.py::test_stop_request_next_server_after_reject[**-lc1-1] 
-------------------------------- live log call ---------------------------------
17:58:22 test_authorization.test_stop_request_nex L0627 WARNING| ['Sun Nov  3 17:58:21 2024 [17163]: exec authorization request for invalid_user']
PASSED                                                                   [ 30%]
tacacs/test_authorization.py::test_fallback_to_local_authorization_with_config_reload[**-lc1-1] SKIPPED [ 33%]
tacacs/test_authorization.py::test_authorization_tacacs_only[**-lc3-1] PASSED [ 36%]
tacacs/test_authorization.py::test_authorization_tacacs_only_some_server_down[**-lc3-1] PASSED [ 39%]
tacacs/test_authorization.py::test_authorization_tacacs_only_then_server_down_after_login[**-lc3-1] PASSED [ 42%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local[**-lc3-1] SKIPPED [ 45%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local_then_server_down_after_login[**-lc3-1] SKIPPED [ 48%]
tacacs/test_authorization.py::test_authorization_local[**-lc3-1] PASSED [ 51%]
tacacs/test_authorization.py::test_bypass_authorization[**-lc3-1] PASSED [ 54%]
tacacs/test_authorization.py::test_backward_compatibility_disable_authorization[**-lc3-1] PASSED [ 57%]
tacacs/test_authorization.py::test_tacacs_authorization_wildcard[**-lc3-1] PASSED [ 60%]
tacacs/test_authorization.py::test_stop_request_next_server_after_reject[**-lc3-1] 
-------------------------------- live log call ---------------------------------
18:03:42 test_authorization.test_stop_request_nex L0627 WARNING| ['Sun Nov  3 18:03:41 2024 [18111]: exec authorization request for invalid_user']
PASSED                                                                   [ 63%]
tacacs/test_authorization.py::test_fallback_to_local_authorization_with_config_reload[**-lc3-1] SKIPPED [ 66%]
tacacs/test_authorization.py::test_authorization_tacacs_only[**-sup-1] PASSED [ 69%]
tacacs/test_authorization.py::test_authorization_tacacs_only_some_server_down[**-sup-1] PASSED [ 72%]
tacacs/test_authorization.py::test_authorization_tacacs_only_then_server_down_after_login[**-sup-1] PASSED [ 75%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local[**-sup-1] SKIPPED [ 78%]
tacacs/test_authorization.py::test_authorization_tacacs_and_local_then_server_down_after_login[**-sup-1] SKIPPED [ 81%]
tacacs/test_authorization.py::test_authorization_local[**-sup-1] PASSED [ 84%]
tacacs/test_authorization.py::test_bypass_authorization[**-sup-1] PASSED [ 87%]
tacacs/test_authorization.py::test_backward_compatibility_disable_authorization[**-sup-1] PASSED [ 90%]
tacacs/test_authorization.py::test_tacacs_authorization_wildcard[**-sup-1] PASSED [ 93%]
tacacs/test_authorization.py::test_stop_request_next_server_after_reject[**-sup-1] 
-------------------------------- live log call ---------------------------------
18:10:37 test_authorization.test_stop_request_nex L0627 WARNING| ['Sun Nov  3 18:10:35 2024 [19006]: exec authorization request for invalid_user']
PASSED                                                                   [ 96%]
tacacs/test_authorization.py::test_fallback_to_local_authorization_with_config_reload[**-sup-1] SKIPPED [100%]DEBUG:tests.conftest:[log_custom_msg] item: <Function test_fallback_to_local_authorization_with_config_reload[**-sup-1]>
INFO:root:Can not get Allure report URL. Please check logs
