### ISSUE TITLE
[Bug]: [ACL][DualTor] test_acl.py ingress-uplink->downlink forward test cases are failing due to muxcable keepalive packets are droped by acl rules

### ISSUE THREAD

**Issue by echuawu** [sonic-net/sonic-mgmt#15206]
### Issue Description

On Dualtor setup, all the ingress-uplink->downlink forward test cases of test_acl.py are failing.
For dual ToR setups, it relies on a set of loopback interfaces for the servers to keep alive between each tor to understand their state (active or standby)
In the test, it generates a series of ACL entries to be applied and verified.
By default there is a "discard all" entry in each ACL table, which breaks the keep alive path on the dual ToR setup.

### Results you see

1. Expected packets would not be received.
2. Muxcable status keeps in standby mode in both upper and lower tor.

### Results you expected to see

In ingress-uplink->downlink forward test cases:
1. The acl rules should cares the muxcable keep alive packets between test server and switches.
2. The muxcable status should not in standby mode in both side.
3. Test expected packets should be received correctly.

### Is it platform specific

generic

**Comment by bingwang-ms** [comment]
@echuawu Can you update the test to allow heartbeat?

**Comment by echuawu** [comment]
> @echuawu Can you update the test to allow heartbeat?

Sure, it's in plan.
