### ISSUE TITLE
[Bug]: [QoS][DualTor AA] All the cases of test_qos_sai.py failed at DualTor AA topology due to "Failed to toggle all mux cables to lower_tor"

### ISSUE THREAD

**Issue by echuawu** [sonic-net/sonic-mgmt#15205]
### Issue Description

test_qos_sai.py have not been integrated on Dualtor AA topology. All the cases would be failed due to "Failed to toggle all mux cables to lower_tor".

### Results you see

All the cases would be failed due to "Failed to toggle all mux cables to lower_tor".

### Results you expected to see

All the cases could be run PASS.

### Is it platform specific

generic

**Comment by bingwang-ms** [comment]
@lolyu Can you please check if we have same issue on other dualtor-aa testbed?

**Comment by lolyu** [comment]
Hi @echuawu, could you please share the test log/techsupport?

**Comment by echuawu** [comment]
@lolyu , all the cases failed at dualtor-aa setup.
![image](https://github.com/user-attachments/assets/23963957-ef66-4d36-9077-9bb616da0e92)

**Comment by bingwang-ms** [comment]
@lolyu Can you please check and reply?

**Comment by lolyu** [comment]
@echuawu, these testcases are skipped previously, and due to the skip condition change (https://github.com/sonic-net/sonic-mgmt/pull/14395), their skip conditions didn't hold true anymore.

**Comment by echuawu** [comment]
> @echuawu, these testcases are skipped previously, and due to the skip condition change (#14395), their skip conditions didn't hold true anymore.

Hi @lolyu , would you plan to skip the qos sai test on dualtor aa setup? Or have a plan to enhance the script?

**Comment by lolyu** [comment]
This should be fixed by: https://github.com/sonic-net/sonic-mgmt/pull/15563
