### ISSUE TITLE
[202405] - `snmp` package doesn't run due to `setup_check_snmp_ready` fixture function has more than one 'yield'

### ISSUE THREAD

**Issue by arista-nwolfe** [sonic-net/sonic-mgmt#15514]
### Issue Description

`setup_check_snmp_ready` was updated recently by https://github.com/sonic-net/sonic-mgmt/pull/14926

This introduced a `for` loop over the `duthosts` but the yield is nested in the for loop resulting in multiple `yield` calls in a fixture
```
/data/tests/snmp/conftest.py:11&quot;">fixture function has more than one 'yield'

    @pytest.fixture(scope="module", autouse=True)
    def setup_check_snmp_ready(duthosts, localhost):
        for duthost in duthosts:
...
            yield
...
            localhost.shell(local_command)
/data/tests/snmp/conftest.py:11</error></testcase></testsuite></testsuites>
```

Possibly the yield was meant to be run after the for loop is completed?

### Results you see

`yield` being called multiple times within fixture `setup_check_snmp_ready`

### Results you expected to see

`yield` should only be called once within a fixture

### Is it platform specific

generic

**Comment by vkjammala-arista** [comment]
Just noticed this issue, I have raised https://github.com/sonic-net/sonic-mgmt/pull/15529 fixing the issue.

**Comment by arista-nwolfe** [comment]
Closing this issue as https://github.com/sonic-net/sonic-mgmt/pull/15529 has merged
