### ISSUE TITLE
[Bug]: check_pmon_daemon_status always return False on Mellanox-SN2700

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#15852]
### Issue Description

The issue was seen after PR [[202405] Delay pmon non-critical daemon by yuazhe · Pull Request #20879 · sonic-net/sonic-buildimage](https://github.com/sonic-net/sonic-buildimage/pull/20879)

It's because the daemon `delay` will be in `exit` state, which is expected.

### Results you see

![image](https://github.com/user-attachments/assets/df968a95-bd64-4099-8e9a-d13320105606)

### Results you expected to see

Test should pass.

### Is it platform specific

mellanox

### Output of `show version`

```shell
admin@strtk5-msn2700-01:~$ show ver

SONiC Software Version: SONiC.20240510.16
SONiC OS Version: 12
Distribution: Debian 12.6
Kernel: 6.1.0-22-2-amd64
Build commit: 383f375c88
Build date: Sun Dec  1 04:28:11 UTC 2024
Built by: azureuser@0c812cb1c000000

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
```

**Comment by bingwang-ms** [comment]
@yuazhe Can you help take a look?

**Comment by yuazhe** [comment]
@bingwang-ms This is a testing case issue, fix pr had been created https://github.com/sonic-net/sonic-mgmt/pull/15873
