### ISSUE TITLE
[everflow_testbed] Test fails randomly

### ISSUE THREAD

**Issue by shlomibitton** [sonic-net/sonic-mgmt#2145]
**Description**
everflow_testbed test is failing randomly on various platforms with t1-lag topology.

**Steps to reproduce the issue:**
1. Deploy t1-lag topology on a switch.
2. Run everflow_testbed test and observe if the issue reproduced.

**Describe the results you received:**
A full system dump and test log is provided:
[everflow_testbed_test_log.txt](https://github.com/Azure/sonic-mgmt/files/5134720/everflow_testbed_test_log.txt)
[sonic_dump_arc-switch1038_20200818_162014.tar.gz](https://github.com/Azure/sonic-mgmt/files/5134725/sonic_dump_arc-switch1038_20200818_162014.tar.gz)

**Describe the results you expected:**
Test should always pass.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by daall** [comment]
@shlomibitton can you double-check for me that it's this specific test case TestEverflowV4EgressAclEgressMirror::test_everflow_dscp_with_policer) that is failing periodically, or if there are others as well?

Trying to narrow down the repro further. Thank you!
