### ISSUE TITLE
show snmp counters unavailable failing test_ft_snmp_trap_counter

### ISSUE THREAD

**Issue by tbgowda** [sonic-net/sonic-mgmt#3043]
Hello,

In spytest/apis/system/snmp.py, we have a method called show_snmp_counters (and clear snmp counters) which is being called by test_ft_snmp_trap_counter and test_ft_snmp_basic_counters. 

show_snmp_counters tries to run "show snmp counters" on the DUT. However, on the DUT there is no "show snmp counters" in klish CLI. What could be missing?

The DUT is running :

SONiC Software Version: SONiC.master.565-e0781f46
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: e0781f46
Build date: Mon Nov 23 08:32:04 UTC 2020
Built by: johnar@jenkins-worker-12

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
Serial Number: 000000
Uptime: 03:01:08 up 1 day,  4:44,  1 user,  load average: 0.45, 0.81, 0.67

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-gbsyncd-vs             latest                fc2bcaf7dc91        447MB
docker-gbsyncd-vs             master.565-e0781f46   fc2bcaf7dc91        447MB
docker-syncd-vs               latest                a599f4b6a7c9        447MB
docker-syncd-vs               master.565-e0781f46   a599f4b6a7c9        447MB
docker-snmp                   latest                72953533ec0e        477MB
docker-snmp                   master.565-e0781f46   72953533ec0e        477MB
docker-teamd                  latest                0392627a102f        483MB
docker-teamd                  master.565-e0781f46   0392627a102f        483MB
docker-nat                    latest                61210a29630f        486MB
docker-nat                    master.565-e0781f46   61210a29630f        486MB
docker-router-advertiser      latest                dcc0e15c5463        441MB
docker-router-advertiser      master.565-e0781f46   dcc0e15c5463        441MB
docker-platform-monitor       latest                053ce63c0b8f        563MB
docker-platform-monitor       master.565-e0781f46   053ce63c0b8f        563MB
docker-lldp                   latest                c68597acb666        514MB
docker-lldp                   master.565-e0781f46   c68597acb666        514MB
docker-dhcp-relay             latest                badb3fb27c4e        448MB
docker-dhcp-relay             master.565-e0781f46   badb3fb27c4e        448MB
docker-database               latest                d92f5b4cb6e0        441MB
docker-database               master.565-e0781f46   d92f5b4cb6e0        441MB
docker-orchagent              latest                d9c215c333d9        497MB
docker-orchagent              master.565-e0781f46   d9c215c333d9        497MB
docker-sonic-telemetry        latest                26941527084a        511MB
docker-sonic-telemetry        master.565-e0781f46   26941527084a        511MB
docker-sonic-mgmt-framework   latest                d92d56dac3a5        598MB
docker-sonic-mgmt-framework   master.565-e0781f46   d92d56dac3a5        598MB
docker-fpm-frr                latest                6c139d86ef63        500MB
docker-fpm-frr                master.565-e0781f46   6c139d86ef63        500MB
docker-sflow                  latest                883128578286        484MB
docker-sflow                  master.565-e0781f46   883128578286        484MB

**Comment by yxieca** [comment]
@ramakristipati please help
