### ISSUE TITLE
SNMP link up/down traps not working

### ISSUE THREAD

**Issue by tbgowda** [sonic-net/sonic-mgmt#3055]
Hello,

The tests for SNMP link up/down traps doesn't seem to work. It turns out that sonic-snmpagent doesn't have support for link up and down traps yet.

There is a proposal to provide the support through : https://github.com/Azure/sonic-snmpagent/pull/187

This has not been integrated with the Sonic software yet. Given this, is it expected that these tests will fail ?

spytest/tests/system/test_snmp.py :: test_ft_snmp_link_down_trap 
spytest/tests/system/test_snmp.py :: test_ft_snmp_link_up_trap

Thanks

**Comment by yxieca** [comment]
@tbgowda Thanks for finding the answer. I think you are right.

**Comment by ramakristipati** [comment]
Yes these are not supported

Please find the below lines in reporting/suites/community-ixia to exclude from the run

-test:test_ft_snmp_link_down_trap
-test:test_ft_snmp_link_down_trap

**Comment by ramakristipati** [comment]
unsupported tests are excluded in the suite file
