### ISSUE TITLE
Need new test: Sub-second reboot

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3585]
**Description**

This is a test gap:

Integrated SLB test scenario: dynamic sessions got closed during warm reboot. Reestablish after warm reboot is done.

**Comment by kamalsahu0001** [comment]
Hi Kevin,

Can you elaborate more on what are the dynamic sessions which got closed during warm reboot? 
Is it like verify BGP session/LAG is coming back up after warm reboot is done?

**Comment by vaibhavhd** [comment]
This will be added to upgrade path testcase's list of checks to be done at every hop.

**Comment by vaibhavhd** [comment]
@lolyu , I think your PR for `test_bgp_slb_neighbor_persistence_across_advanced_reboot` will address the gap that is raised here.

Do you agree? 

PR: https://github.com/sonic-net/sonic-mgmt/pull/4646

**Comment by lolyu** [comment]
@vaibhavhd, yes, this should be covered by PR #4646

**Comment by vaibhavhd** [comment]
Closing this test gap as the case `test_bgp_slb_neighbor_persistence_across_advanced_reboot ` has already been added.
