### ISSUE TITLE
Need new test: Protocols/Technology - IPv4 and IPv6

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3602]
This is a test gap:
Arp and neighbor_mac covers basic scenarios. Need test to cover our IPv4/IPv6 neighbor refresh test. Prince to add more detail by revisiting the IPv6 incident in AZAP

**Comment by yxieca** [comment]
@prsunny  can you add more details?

**Comment by StormLiangMS** [comment]
hi @prsunny this one seems a dataplane related test gap, assigned to you for further triage.

**Comment by prsunny** [comment]
The test requirement is not clear. @kevinskwang , do you've more details. if not prefer to close this.
