### ISSUE TITLE
Need new test: BGP-Convergence

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3608]
This is a test gap:

Need to add BGP convergence test.

**Comment by yxieca** [comment]
Convergence: Route should be program first in FIB and then advertised

**Comment by kamalsahu0001** [comment]
Keysight will be taking care of this test case. We already have the RIB-IN Convergence test covered in BGP Convergence test plan. In our case, we are verifying that initially there won't be any traffic flowing and once we start advertising the routes, we are measuring the time it takes to install in FIB and then to forward the traffic and no traffic loss once all the routes are advertised. Will this verification steps satisfies the test case? or we need any additional verification steps?

**Comment by wsycqyz** [comment]
Currently there is testplan:
docs/testplan/BGP Convergence Testplan for single DUT.md
docs/testplan/BGP-Convergence-Testplan-for-Benchmark-Performance.md.

there is testcase:
tests/snappi_tests/bgp/test_bgp_convergence_performance.py
tests/snappi_tests/bgp/test_bgp_rib_in_convergence.py

I have read these documents and found the current tests cover the most common scenarios.

@StormLiangMS Let's discuss offline to see if there is any gap here.
@yxieca FYI.

**Comment by wsycqyz** [comment]
Following PR has been merged for this test gap. So close this test gap as finished.
PR#2926
PR#3715
PR#5098

**Comment by wsycqyz** [comment]
Following PR has been merged for this test gap. So close this test gap as finished.
PR https://github.com/sonic-net/sonic-mgmt/pull/2926
PR https://github.com/sonic-net/sonic-mgmt/pull/3715
PR https://github.com/sonic-net/sonic-mgmt/pull/5098
