### ISSUE TITLE
Need new test: BGP-Scalability

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3609]
This is a test gap:

Need to add BGP scalability test.

**Comment by kamalsahu0001** [comment]
Hi Kevin,

Expectation here is to scale BGP sessions as well as the routes?

**Comment by kamalsahu0001** [comment]
Hi @yxieca,

Difference between step 1 and 5? In step 1 we will already hit the limit right. Step 5 is to see even after hitting the 16K limit, how it behaves when we advertise 100K ipv4 prefix and 25K ipv6 prefixes?

**Comment by kamalsahu0001** [comment]
Keysight will be taking care of this test case. We have the script already defined in BGP convergence test plan. Will add new verification steps to look for the warning messages in console and in syslog.  Will raise a separate PR in order to cover these BGP cases.
