### ISSUE TITLE
Need new test: BGP-Standard 3 ports BGP Routing Convergence Time (Control Plane and Data Plane)

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3610]
This is a test gap

**Comment by kamalsahu0001** [comment]
Hi @yxieca,

This is w.r.t to ECMP or without ECMP behavior?

**Comment by yxieca** [comment]
> Hi @yxieca,
> 
> This is w.r.t to ECMP or without ECMP behavior?

I think we care more about with ECMP. Don't mind if test covers both.

**Comment by kamalsahu0001** [comment]
Keysight will be taking care of this test case. Currently we have this implemented as part of our BGP convergence test plan. Modified current case to handle step 3 outlined above.
