### ISSUE TITLE
Need new test: Performance Testing

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3613]
Test throughput of various packet sizes under different scenarios (To be described)

**Comment by kamalsahu0001** [comment]
Hi Kevin,

Can you elaborate what exactly you are looking under Performance Testing?

**Comment by yxieca** [comment]
Scenarios including: regular IO, GRE, 802.1q in VRF/GRT etc.

**Comment by StormLiangMS** [comment]
hi @prsunny  this one seems a dataplane related test gap, assigned to you for further triage.

**Comment by prsunny** [comment]
This is a very old test gap and we do have stress test currently. Im closing this and can create new one based on specific requirement
