### ISSUE TITLE
Need new test: DHCP Storm

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#3614]
This is a test gap:

Need to handle capability test without CoPP protection.

**Comment by yxieca** [comment]
COPP test proved that we only lift x mount of packet for DHCP into CPU port. However, during COPP test, the upper layer services are shutdown to prevent packet count contaminations. This test is to make sure that the DHCP relay service can survive the max load that we lift to CPU.

**Comment by kevinskwang** [comment]
@yyynini could you help to take a look of this test gap?
