### ISSUE TITLE
num_asic instead of num_asics used in TestbedProcessing file.

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#3997]
**Description**

In TestbedProcessing file - for makeLab proc, it is trying to access num_asic instead of num_asics. 

python TestbedProcessing.py -i testbed.yaml
PROCESS STARTED
BACKUP PROCESS STARTED
Error: could not back up group_vars/eos/creds.yml
BACKUP PROCESS COMPLETED
LOADING PROCESS STARTED
LOADING: testbed.yaml
TestbedProcessing.py:642: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  doc = yaml.load(open(args.i, 'r'))
LOADING PROCESS COMPLETED
GENERATING FILES FROM CONFIG FILE
	CREATING SONIC LAB LINKS: files/sonic_lab_links.csv
	CREATING SONIC LAB DEVICES: files/sonic_lab_devices.csv
	CREATING TEST BED: testbed.csv
	CREATING VM_HOST/CREDS: group_vars/vm_host/creds.yml
	CREATING EOS/CREDS: group_vars/eos/creds.yml
	CREATING FANOUT/SECRETS: group_vars/fanout/secrets.yml
	CREATING LAB SECRETS: group_vars/lab/secrets.yml
	CREATING MAIN.YML: group_vars/vm_host/main.yml
	CREATING LAB FILE: lab
Traceback (most recent call last):
  File "TestbedProcessing.py", line 693, in <module>
    main()
  File "TestbedProcessing.py", line 681, in main
    makeLab(device_groups, devices, testbed, args.basedir + lab_file)  # Generate lab (LAB)
  File "TestbedProcessing.py", line 461, in makeLab
    if num_asic is not None:
NameError: global name 'num_asic' is not defined

Section in the script:

                        if card_type != 'supervisor':
                           entry += "\tstart_switchid=" + str( start_switchid )
                           if num_asic is not None:
                              start_switchid += int( num_asic )
                           else:
                              start_switchid += 1

Changing it to num_asics fixes this issue.

**Comment by abdosi** [comment]
should not be their anymore.
