### ISSUE TITLE
Add test case to verify ECN marking 

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-mgmt#4122]
**Description**

We need to add test case to verify ECN marking behavior on BRCM chipsets. We have IXIA based test cases but not enabled as of today. We should enable them for all BRCM chipsets. Also, we should add non ixia based test to make sure functionality works as expected.

**Steps to reproduce the issue:**
1. Bring up SONIC box (ECN marking should be enabled by default)
2. Send traffic from port A to B while B is congested.
3. Packets received out of B should have ECN marking

**Describe the results you received:**
Packets are not ECN marked.

**Describe the results you expected:**
Packet should be ECN marked.

**Additional information you deem important:**

    **Output of `show version`:**
It should be for all chipsets TD2/TD3, TH/TH2/TH3.
    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by developfast** [comment]
This testgap was covered in this PR - https://github.com/sonic-net/sonic-mgmt/pull/10265
