### ISSUE TITLE
Warm-boot CPA traffic handling

### ISSUE THREAD

**Issue by abdosi** [sonic-net/sonic-mgmt#4284]
Issue#

During CPA time-window following traffic consideration can be added to existing test case 

- Traffic coming from uplink (VxLAN Traffic)  should be decapsulated and L2 forwarded and not flooded if MAC is Learnt. Some of SAI implementaion it gets flooded even though Downstream MAC is known

- All the Uplink Path should have VxLAN encapsulated traffic. This to make sure traffic from all uplink can be forwarded.

- Mirroring of AR Traffic should happen in complete duration from CPA Installation and then removal. Current SONiC there is small window post-warmboot here Traffic is not mirror even though CPA is not removed yet.

**Comment by jcaiMR** [comment]
Test case 1 – non broadcast ARP Reply 

Test objective 

Verify ARP Reply for known mac is not broadcast to server during warm-reboot 

 

Test steps 

Server (PTF) enable GARP service, ARP entry learnt on tor 

Trigger Warm-Reboot, PTF send ARP Request from Port Ethernet-A 

Verify ARP Reply received only on Ethernet-A (non-broadcast) 

Clear ARP Entry, PTF send ARP Request from Port Ethernet-A 

Verify ARP Reply received on multi-interfaces 

Check if Warm-Reboot timeout, and finish test case post check 

 

Test case 2 – ARP Request to ferret server 

Test objective 

Verify during Warm-Reboot, ARP Request from server send to ferret 

 

Test steps 

Server (PTF) enable GARP service, check ARP entry learnt on interface 

Trigger Warm-Reboot 

Start new thread and in this thread let PTF periodically send ARP Request from Port Ethernet-A, check send counter X.  

Wait and show everflow ACL counter 

Verify X matches everflow acl counter increase, verify ARP Reply received from Ethernet-A 

Check if Warm-Reboot timeout, and finish test case post check (join new thread ...) 

 

 

Test Case 3 – ARP Reply from ferret server During Warm-Reboot 

Test objective 

Verify during Warm-Reboot, ARP Reply all comes from ferret server and in vxlan encap  

 

Test steps 

Server (PTF) enable GARP service, check ARP entry learnt on interface 

Clear related interface counters, vxlan counter, Everflow ACL counters 

Trigger Warm-Reboot, PTF send ARP Request from Port Ethernet-A, check send counter X 

Show everflow ACL counter match send counter X, PTF received ARP Reply from Ethernet-A and counter matches X (refer to Note) 

Verify vxlan packets counter matches X (refer to Note) 

Check if Warm-Reboot timeout, and finish test case post check 

Note: It's hard to determine when warm-reboot starts, so counter send counter X may always large than everflow ACL and VXLAN counters, to simplify the test case, we can just monitor the increase value of acl and vxlan counters)
