### ISSUE TITLE
New test: DHCP RELAY T0/M0 dhcp packet behavior

### ISSUE THREAD

**Issue by kellyyeh** [sonic-net/sonic-mgmt#4621]
**Description**

Need to test for dhcp_relay packet lifting behavior on T0/M0. 
Check if dhcp packets on T0/M0 is lifted and forwarded when there are two layers of dhcp relay

* For layer 3 DHCP COPP, only Broadcast and/or IP2ME should be lifted.

**Comment by StormLiangMS** [comment]
@kellyyeh  I see this issue is closed, do we have a PR?
