### ISSUE TITLE
[Dualtor] IPv6 test coverage for dual tor cases

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-mgmt#4687]
**Description**

Current dualtor test cases for orchagent is covering only the IPv4 packet flow. This was the planned phase 1 delivery which is completed. As the next step, we need IPv6 traffic coverage

**Steps to reproduce the issue:**
Enable IPv6 for the following cases:

1. https://github.com/Azure/sonic-mgmt/blob/master/tests/dualtor/test_orchagent_active_tor_downstream.py
2. https://github.com/Azure/sonic-mgmt/blob/master/tests/dualtor/test_orchagent_standby_tor_downstream.py
3. https://github.com/Azure/sonic-mgmt/blob/master/tests/dualtor/test_orchagent_slb.py

For this, the test must create IPv6 neighbor on both standby and active and send regular IPv6 traffic. For tunneled traffic, the expected packet would be IPv6 over IPv4. 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by StormLiangMS** [comment]
confirmed with Longxiang, this one is done.
