### ISSUE TITLE
[Test gap] Verify CPU Q and rate limiting for trapped packets

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-mgmt#4691]
**Description**

In one of the dualtor scenario, observed that packets that were trapped to CPU was on a high priority que on which there was no rate-limiting. This resulted in overloading kernel and device became unresponsive to critical commands like "changing mux state"

Need a test to check on what queues are being used in trapping and ensure rate limiting is applied. 

For e.g in the problem case, ~100k packets/sec got trapped to CPU. Whereas Sonic has rate limiting on Queue 1 and 4 but not on Queue 4. 

```
show c cpu
MC_PERQ_PKT(1).cpu0	    :		263,138,968		 +1,239 	    258/s
MC_PERQ_PKT(4).cpu0	    :		  9,310,202		    +58 	     10/s
MC_PERQ_PKT(7).cpu0	    :		259,029,881	       +440,113 	 84,029/s

show c cpu
TDBGC3_64.cpu0		    :		    254,717		 +9,421
MC_PERQ_PKT(1).cpu0	    :		263,137,729		+79,148 	    259/s
MC_PERQ_PKT(4).cpu0	    :		  9,310,144		 +3,549 	     11/s
MC_PERQ_PKT(7).cpu0	    :		258,589,768	    +28,963,633 	 97,576/s

```

Reference CSP - CS00012218081

**Steps to reproduce the issue:**
Need a test to check on trapped Q and/or the rate limiting for the following cases:

1. IP2ME packets (Regular ICMP)
2. Neighbor Miss (IPv4 and IPv6)
3. IPinIP encapsulated packet (v4inv4 and v6inv4) and neighbor miss after decap

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

```
SONiC.20201231.31
HwSKU: Arista-7050CX3
ASIC: broadcom
 ```

**Comment by StormLiangMS** [comment]
@prsunny could you help to clarify the result we are expecting for this one?

**Comment by yxieca** [comment]
@prsunny can you clarify this statement? " Whereas Sonic has rate limiting on Queue 1 and 4 but not on Queue 4."

**Comment by StormLiangMS** [comment]
hi @prsunny this one seems a dataplane related test gap, assigned to you for further triage.
