### ISSUE TITLE
Time taken by Peer link going down  when SONiC is issued cold reboot (/bin/reboot)

### ISSUE THREAD

**Issue by abdosi** [sonic-net/sonic-mgmt#4894]
Currently there is no platform test that verify whether the Peer detects Link down (Eg: Links on fanout switch) immediately when /bin/reboot is given on SONiC device.  Even if the links are not down immediately atleast test case should publish how much time it took peer to detect link down.

This is important because if peer do not detect link down immediately it can cause traffic blackhole when the SONiC device for example go for unplanned reboot.

**Comment by rlhui** [comment]
@wenyiz2021 , would you please start on this for chassis first? Thanks.

**Comment by wenyiz2021** [comment]
closing as PR merged
