### ISSUE TITLE
[chassis-packet] route/test_route_perf.py::test_perf_add_remove_routes test failed on multi-asic

### ISSUE THREAD

**Issue by anamehra** [sonic-net/sonic-mgmt#4916]
**Description**
route/test_route_perf.py::test_perf_add_remove_routes test case failed on multi-asic chassis-packet due to missing '-n <namesoace>' option during 'config interface' CLI

On multi asic setup, config interface needs to provide '-n <namespace>' option which is missing in this test causing the CLI to fail. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

Failure logs:
20/12/2021 20:05:13 base._run                                L0063 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#97: [sfd-t2-lc2] AnsibleModule::shell, args=["sudo config interface ip add PortChannel1054 2000::1/64"], kwargs={}
20/12/2021 20:05:14 base._run                                L0082 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#97: [sfd-t2-lc2] AnsibleModule::shell Result => {"stderr_lines": ["Usage: config interface [OPTIONS] COMMAND [ARGS]...", "Try \"config interface -h\" for help.", "", "Error: Missing option \"-n\" / \"--namespace\".  Choose from:", "\tasic0,", "\tasic1."], "cmd": "sudo config interface ip add PortChannel1054 2000::1/64", "end": "2021-07-28 15:32:23.175633", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 2, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": true, "strip_empty_ends": true, "_raw_params": "sudo config interface ip add PortChannel1054 2000::1/64", "removes": null, "argv": null, "creates": null, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "failed": true, "stderr": "Usage: config interface [OPTIONS] COMMAND [ARGS]...\nTry \"config interface -h\" for help.\n\nError: Missing option \"-n\" / \"--namespace\".  Choose from:\n\tasic0,\n\tasic1.", "delta": "0:00:00.576120", "msg": "non-zero return code", "stdout_lines": [], "start": "2021-07-28 15:32:22.599513", "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}
20/12/2021 20:05:14 base._run                                L0063 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#97: [sfd-t2-lc2] AnsibleModule::shell, args=["sudo ip neigh del 2000::2 dev PortChannel1054"], kwargs={}
20/12/2021 20:05:14 base._run                                L0082 DEBUG  | /data/tests/common/devices/multi_asic.py::_run_on_asics#97: [sfd-t2-lc2] AnsibleModule::shell Result => {"stderr_lines": ["Cannot find device \"PortChannel1054\""], "cmd": "sudo ip neigh del 2000::2 dev PortChannel1054", "end": "2021-07-28 15:32:23.662616", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": true, "strip_empty_ends": true, "_raw_params": "sudo ip neigh del 2000::2 dev PortChannel1054", "removes": null, "argv": null, "creates": null, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "failed": true, "stderr": "Cannot find device \"PortChannel1054\"", "delta": "0:00:00.017467", "msg": "non-zero return code", "stdout_lines": [], "start": "2021-07-28 15:32:23.645149", "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}
20/12/2021 20:05:14 __init__.pytest_runtest_call             L0039 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/tests/route/test_route_perf.py", line 250, in test_perf_add_remove_routes
    cleanup_dut(duthost, intf_neighs)
  File "/data/tests/route/test_route_perf.py", line 82, in cleanup_dut
    duthost.shell('sudo ip neigh del {} dev {}'.format(intf_neigh['neighbor'], intf_neigh['interface']))
  File "/data/tests/common/devices/multi_asic.py", line 97, in _run_on_asics
    return getattr(self.sonichost, self.multi_asic_attr)(*module_args, **complex_args)
  File "/data/tests/common/devices/base.py", line 89, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by anamehra** [comment]
Hi @abdosi ,  FYI

**Comment by abdosi** [comment]
cc @SuvarnaMeenakshi

**Comment by abdosi** [comment]
@anamehra : can we close this ?

**Comment by anamehra** [comment]
I see the script using namspace now for multiasic. Closing this issue.
