### ISSUE TITLE
[dualtor]: Standby link down scenario with no neighbor info learned

### ISSUE THREAD

**Issue by theasianpianist** [sonic-net/sonic-mgmt#5017]
**Description**
There is a test gap for the following scenario on a dual ToR testbed:
1. For a given port, the the standby ToR link for that port goes down (the active ToR link remains up). No neighbor information is learned on the standby ToR for the port.
2. The T1 sends a packet destined for the given port to the standby ToR. Since there is no neighbor information learned for the neighbor, the packet is dropped.

**Comment by yxieca** [comment]
@theasianpianist  is this still issue? shouldn't packet be sent to the tunnel when neighbor is missing?

**Comment by theasianpianist** [comment]
Sorry missed this update. The image fix is in, but we still need a test case to cover it. This PR adds the test plan description: https://github.com/sonic-net/sonic-mgmt/pull/7711

**Comment by StormLiangMS** [comment]
hi @prsunny this one seems a dataplane related test gap, assigned to you for further triage.
