### ISSUE TITLE
[Bgp] Test coverage for Bgp commands

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-mgmt#5069]
**Description**

Based on issue, https://github.com/Azure/sonic-buildimage/issues/7935, it is required to have test coverage for commonly used bgp commands as below:

1. show ip bgp network

**Describe the results you expected:**
Command execution must pass on all platforms including multi-asics. 

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by oleksandrKovtunenko** [comment]
could I take a look at this ?  thanks

**Comment by wangxin** [comment]
@oleksandrKovtunenko Sure, assigned this to you. Looking forward to your PR.

**Comment by StormLiangMS** [comment]
hi @Gfrom2016 could you help with this test gap?

**Comment by StormLiangMS** [comment]
hi @oleksandrKovtunenko let us know if you have PR ready for this one? I'd like to avoid duplicate work.

**Comment by ZhaohuiS** [comment]
close this issue since https://github.com/sonic-net/sonic-mgmt/pull/14656 got merged
