### ISSUE TITLE
[chassis][supervisor] Add tests to test processes/container in supervisor

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5078]
**Description**

Add tests to test containers in supervisor. Existing tests can be modified to run on supervisor.

container_checker/test_container_checker.py
memory_checker/test_memory_checker.py
monit/test_monit_status.py

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rlhui** [comment]
@do we need this?
