### ISSUE TITLE
Hitting Keyerror for test_lag_2.py for chassis-packet systems.

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#5080]
**Description**

Hitting keyerror while running test_lag_2.py for chassis-packet systems. @abdosi,kindly take a look.

_____________________ test_lag[unknown|unknown-single_lag] _____________________

common_setup_teardown = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
duthosts = [<MultiAsicSonicHost> sfd-t2-lc0]
tbinfo = {'auto_recover': 'True', 'comment': 'Tests SFD T2', 'conf-name': 'sfd-t2', 'duts': ['sfd-t2-lc0', 'sfd-t2-lc1', 'sfd-t2-lc2', 'sfd-t2-sup'], ...}
nbrhosts = {'ARISTA01T1': {'host': <tests.common.devices.eos.EosHost object at 0x7fe3d8b9ae90>, 'conf': ..., 'leaf'], 'bp_interfa...ct at 0x7fe3d3e47ed0>, 'conf': ...n', 'core'], 'bp_interface': {'ipv4': '10.10.246.3/24', 'ipv6': 'fc0a::6/64'}}}, ...}
fanouthosts = {'nexus-root': { os: 'nxos', hostname: 'nexus-root', device_type: 'FanoutLeaf' }}
conn_graph_facts = {'device_conn': {'sfd-t2-lc0': {'Ethernet0': {'peerdevice': u'nexus-root', 'peerport': u'Ethernet1/1', 'speed': u'1000...d-t2-lc0': {'CardType': u'Linecard', 'HwSku': u'8800-LC-48H-O', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
enum_dut_portchannel = 'unknown|unknown', testcase = 'single_lag'

    @pytest.mark.parametrize("testcase", ["single_lag",
                                          "lacp_rate",
                                          "fallback"])
    def test_lag(common_setup_teardown, duthosts, tbinfo, nbrhosts, fanouthosts, conn_graph_facts, enum_dut_portchannel, testcase):
        # We can't run single_lag test on vtestbed since there is no leaffanout
        if testcase == "single_lag" and is_vtestbed(duthosts[0]):
            pytest.skip("Skip single_lag test on vtestbed")

        ptfhost = common_setup_teardown

        dut_name, dut_lag = decode_dut_port_name(enum_dut_portchannel)

        some_test_ran = False
        for duthost in duthosts:
            if dut_name in [ 'unknown', duthost.hostname ]:
                lag_facts = duthost.lag_facts(host = duthost.hostname)['ansible_facts']['lag_facts']

                test_instance = LagTest(duthost, tbinfo, ptfhost, nbrhosts, fanouthosts, conn_graph_facts)

                # Test for each lag
                if dut_lag == "unknown":
                    test_lags = lag_facts['names']
                else:
                    pytest_require(dut_lag in lag_facts['names'], "No lag {} configuration found in {}".format(dut_lag, duthost.hostname))
                    test_lags = [ dut_lag ]

                for lag_name in test_lags:
                    if testcase in [ "single_lag",  "lacp_rate" ]:
                        try:
                            lag_facts['lags'][lag_name]['po_config']['runner']['min_ports']
                        except KeyError:
                            msg = "Skip {} for lag {} due to min_ports not exists".format(testcase, lag_name)
                            pytest_require(lag_name == "unknown", msg)
                            logger.info(msg)
                            continue
                        else:
                            some_test_ran = True
                            if testcase == "single_lag":
>                               test_instance.run_single_lag_test(lag_name, lag_facts)

common_setup_teardown = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
conn_graph_facts = {'device_conn': {'sfd-t2-lc0': {'Ethernet0': {'peerdevice': u'nexus-root', 'peerport': u'Ethernet1/1', 'speed': u'1000...d-t2-lc0': {'CardType': u'Linecard', 'HwSku': u'8800-LC-48H-O', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
dut_lag    = 'unknown'
dut_name   = 'unknown'
duthost    = <MultiAsicSonicHost> sfd-t2-lc0
duthosts   = [<MultiAsicSonicHost> sfd-t2-lc0]
enum_dut_portchannel = 'unknown|unknown'
fanouthosts = {'nexus-root': { os: 'nxos', hostname: 'nexus-root', device_type: 'FanoutLeaf' }}
lag_facts  = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}
lag_name   = 'PortChannel1010'
nbrhosts   = {'ARISTA01T1': {'host': <tests.common.devices.eos.EosHost object at 0x7fe3d8b9ae90>, 'conf': ..., 'leaf'], 'bp_interfa...ct at 0x7fe3d3e47ed0>, 'conf': ...n', 'core'], 'bp_interface': {'ipv4': '10.10.246.3/24', 'ipv6': 'fc0a::6/64'}}}, ...}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
some_test_ran = True
tbinfo     = {'auto_recover': 'True', 'comment': 'Tests SFD T2', 'conf-name': 'sfd-t2', 'duts': ['sfd-t2-lc0', 'sfd-t2-lc1', 'sfd-t2-lc2', 'sfd-t2-sup'], ...}
test_instance = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d3979190>
test_lags  = {'PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}
testcase   = 'single_lag'

pc/test_lag_2.py:299:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d3979190>
lag_name = 'PortChannel1010'
lag_facts = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}

    def run_single_lag_test(self, lag_name, lag_facts):
        logger.info("Start checking single lag for: %s" % lag_name)

        intf, _ = self.__get_lag_intf_info(lag_facts, lag_name)

        # Figure out fanout switches info if exists for the lag member and run minlink test
        if intf in self.fanout_neighbors.keys():
            peer_device   = self.fanout_neighbors[intf]['peerdevice']
            neighbor_intf = self.fanout_neighbors[intf]['peerport']
            self.__verify_lag_minlink(self.fanouthosts[peer_device], lag_name, lag_facts, neighbor_intf, deselect_time=5)

        # Figure out remote VM and interface info for the lag member and run minlink test
>       peer_device   = self.vm_neighbors[intf]['name']
E       KeyError: u'Ethernet8'

_          = {'Ethernet8': {'lacp_key': 0, 'link_watch': {'name': u'ethtool'}}, 'Ethernet9': {'lacp_key': 0, 'link_watch': {'name': u'ethtool'}}}
intf       = 'Ethernet8'
lag_facts  = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}
lag_name   = 'PortChannel1010'
neighbor_intf = u'Ethernet1/9'
peer_device = u'nexus-root'
self       = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d3979190>

pc/test_lag_2.py:205: KeyError
_____________________ test_lag[unknown|unknown-lacp_rate] ______________________

common_setup_teardown = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
duthosts = [<MultiAsicSonicHost> sfd-t2-lc0]
tbinfo = {'auto_recover': 'True', 'comment': 'Tests SFD T2', 'conf-name': 'sfd-t2', 'duts': ['sfd-t2-lc0', 'sfd-t2-lc1', 'sfd-t2-lc2', 'sfd-t2-sup'], ...}
nbrhosts = {'ARISTA01T1': {'host': <tests.common.devices.eos.EosHost object at 0x7fe3d8b9ae90>, 'conf': ..., 'leaf'], 'bp_interfa...ct at 0x7fe3d3e47ed0>, 'conf': ...n', 'core'], 'bp_interface': {'ipv4': '10.10.246.3/24', 'ipv6': 'fc0a::6/64'}}}, ...}
fanouthosts = {'nexus-root': { os: 'nxos', hostname: 'nexus-root', device_type: 'FanoutLeaf' }}
conn_graph_facts = {'device_conn': {'sfd-t2-lc0': {'Ethernet0': {'peerdevice': u'nexus-root', 'peerport': u'Ethernet1/1', 'speed': u'1000...d-t2-lc0': {'CardType': u'Linecard', 'HwSku': u'8800-LC-48H-O', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
enum_dut_portchannel = 'unknown|unknown', testcase = 'lacp_rate'

    @pytest.mark.parametrize("testcase", ["single_lag",
                                          "lacp_rate",
                                          "fallback"])
    def test_lag(common_setup_teardown, duthosts, tbinfo, nbrhosts, fanouthosts, conn_graph_facts, enum_dut_portchannel, testcase):
        # We can't run single_lag test on vtestbed since there is no leaffanout
        if testcase == "single_lag" and is_vtestbed(duthosts[0]):
            pytest.skip("Skip single_lag test on vtestbed")

        ptfhost = common_setup_teardown

        dut_name, dut_lag = decode_dut_port_name(enum_dut_portchannel)

        some_test_ran = False
        for duthost in duthosts:
            if dut_name in [ 'unknown', duthost.hostname ]:
                lag_facts = duthost.lag_facts(host = duthost.hostname)['ansible_facts']['lag_facts']

                test_instance = LagTest(duthost, tbinfo, ptfhost, nbrhosts, fanouthosts, conn_graph_facts)

                # Test for each lag
                if dut_lag == "unknown":
                    test_lags = lag_facts['names']
                else:
                    pytest_require(dut_lag in lag_facts['names'], "No lag {} configuration found in {}".format(dut_lag, duthost.hostname))
                    test_lags = [ dut_lag ]

                for lag_name in test_lags:
                    if testcase in [ "single_lag",  "lacp_rate" ]:
                        try:
                            lag_facts['lags'][lag_name]['po_config']['runner']['min_ports']
                        except KeyError:
                            msg = "Skip {} for lag {} due to min_ports not exists".format(testcase, lag_name)
                            pytest_require(lag_name == "unknown", msg)
                            logger.info(msg)
                            continue
                        else:
                            some_test_ran = True
                            if testcase == "single_lag":
                                test_instance.run_single_lag_test(lag_name, lag_facts)
                            else:
>                               test_instance.run_single_lag_lacp_rate_test(lag_name, lag_facts)

common_setup_teardown = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
conn_graph_facts = {'device_conn': {'sfd-t2-lc0': {'Ethernet0': {'peerdevice': u'nexus-root', 'peerport': u'Ethernet1/1', 'speed': u'1000...d-t2-lc0': {'CardType': u'Linecard', 'HwSku': u'8800-LC-48H-O', 'HwSkuType': u'predefined', 'Type': u'DevSonic'}}, ...}
dut_lag    = 'unknown'
dut_name   = 'unknown'
duthost    = <MultiAsicSonicHost> sfd-t2-lc0
duthosts   = [<MultiAsicSonicHost> sfd-t2-lc0]
enum_dut_portchannel = 'unknown|unknown'
fanouthosts = {'nexus-root': { os: 'nxos', hostname: 'nexus-root', device_type: 'FanoutLeaf' }}
lag_facts  = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}
lag_name   = 'PortChannel1010'
nbrhosts   = {'ARISTA01T1': {'host': <tests.common.devices.eos.EosHost object at 0x7fe3d8b9ae90>, 'conf': ..., 'leaf'], 'bp_interfa...ct at 0x7fe3d3e47ed0>, 'conf': ...n', 'core'], 'bp_interface': {'ipv4': '10.10.246.3/24', 'ipv6': 'fc0a::6/64'}}}, ...}
ptfhost    = <tests.common.devices.ptf.PTFHost object at 0x7fe3d8da5750>
some_test_ran = True
tbinfo     = {'auto_recover': 'True', 'comment': 'Tests SFD T2', 'conf-name': 'sfd-t2', 'duts': ['sfd-t2-lc0', 'sfd-t2-lc1', 'sfd-t2-lc2', 'sfd-t2-sup'], ...}
test_instance = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d8e0f820>
test_lags  = {'PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}
testcase   = 'lacp_rate'

pc/test_lag_2.py:301:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d8e0f820>
lag_name = 'PortChannel1010'
lag_facts = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}

    def run_single_lag_lacp_rate_test(self, lag_name, lag_facts):
        logger.info("Start checking single lag lacp rate for: %s" % lag_name)

        intf, po_interfaces = self.__get_lag_intf_info(lag_facts, lag_name)
>       peer_device         = self.vm_neighbors[intf]['name']
E       KeyError: u'Ethernet8'

intf       = 'Ethernet8'
lag_facts  = {'lags': {'PortChannel1010': {'po_config': {'device': u'PortChannel1010', 'hwaddr': u'f8:6b:d9:78:5e:1a', 'ports': {'E...PortChannel1010': u'asic0', 'PortChannel1012': u'asic0', 'PortChannel1016': u'asic1', 'PortChannel102': u'asic0', ...}}
lag_name   = 'PortChannel1010'
po_interfaces = {'Ethernet8': {'lacp_key': 0, 'link_watch': {'name': u'ethtool'}}, 'Ethernet9': {'lacp_key': 0, 'link_watch': {'name': u'ethtool'}}}
self       = <tests.pc.test_lag_2.LagTest instance at 0x7fe3d8e0f820>

pc/test_lag_2.py:151: KeyError
-- generated xml file: /data/tests/logs/pc/test_lag_2_2022-02-07-18-49-05.xml --
INFO:root:Can not get Allure report URL. Please check logs
---------------------------- live log sessionfinish ----------------------------
18:51:00 __init__.pytest_terminal_summary         L0064 INFO   | Can not get Allure report URL. Please check logs
=========================== short test summary info ============================
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skip fallback for lag PortChannel1010 due to fallback was not set for it
FAILED pc/test_lag_2.py::test_lag[unknown|unknown-single_lag] - KeyError: u'E...
FAILED pc/test_lag_2.py::test_lag[unknown|unknown-lacp_rate] - KeyError: u'Et...
==================== 2 failed, 1 skipped in 114.06 seconds =====================

**Comment by vperumal** [comment]
FYI @abdosi 

The test fails because it is looking for Ethernet10 while vm_neighbors are populated as Ethx/x/x. 
 
> /data/tests/pc/test_lag_2.py(206)run_single_lag_test()
-> peer_device   = self.vm_neighbors[intf]['name']
(Pdb) self.vm_neighbors
{u'Eth2/1/20': {u'namespace': u'', u'name': u'ARISTA53T1', u'port': u'Ethernet1'}, u'Eth2/0/21': {u'namespace': u'', u'name': u'ARISTA54T1', u'port': u'Ethernet1'}, u'Eth2/1/25': {u'namespace': u'', u'name': u'ARISTA58T1', u'port': u'Ethernet1'}, u'Eth2/1/23': {u'namespace': u'', u'name': u'ARISTA56T1', u'port': u'Ethernet1'}, u'Eth2/1/22': {u'namespace': u'', u'name': u'ARISTA55T1', u'port': u'Ethernet1'}, u'Eth2/0/27': {u'namespace': u'', u'name': u'ARISTA60T1', u'port': u'Ethernet1'}, u'Eth2/1/29': {u'namespace': u'', u'name': u'ARISTA62T1', u'port': u'Ethernet1'}, u'Eth2/1/28': {u'namespace': u'', u'name': u'ARISTA61T1', u'port': u'Ethernet1'}, u'Eth2/0/9': {u'namespace': u'', u'name': u'ARISTA41T1', u'port': u'Ethernet2'}, u'Eth2/0/8': {u'namespace': u'', u'name': u'ARISTA41T1', u'port': u'Ethernet1'}, u'Eth2/1/19': {u'namespace': u'', u'name': u'ARISTA52T1', u'port': u'Ethernet1'}, u'Eth2/1/13': {u'namespace': u'', u'name': u'ARISTA47T1', u'port': u'Ethernet1'}, u'Eth2/0/1': {u'namespace': u'', u'name': u'ARISTA33T1', u'port': u'Ethernet2'}, u'Eth2/0/0': {u'namespace': u'', u'name': u'ARISTA33T1', u'port': u'Ethernet1'}, u'Eth2/0/3': {u'namespace': u'', u'name': u'ARISTA35T1', u'port': u'Ethernet2'}, u'Eth2/0/2': {u'namespace': u'', u'name': u'ARISTA35T1', u'port': u'Ethernet1'}, u'Eth2/0/5': {u'namespace': u'', u'name': u'ARISTA37T1', u'port': u'Ethernet2'}, u'Eth2/0/4': {u'namespace': u'', u'name': u'ARISTA37T1', u'port': u'Ethernet1'}, u'Eth2/0/7': {u'namespace': u'', u'name': u'ARISTA39T1', u'port': u'Ethernet2'}, u'Eth2/0/6': {u'namespace': u'', u'name': u'ARISTA39T1', u'port': u'Ethernet1'}, u'Eth2/1/31': {u'namespace': u'', u'name': u'ARISTA64T1', u'port': u'Ethernet1'}, u'Eth2/0/18': {u'namespace': u'', u'name': u'ARISTA51T1', u'port': u'Ethernet1'}, u'Eth2/1/16': {u'namespace': u'', u'name': u'ARISTA50T1', u'port': u'Ethernet1'}, u'Eth2/1/17': {u'namespace': u'', u'name': u'ARISTA50T1', u'port': u'Ethernet2'}, u'Eth2/1/14': {u'namespace': u'', u'name': u'ARISTA47T1', u'port': u'Ethernet2'}, u'Eth2/0/11': {u'namespace': u'', u'name': u'ARISTA43T1', u'port': u'Ethernet2'}, u'Eth2/0/10': {u'namespace': u'', u'name': u'ARISTA43T1', u'port': u'Ethernet1'}, u'Eth2/0/12': {u'namespace': u'', u'name': u'ARISTA45T1', u'port': u'Ethernet1'}, u'Eth2/0/15': {u'namespace': u'', u'name': u'ARISTA49T1', u'port': u'Ethernet1'}, u'Eth2/0/30': {u'namespace': u'', u'name': u'ARISTA63T1', u'port': u'Ethernet1'}, u'Eth2/1/26': {u'namespace': u'', u'name': u'ARISTA59T1', u'port': u'Ethernet1'}, u'Eth2/0/24': {u'namespace': u'', u'name': u'ARISTA57T1', u'port': u'Ethernet1'}}
(Pdb) intf
u'Ethernet10'

**Comment by abdosi** [comment]
Passing.
