### ISSUE TITLE
[chassis][fabric][VoQ] Add tests to test fabric ports on chassis

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5081]
**Description**

On a VoQ chassis fabric port information can be obtained from CLI on supervisor card. ASICs between line cards are connected to each other via the fabric ports. 
Example test cases:
* Fabric port counters
* Link connectivity/reachability  
* Link recovery in case of errors 
* VoQ queue counters (should it be part of supervisor or line card?)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by vmittal-msft** [comment]
fabric port test plan under review - 
https://github.com/Azure/sonic-mgmt/pull/4305

**Comment by rlhui** [comment]
@kenneth-arista

**Comment by kenneth-arista** [comment]
Also see this PR: https://github.com/sonic-net/sonic-mgmt/pull/6620/

**Comment by wenyiz2021** [comment]
closing as tests added
