### ISSUE TITLE
[chassis][console-port] Test line card console port connection

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5084]
**Description**

Test console connection to the line cards.

Example tests:
https://github.com/Azure/sonic-mgmt/tree/master/tests/console

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by arlakshm** [comment]
@YatishSVC

**Comment by rlhui** [comment]
PR is merged.
