### ISSUE TITLE
[chassis][reboot] Chassis reboot tests for supervisor and line cards from supervisor module.

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5085]
**Description**

Add reboot tests to reboot line cards and supervisor from supervisor module.
example reboot test:
https://github.com/Azure/sonic-mgmt/blob/master/tests/common/reboot.py

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rlhui** [comment]
Three categories: power cycle, software reboot (incl. rebooting the kernel), config reload.
Check/update https://github.com/mprabhu-nokia/SONiC/blob/3e857476ccc2c1b7b172bc94bc439a6e7e63f2f5/doc/pmon/pmon-chassis-design.md

**Comment by arlakshm** [comment]
The software reboot is already implemented https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_reboot.py. 

PDU poweroff is implemented in this test https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_power_off_reboot.py

Kernal panic is implemented in this test https://github.com/sonic-net/sonic-mgmt/blob/master/tests/platform_tests/test_memory_exhaustion.py

**Comment by wenyiz2021** [comment]
mark done as testcase added
