### ISSUE TITLE
[chassis][QoS] Add QoS test cases to cover traffic across line cards.

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5086]
**Description**

Current QoS tests [ https://github.com/Azure/sonic-mgmt/blob/master/tests/qos/test_qos_sai.py ] run on each line card separately. Add selected test cases from 'test_qos_sai' to run for ports across line cards. 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by arlakshm** [comment]
Testcases added to cover inter LC traffic for Qos tests
