### ISSUE TITLE
[chassis][Everflow] Add test coverage for inter-LC mirroring

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#5095]
**Description**

Current Everflow tests don't provide test coverage for chassis. Add new tests (or extend existing tests) to provide test coverage for chassis, e.g., inter-LC mirroring. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rlhui** [comment]
@ysmanman is taking this up

**Comment by rlhui** [comment]
@ysmanman , you have an update on this? Thanks.

**Comment by ysmanman** [comment]
The test gap was already fixed in https://github.com/sonic-net/sonic-mgmt/pull/6945
