### ISSUE TITLE
[multi asic][pytest fails] Fix test BGP update timer

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5118]
**Description**
pytest bgp/  --testbed=vmsvc1-t1-nmasic-acs-1 --inventory=../ansible/strsvc,../ansible/veos  --testbed_file=../ansible/testbed.csv --host-pattern=svcstr-nmasic-acs-1  --module-path=../ansible/library  -s -k test_bgp_update_timer

        if (res.is_failed or 'exception' in res) and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
E           RunAnsibleModuleFail: run module shell failed, Ansible Results =>
E           {
E               "changed": true,
E               "cmd": "vtysh -c 'show version'",
E               "delta": "0:00:00.266590",
E               "end": "2022-02-01 18:19:22.020968",
E               "failed": true,
E               "invocation": {
E                   "module_args": {
E                       "_raw_params": "vtysh -c 'show version'",
E                       "_uses_shell": true,
E                       "argv": null,
E                       "chdir": null,
E                       "creates": null,
E                       "executable": null,
E                       "removes": null,
E                       "stdin": null,
E                       "stdin_add_newline": true,
E                       "strip_empty_ends": true,
E                       "warn": true
E                   }
E               },
E               "msg": "non-zero return code",
E               "rc": 1,
E               "start": "2022-02-01 18:19:21.754378",
E               "stderr": "Usage: /usr/bin/vtysh -n [0 to 5] [OPTION]... ",
E               "stderr_lines": [
E                   "Usage: /usr/bin/vtysh -n [0 to 5] [OPTION]... "
E               ],
E               "stdout": "",
E               "stdout_lines": []
E           }

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wenyiz2021** [comment]
test_bgp_update_timer is not supporting multi-asic commands yet. Working on fix

**Comment by wenyiz2021** [comment]
close as PR merged
