### ISSUE TITLE
show_techsupport/test_techsupport.py script fails on chassis-packet system due to missing bfd commands

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#5139]
**Description**

show_techsupport/test_techsupport.py script fails on chassis-packet system due to missing bfd commands.

FYI @abdosi 

duthosts = [<MultiAsicSonicHost> sfd-t2-lc0, <MultiAsicSonicHost> sfd-t2-lc1, <MultiAsicSonicHost> sfd-t2-lc2, <MultiAsicSonicHost> sfd-t2-sup]
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-t2-lc0'
commands_to_check = {'bfd_cmds': ["vtysh  -n  0 -c 'show bfd peers'", "vtysh  -n  1 -c 'show bfd peers'", "vtysh  -n  0 -c 'show bfd peers... ['/proc/buddyinfo', '/proc/cmdl
ine', '/proc/consoles', '/proc/cpuinfo', '/proc/devices', '/proc/diskstats', ...], ...}

    def test_techsupport_commands(
        duthosts, enum_rand_one_per_hwsku_frontend_hostname, commands_to_check
    ):
        """
        This test checks list of commands that will be run when executing
        'show techsupport' CLI against a standard expected list of commands
        to run.

        The test invokes show techsupport with noop option, which just
        returns the list of commands that will be run when collecting
        tech support data.

        Args:
        commands_to_check: contains a dict of command groups with each
        group containing a list of related commands.
        """

        cmd_not_found = defaultdict(list)
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]

        stdout = duthost.shell(
            'sudo generate_dump -n | grep -v "^mkdir\|^rm\|^tar\|^gzip"'
        )

        pytest_assert(stdout['rc'] == 0, 'generate_dump command failed')

        cmd_list = stdout["stdout_lines"]

        for cmd_group_name, cmd_group_to_check in commands_to_check.items():
            cmd_not_found.update(
                check_cmds(cmd_group_name, cmd_group_to_check, cmd_list)
            )

>       pytest_assert(len(cmd_not_found) == 0, cmd_not_found)
E       Failed: defaultdict(<type 'list'>, {'docker_cmds': ['docker exec syncd0 saidump', 'docker exec syncd1 saidump', 'docker exec lldp0 lldpcli show statistics', 'docker exec lldp1 lldpcli show statistics']})

cmd_group_name = 'bfd_cmds'
cmd_group_to_check = ["vtysh  -n  0 -c 'show bfd peers'", "vtysh  -n  1 -c 'show bfd peers'", "vtysh  -n  0 -c 'show bfd peers counters'", ...1 -c 'show bfd peers counters'"
, "vtysh  -n  0 -c 'show bfd peers json'", "vtysh  -n  1 -c 'show bfd peers json'", ...]
cmd_list   = [u'ln -s /usr/local/bin/generate_dump /var/dump/sonic_dump_sfd-t2-lc0_20210722_002728', u'echo cp  -r /proc/buddyinfo ...d-t2-lc0_20210722_002728/proc', u'echo
cp  -r /proc/devices /var/dump/sonic_dump_sfd-t2-lc0_20210722_002728/proc', ...]
cmd_not_found = defaultdict(<type 'list'>, {'docker_cmds': ['docker exec syncd0 saidump', 'doc... lldp0 lldpcli show statistics', 'docker exec lldp1 lldpcli show statistics'
]})
commands_to_check = {'bfd_cmds': ["vtysh  -n  0 -c 'show bfd peers'", "vtysh  -n  1 -c 'show bfd peers'", "vtysh  -n  0 -c 'show bfd peers... ['/proc/buddyinfo', '/proc/cmdl
ine', '/proc/consoles', '/proc/cpuinfo', '/proc/devices', '/proc/diskstats', ...], ...}
duthost    = <MultiAsicSonicHost> sfd-t2-lc0
duthosts   = [<MultiAsicSonicHost> sfd-t2-lc0, <MultiAsicSonicHost> sfd-t2-lc1, <MultiAsicSonicHost> sfd-t2-lc2, <MultiAsicSonicHost> sfd-t2-sup]
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-t2-lc0'
stdout     = {'stderr_lines': [u'find: \u2018/var/dump/sonic_dump_sfd-t2-lc0_20210722_00272...'become_method', and 'become_user' rather than running sudo"], 'failed': False}

show_techsupport/test_techsupport.py:457: Failed

**Comment by abdosi** [comment]
@vperumal is this still exist ?

**Comment by abdosi** [comment]
this issue is not seen,
