### ISSUE TITLE
[qos][traditional buffer test][MASIC] Add support for qos/test_buffer_traditional.py on multi ASIC platform

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5144]
**Description**

Add support for qos/test_buffer_traditional.py on multi ASIC platform

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by neethajohn** [comment]
Closing this one. PRs merged to 202012, 202205 and master
https://github.com/sonic-net/sonic-mgmt/pull/8194
https://github.com/sonic-net/sonic-mgmt/pull/8062
https://github.com/sonic-net/sonic-mgmt/pull/8195
