### ISSUE TITLE
[Multi ASIC][VxLAN][ECMP] Add test support for multi ASIC

### ISSUE THREAD

**Issue by smaheshm** [sonic-net/sonic-mgmt#5226]
**Description**

VxLAN ECMP tests are failing on multi ASIC platform. Currently tests are skiipped
https://github.com/Azure/sonic-mgmt/pull/5225

Code needs modification to run on multi ASIC platform.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment]
This is very old ask and vxlan ecmp is not a usecase for multiasic. Closing this
