### ISSUE TITLE
Add PFCWD test to verify storm detection on multiple ports 

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-mgmt#5239]
**Description**
Add new test case to verify PFCWD storm detection on multiple ports at same time

**Steps to reproduce the issue:**
1. Send continuous PFC frames to a port/priority to cause it to trigger PFCWD storm
2. Send continuous PFC frames to another port/priority to cause it to trigger PFCWD storm 
3.

**Describe the results you received:**
2nd port wasn't seeing PFCWD storm event.

**Describe the results you expected:**
2nd port should have received PFCWD storm.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@vmittal-msft what is the platform this issue observed on? is this a general issue for SONiC or a platform specific issue?

**Comment by vmittal-msft** [comment]
@yxieca I observed this issue on TH3 based HWSKUs. Not sure if this can happen on other SKUs but good to have this test in any case since it is not covered today.
