### ISSUE TITLE
[chassis-packet]: arp/test_neighbor_mac_noptf.py fails for LC with more than 2 asic.

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#5299]
**Description**

The script is failing for LC which has more than 2 asic. The test passes for two asic and fails for the third with Keyerror. 

@abdosi  FYI

==================================== ERRORS ====================================
_ ERROR at setup of TestNeighborMacNoPtf.testNeighborMacNoPtf[4-sfd-vt2-lc0-1] _

self = <tests.arp.test_neighbor_mac_noptf.TestNeighborMacNoPtf instance at 0x7fb9e74f4230>
duthosts = [<MultiAsicSonicHost sfd-vt2-lc0>, <MultiAsicSonicHost sfd-vt2-lc1>, <MultiAsicSonicHost sfd-vt2-lc2>, <MultiAsicSonicHost sfd-vt2-sup>]
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-vt2-lc0'
enum_frontend_asic_index = 1, routedInterfaces = {2: 'Ethernet26'}
ipVersion = 4, verifyOrchagentPresence = None

    @pytest.fixture(autouse=True)
    def updateNeighborIp(self, duthosts, enum_rand_one_per_hwsku_frontend_hostname, enum_frontend_asic_index, routedInterfaces, ipVersion, verifyOrchagentPresence):
        """
            Update Neighbor/Interface IP

            Prepares the DUT for testing by adding IP to the test interface, add and update
            the neighbor MAC 2 times.

            Args:
                duthost (AnsibleHost): Device Under Test (DUT)
                routedInterface (Fixture<str>): test Interface name
                ipVersion (Fixture<int>): IP version
                verifyOrchagentPresence (Fixture): Make sure orchagent is running before and
                    after update takes place

            Returns:
                None
        """
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        asichost = duthost.asic_instance(enum_frontend_asic_index)
>       routedInterface = routedInterfaces[asichost.asic_index]
E       KeyError: 1

asichost   = <SonicAsic 1>
duthost    = <MultiAsicSonicHost sfd-vt2-lc0>
duthosts   = [<MultiAsicSonicHost sfd-vt2-lc0>, <MultiAsicSonicHost sfd-vt2-lc1>, <MultiAsicSonicHost sfd-vt2-lc2>, <MultiAsicSonicHost sfd-vt2-sup>]
enum_frontend_asic_index = 1
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-vt2-lc0'
ipVersion  = 4
routedInterfaces = {2: 'Ethernet26'}
self       = <tests.arp.test_neighbor_mac_noptf.TestNeighborMacNoPtf instance at 0x7fb9e74f4230>
verifyOrchagentPresence = None

arp/test_neighbor_mac_noptf.py:213: KeyError

=========================== short test summary info ============================
ERROR arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-sfd-vt2-lc0-1]
ERROR arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-sfd-vt2-lc0-1]
PASSED arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-sfd-vt2-lc0-0]
PASSED arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-sfd-vt2-lc0-0]
PASSED arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[4-sfd-vt2-lc0-2]
PASSED arp/test_neighbor_mac_noptf.py::TestNeighborMacNoPtf::testNeighborMacNoPtf[6-sfd-vt2-lc0-2]
===================== 4 passed, 2 error in 1025.00 seconds =====================

**Comment by abdosi** [comment]
passing now
