### ISSUE TITLE
Need new test: verify the console's baud rate is 9600

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#5399]
**Description**

This baud rate needs to be set from bios/onie and be consistent all the way up to SONiC

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Blueve** [comment]
Let's make this testcase scalable. I think we will not use 9600 forever, after all it is 21 century already. Define a new test parameter for expected baud rate, and we can use 9600 as default.
