### ISSUE TITLE
test_acl.py currently fails on T2 profile because it is unable to determine upstream and downstream ports

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#5524]
**Description**

test_acl.py currently fails on T2 profile because it is unable to determine upstream and downstream ports. Because the upstream and downstream ports are empty, the test fails while trying to create acl table due to  "Error: -p option requires an argument" 

DEBUG:root:/data/tests/acl/test_acl.py::create_or_remove_acl_table#317: [sfd-t2-lc0] AnsibleModule::command Result => {"stderr_lines": ["Error: -p option requires an argume
nt"], "cmd": ["config", "acl", "add", "table", "DATA_INGRESS_IPV4_TEST", "L3", "-s", "ingress", "-p"], "end": "2022-03-20 21:36:31.035719", "_ansible_no_log": false, "stdou
t": "", "changed": true, "rc": 2, "failed": true, "stderr": "Error: -p option requires an argument", "delta": "0:00:00.465011", "invocation": {"module_args": {"creates": nu
ll, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "config acl add table DATA_INGRESS_IPV4_TEST L3 -s ingress -p ", "removes": null, "ar
gv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "start": "2022-03-20 21:36:30.570708", "msg": "non-zero return code"
}

{'acl_table_ports': defaultdict(<type 'list'>, {}),
 'destination_mac': {'downlink->uplink': {}, 'uplink->downlink': {}},
 'downstream_port_ids': [],
 'topo': 't2',
 'upstream_port_ids': [],
 'vlan_mac': None,
 'vlan_ports': []}
20:34:18 test_acl.setup                           L0209 INFO   | Gathered variables for ACL test:
{'acl_table_ports': defaultdict(<type 'list'>, {}),
 'destination_mac': {'downlink->uplink': {}, 'uplink->downlink': {}},
 'downstream_port_ids': [],
 'topo': 't2',
 'upstream_port_ids': [],
 'vlan_mac': None,
 'vlan_ports': []}
INFO:test_acl:Creating temporary folder "acl_test_dir" for ACL test

@abdosi : Kindly take a look.

**Comment by vperumal** [comment]
Adding the code to get upstream and downstream ports is straightforward but we hit three other issues :
 

- The test is run on a single DUT, so even though the code is put in to handle random DUT. The first issue is hit when it picks up supervisor node as the DUT. The test will fail for supervisor node. <-- We can skip supervisor node as DUT
- In case of T2 topology, all LC0 neighbors are T3 neighbors and all LC1 and LC2 are T1 neighbors, so since testcase is run on single DUT, you will either get upstream ports or downstream ports. <-- This one is a trickier issue, since the test is designed for single LC/single DUT having both upstream/downstream ports in single DUT. 
- The test also doesn't take into consideration about multi-asic support

**Comment by sanmalho-git** [comment]
One other thing I noticed is that in setup fixture acl_table_ports is populated based on the expectation that all upstream ports to the portchannels. In a T2 topology, if we assume that LC0 neighbors to T3 are upstream ports, then we have a mix of both PortChannels and ports.

**Comment by abdosi** [comment]
Passing now.
