### ISSUE TITLE
Sanity error while accessing result list in multi-asic vs testbed

### ISSUE THREAD

**Issue by SuvarnaMeenakshi** [sonic-net/sonic-mgmt#5525]
**Description**

**Steps to reproduce the issue:**
1. Run multi-asic vs with sanity test in azure pipeline, was not able to reproduce this locally.

**Describe the results you received:**
Sanity test failing : TypeError: list indices must be integers, not str

**Describe the results you expected:**
sanity test should not see the TypeError.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by SuvarnaMeenakshi** [comment]
@wangxin fyi

**Comment by wenyiz2021** [comment]
Issue being multi-asic vs taking more time than a multi-asic physical switch, multi-asic vs always take 7min ~ 10min to run check_interface_status task, while the timeout set is 600sec(10min):
data as follows:

1. multi-asic vs with 4 asics:
a good run takes ~7min:
12/08/2022 00:13:34 checks._check_interfaces_on_dut          L0130 INFO   | Done checking interfaces status on vlab-08
12/08/2022 00:13:34 parallel.on_terminate                    L0081 INFO   | process _check_interfaces_on_dut--<MultiAsicSonicHost vlab-08> terminated with exit code None
12/08/2022 00:13:34 parallel.parallel_run                    L0149 DEBUG  | task completed 1, running 0
12/08/2022 00:13:34 parallel.parallel_run                    L0204 INFO   | Completed running processes for target "_check_interfaces_on_dut" in **0:07:16.457277 seconds**

on a run that timeout, it is wrapping on the last asic but reached timeout 10min:
12/08/2022 17:50:44 base._run                                L0063 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_ip_interface#150: [vlab-08] AnsibleModule::show_ip_interface, args=[], kwargs={"namespace": "asic3"}
12/08/2022 17:51:53 base._run                                L0082 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_ip_interface#150: [vlab-08] AnsibleModule::show_ip_interface Result => {"invocation": {"module_args": {"namespace": "asic3"}}, "failed": false, "changed": false, "_ansible_no_log": false, "ansible_facts": {"ip_interfaces": {"Loopback4096": {"bgp_neighbor": "N/A", "ipv4": "8.0.0.3", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "32"}, "docker0": {"bgp_neighbor": "N/A", "ipv4": "240.127.1.1", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "24"}, "Loopback0": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.32", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "32"}, "PortChannel49": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.2", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "31"}, "PortChannel50": {"bgp_neighbor": "N/A", "ipv4": "10.1.0.6", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "31"}, "lo": {"bgp_neighbor": "N/A", "ipv4": "127.0.0.1", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "8"}, "eth0": {"bgp_neighbor": "N/A", "ipv4": "240.127.1.2", "peer_ipv4": "N/A", "admin": "up", "oper_state": "up", "prefix_len": "24"}}}}
12/08/2022 17:51:53 base._run                                L0063 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_interface#137: [vlab-08] AnsibleModule::show_interface, args=[], kwargs={"include_internal_intfs": true, "namespace": "asic3", "command": "status"}
12/08/2022 17:52:46 parallel.parallel_run                    L0149 DEBUG  | task completed 0, running 1
12/08/2022 17:52:46 parallel.parallel_run                    L0153 DEBUG  | all processes have timedout
12/08/2022 17:52:46 parallel.force_terminate                 L0090 INFO   | Found processes still running: [<SonicProcess(_check_interfaces_on_dut--<MultiAsicSonicHost vlab-08>, started)>]. Try to kill them.
12/08/2022 17:52:46 parallel.parallel_run                    L0204 INFO   | Completed running processes for target "_check_interfaces_on_dut" in **0:10:00.009412 seconds**
12/08/2022 17:52:46 __init__.do_checks                       L0097 DEBUG  | check results of each item [[{'failed': True}]]

2. while a physical multi-asic switch, which has 6 asics is taking much shorter ~35sec:
30/07/2022 06:37:03 parallel.on_terminate                    L0081 INFO   | process _check_interfaces_on_dut--<MultiAsicSonicHost svcstr-masic-acs-1> terminated with exit code None
30/07/2022 06:37:03 parallel.parallel_run                    L0149 DEBUG  | task completed 1, running 0
30/07/2022 06:37:03 parallel.parallel_run                    L0204 INFO   | Completed running processes for target "_check_interfaces_on_dut" in **0:00:34.835056 seconds**

3. on single-asic vs, it is taking  ~7sec:
Completed running processes for target "_check_interfaces_on_dut" in 0:00:07.419399 seconds

4. on a single-asic physical switch, it is taking ~9sec:
INFO     tests.common.helpers.parallel:parallel.py:81 process _check_interfaces_on_dut--<MultiAsicSonicHost str2-7050cx3-acs-02> terminated with exit code None
DEBUG    tests.common.helpers.parallel:parallel.py:149 task completed 1, running 0
INFO     tests.common.helpers.parallel:parallel.py:204 Completed running processes for target "_check_interfaces_on_dut" in **0:00:09.179232 seconds**

point 2, 3, 4 is taking short time within a minute, but multi-asic vs is taking very long to verify 'show ip int' and 'show int status', to check if it is resource issue, or the timeout need to be increased.

**Comment by wenyiz2021** [comment]
This issue is resolved when increased vm size.
with new size each show_ip_int cmd per asic takes ~6sec
**16/08/2022 17:21:57** base._run                                L0063 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_ip_interface#150: [vlab-08] AnsibleModule::show_ip_interface, args=[], kwargs={"namespace": "asic0"}
**16/08/2022 17:22:03** base._run                                L0082 DEBUG  | /var/src/s/tests/common/devices/sonic_asic.py::show_ip_interface#150: [vlab-08] AnsibleModule::show_ip_interface Result => {"invocation": {"module_args": {"nam

total time taken is ~45sec:
 L0204 INFO   | Completed running processes for target "_check_interfaces_on_dut" in **0:00:45.574005** seconds
