### ISSUE TITLE
test_ebtables_application exits with an error due to missing 'import logging'

### ISSUE THREAD

**Issue by kartik-arista** [sonic-net/sonic-mgmt#6029]
**Description**

test_ebtables_application aborts due to an error in import logging

cacl/test_ebtables_application.py:4: in <module>
    logger = logging.getLogger(__name__)
E   NameError: name 'logging' is not defined

**Steps to reproduce the issue:**

Simply run the test.

@abdosi seems to have introduced this change in 

https://github.com/Azure/sonic-mgmt/pull/3169

**Comment by SuvarnaMeenakshi** [comment]
Error should no longer be seen.
https://github.com/sonic-net/sonic-mgmt/pull/6797 fixes this issue.
