### ISSUE TITLE
voq/test_voq_disrupts.py failed with TypeError

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#6034]
**Description**
voq/test_voq_disrupts.py failed with the following error:
TypeError: check_ip_fwd() takes exactly 4 arguments (3 given)

**Steps to reproduce the issue:**
Run the test with T2 topo.

**Describe the results you received:**
TypeError: check_ip_fwd() takes exactly 4 arguments (3 given)

**Describe the results you expected:**

**Additional information you deem important:**
PR https://github.com/Azure/sonic-mgmt/pull/4704 added one more argument to check_ip_fwd(), but the PR does not update the caller of check_ip_fwd().

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by sanmalho-git** [comment]
PR https://github.com/Azure/sonic-mgmt/pull/5173 address this issue.

**Comment by ysmanman** [comment]
Add @arlakshm for viz.

**Comment by arlakshm** [comment]
Fix commited in this PR https://github.com/sonic-net/sonic-mgmt/pull/6605
