### ISSUE TITLE
voq test helper pick_ports may pick up the same port twice.

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#6035]
**Description**
The issue was uncovered when triaging end-to-end neighbor ping failure seen in voq test. It is specific to multi-asic with T2 topo. Detailedly, when pick_ports(..., port_type_a="portchannel",...) selects portA & portB from an ASIC that only has portchannels,  it selects 2 portchannels, instead of 1 portchannel + 1 ethernet, by calling get_info_for_a_port() twice. https://github.com/Azure/sonic-mgmt/blob/857e83ef07a48af973fa458b268f6db67b0f1454/tests/voq/test_voq_ipfwd.py#L246-L257  get_info_for_a_port() randomly chooses portchannel by using random.choice().https://github.com/Azure/sonic-mgmt/blob/857e83ef07a48af973fa458b268f6db67b0f1454/tests/voq/test_voq_ipfwd.py#L140 So it's possible get_info_for_a_port() may choose the same portchannel twice.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by sanmalho-git** [comment]
Good catch - Tests were written with either [T2 min](https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t2_2lc_min_ports-masic.yml) topology or [T2,](https://github.com/Azure/sonic-mgmt/blob/master/ansible/vars/topo_t2_2lc_36p-masic.yml) for multi-asic so never caught this scenario.  

Quick solution would be remove the 'portA' interface from the 'pos' list before calling get_info_for_a_port at https://github.com/Azure/sonic-mgmt/blob/master/tests/voq/test_voq_ipfwd.py#L256

**Comment by ysmanman** [comment]
Add @arlakshm for viz.

**Comment by abdosi** [comment]
@ysmanman please check back. For T2/t2-min topology you should not see the issue.

**Comment by ysmanman** [comment]
> @ysmanman please check back. For T2/t2-min topology you should not see the issue.

Yeah, we haven't seen this issue anymore in our recent T2 testing.
