### ISSUE TITLE
bgp/test_bgp_gr_helper.py failed with KeyError: u'Ethernet-IB0'

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#6036]
**Description**
Encountered the following error when running bgp/test_bgp_gr_helper.py with T2 topo:

bgp/test_bgp_gr_helper.py:134: KeyError: u'Ethernet-IB0'

**Steps to reproduce the issue:**
Run bgp/test_bgp_gr_helper.py with T2 top.

**Describe the results you received:**
bgp/test_bgp_gr_helper.py:134: KeyError: u'Ethernet-IB0'

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
Test selects a neighbor from the nexthops of default route if default route is installed. https://github.com/Azure/sonic-mgmt/blob/857e83ef07a48af973fa458b268f6db67b0f1454/tests/bgp/test_bgp_gr_helper.py#L110-L125 In T2 topo, it's possible that the default route is learnt over iBgp, and thus the intf of nexthop may be inband port. Test failed with KeyError: u'Ethernet-IB0' if the inband port is selected. Test needs to be updated for T2 topo.

**Comment by ysmanman** [comment]
Add @arlakshm for viz.

**Comment by kenneth-arista** [comment]
This test is only applicable to T1  role

**Comment by arlakshm** [comment]
Fixed in this PR https://github.com/sonic-net/sonic-mgmt/pull/6206 to skip this test
