### ISSUE TITLE
Restarting radv causes swss service to restart

### ISSUE THREAD

**Issue by yxieca** [sonic-net/sonic-mgmt#6042]
**Description**

**Steps to reproduce the issue:**
1. Boot up sonic image and let it stablize
2. systemctl restart radv
3.

**Describe the results you received:**
swss also restarted while radv restarting

**Describe the results you expected:**
swss should not restart when dependent service restarted.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yozhao101** [comment]
@yxieca Ack.
