### ISSUE TITLE
Any test cases fails due to ImportError: No module named grpc

### ISSUE THREAD

**Issue by AndriiLozovyi** [sonic-net/sonic-mgmt#6048]
**Description**

It looks that changes presented in PR -  [6006](https://github.com/Azure/sonic-mgmt/pull/6006) are causing Import Error, which leads to fail of any test case. 

```
common/dualtor/nic_simulator_control.py:2: in <module>
    import grpc
   ImportError: No module named grpc
```

**Steps to reproduce the issue:**
1.  Deploy t0 topology 
2.  Deploy minigraph on DUT
3.  Run snmp/test_snmp_psu.py as an example

**Describe the results you received:**

Test case fails due **Import Error**
```
ImportError while loading conftest '/var/user/jenkins/sonic-mgmt/tests/conftest.py'.
conftest.py:28: in <module>
    from tests.common.fixtures.ptfhost_utils import ptf_portmap_file                # lgtm[py/unused-import]
common/fixtures/ptfhost_utils.py:15: in <module>
    from tests.common.dualtor.dual_tor_utils import increase_linkmgrd_probe_interval
common/dualtor/__init__.py:3: in <module>
    from tests.common.dualtor.nic_simulator_control import *
common/dualtor/nic_simulator_control.py:2: in <module>
    import grpc
   ImportError: No module named grpc
```

**Describe the results you expected:**
TC is running and no errors observed

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    SONiC Software Version: SONiC.master.126453-dirty-20220725.114044
    Distribution: Debian 11.4
    Kernel: 5.10.0-12-2-amd64
    Build commit: 78ad76954
    Build date: Mon Jul 25 16:59:19 UTC 2022
    Built by: AzDevOps@sonic-build-workers-001TX8
    Platform: x86_64-arista_7170_64c
    HwSKU: Arista-7170-64C
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by AndriiLozovyi** [comment]
@lolyu, @wangxin, @yxieca Could you please take a look ?

**Comment by lolyu** [comment]
Hi @AndriiLozovyi, could you use the latest `sonic-mgmt` image? It should be good with that.

**Comment by AndriiLozovyi** [comment]
@lolyu  
Thanks for the reply 
Using latest `sonic-mgmt` image helped
