### ISSUE TITLE
Show mux stat gives: could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE on virtual switch

### ISSUE THREAD

**Issue by Ndancejic** [sonic-net/sonic-mgmt#6162]
**Description**

**Steps to reproduce the issue:**
1.  `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k ceos add-topo vms-kvm-dual-t0 password.txt`
2.  `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb gen-mg vms-kvm-dual-t0 veos_vtb password.txt`
3. `./testbed-cli.sh -t vtestbed.yaml -m veos_vtb deploy-mg vms-kvm-dual-t0 veos_vtb password.txt`
4.  on vlab-05 or 06 run `show mux stat`

**Describe the results you received:**
```
admin@vlab-06:~$ show mux stat
could not retrieve key state value for port Ethernet4 inside table MUX_CABLE_TABLE
```
**Describe the results you expected:**

A list of mux cables and their current states

**Additional information you deem important:**

**Output of `show version`:**

    admin@vlab-06:~$ show version
    
    SONiC Software Version: SONiC.master.0-6f06fee2e
    Distribution: Debian 11.4
    Kernel: 5.10.0-12-2-amd64
    Build commit: 6f06fee2e
    Build date: Thu Aug 11 17:50:11 UTC 2022
    Built by: dancejic@dancejic-vm
    
    Platform: x86_64-kvm_x86_64-r0
    HwSKU: Force10-S6000
    ASIC: vs
    ASIC Count: 1
    Serial Number: N/A
    Model Number: N/A
    Hardware Revision: N/A
    Uptime: 02:34:32 up 17 min,  1 user,  load average: 0.45, 0.34, 0.30
    Date: Sat 13 Aug 2022 02:34:32
    
    Docker images:
    REPOSITORY                    TAG                  IMAGE ID       SIZE
    docker-macsec                 latest               00133a5ab81a   459MB
    docker-dhcp-relay             latest               c55ed06384a7   451MB
    docker-gbsyncd-vs             latest               a95fb57958e0   449MB
    docker-gbsyncd-vs             master.0-6f06fee2e   a95fb57958e0   449MB
    docker-sonic-telemetry        latest               ab771b20f226   522MB
    docker-sonic-telemetry        master.0-6f06fee2e   ab771b20f226   522MB
    docker-teamd                  latest               7a0873dbc3c8   456MB
    docker-teamd                  master.0-6f06fee2e   7a0873dbc3c8   456MB
    docker-router-advertiser      latest               971243300c0f   440MB
    docker-router-advertiser      master.0-6f06fee2e   971243300c0f   440MB
    docker-platform-monitor       latest               46b90d9d6e3e   563MB
    docker-platform-monitor       master.0-6f06fee2e   46b90d9d6e3e   563MB
    docker-orchagent              latest               76fc79dc3d38   475MB
    docker-orchagent              master.0-6f06fee2e   76fc79dc3d38   475MB
    docker-mux                    latest               d9992ff12bb5   489MB
    docker-mux                    master.0-6f06fee2e   d9992ff12bb5   489MB
    docker-lldp                   latest               89381f272347   483MB
    docker-lldp                   master.0-6f06fee2e   89381f272347   483MB
    docker-database               latest               f4fb850fd18f   440MB
    docker-database               master.0-6f06fee2e   f4fb850fd18f   440MB
    docker-syncd-vs               latest               8454f82a6f03   426MB
    docker-syncd-vs               master.0-6f06fee2e   8454f82a6f03   426MB
    docker-sonic-mgmt-framework   latest               f46d6f0ac2f7   558MB
    docker-sonic-mgmt-framework   master.0-6f06fee2e   f46d6f0ac2f7   558MB
    docker-snmp                   latest               f295e624920e   457MB
    docker-snmp                   master.0-6f06fee2e   f295e624920e   457MB
    docker-sflow                  latest               4f112a401daf   430MB
    docker-sflow                  master.0-6f06fee2e   4f112a401daf   430MB
    docker-nat                    latest               516ef6f475a5   432MB
    docker-nat                    master.0-6f06fee2e   516ef6f475a5   432MB
    docker-fpm-frr                latest               6b9d2b0eebb1   458MB
    docker-fpm-frr                master.0-6f06fee2e   6b9d2b0eebb1   458MB

**Attach debug file `sudo generate_dump`:**

    admin@vlab-06:~$ sudo generate_dump
    Lock succesfully accquired and installed signal handlers
    Traceback (most recent call last):
      File "/usr/local/bin/decode-syseeprom", line 18, in <module>
        import sonic_platform
    ModuleNotFoundError: No module named 'sonic_platform'
    No sensors found!
    Make sure you loaded all the kernel drivers you need.
    Try sensors-detect to find out which these are.
    can't get debug descriptor: Resource temporarily unavailable
    /usr/local/bin/generate_dump: line 520: $2: unbound variable
    ERR: RC:-1 observed on line 520
    conntrack v1.4.6 (conntrack-tools): 0 flow entries have been shown.
    conntrack v1.4.6 (conntrack-tools): 0 flow entries have been shown.
    conntrack v1.4.6 (conntrack-tools): 2033 flow entries have been shown.
    conntrack v1.4.6 (conntrack-tools): 2033 flow entries have been shown.
    bfdd is not running
    bfdd is not running
    bfdd is not running
    bfdd is not running
    rm: cannot remove '/var/dump/sonic_dump_vlab-06_20220813_023508/etc/xdg/systemd/user/sockets.target.wants/gpg-agent-extra.socket': No such file or directory
    rm: cannot remove '/var/dump/sonic_dump_vlab-06_20220813_023508/etc/xdg/systemd/user/sockets.target.wants/dirmngr.socket': No such file or directory
    rm: cannot remove '/var/dump/sonic_dump_vlab-06_20220813_023508/etc/xdg/systemd/user/sockets.target.wants/gpg-agent-ssh.socket': No such file or directory
    rm: cannot remove '/var/dump/sonic_dump_vlab-06_20220813_023508/etc/xdg/systemd/user/sockets.target.wants/gpg-agent-browser.socket': No such file or directory
    rm: cannot remove '/var/dump/sonic_dump_vlab-06_20220813_023508/etc/xdg/systemd/user/sockets.target.wants/gpg-agent.socket': No such file or directory
    ERR: RC:-1 observed on line 1422
    Remove secret from etc files.
    sed: can't read /var/dump/sonic_dump_vlab-06_20220813_023508/etc/pam_radius_auth.d/*.conf: No such file or directory
    Tar append operation failed. Aborting for safety.
    Cleaning up working directory /var/dump/sonic_dump_vlab-06_20220813_023508
    Removing lock. Exit: 0
    /var/dump/sonic_dump_vlab-06_20220813_023508.tar.gz

syslog:
![image](https://user-images.githubusercontent.com/26731235/184465338-8fa7849b-fbbc-4198-838d-b75496540e6e.png)

**Comment by upendarreddy98** [comment]
We do have the similar issue here in Arista devices, when we run show mux status,

user@AristDevice:~$ show mux status
**could not retrieve key state value for port Ethernet0 inside table MUX_CABLE_TABLE**

Please can you guide us to resolve this issue.
