### ISSUE TITLE
[chassis] - voq_ipfwd tests are getting skipped

### ISSUE THREAD

**Issue by sanmalho-git** [sonic-net/sonic-mgmt#6171]
**Description**
PR# https://github.com/sonic-net/sonic-mgmt/pull/5708/ introduced using conditional marks instead of pytest.skip in the test scripts.
However, with this PR that is causing all tests voq/test_voq_ipfwd.py to be skipped on T2 chassis.  The are failing with the reason
```
Did not find any asic in the DUTs (linecards) that are connected to T1 VM's
```

We see the following issues:

- mg_facts are loaded in [init.py ](https://github.com/sonic-net/sonic-mgmt/blob/master/tests/common/plugins/conditional_mark/__init__.py#L311) for the first DUT in the testbed.  If the first DUT is connected to T3 VM's, then the tests are going to skip, even though we have another linecard that has T1 VM's connected.
   - The original voq_ipfwdtest was checking minigraph_neighbors on all the linecards (DUTs) in the chassis.
- For a multi-asic card, VOQ_INBAND_INTERFACE and BGP_VOQ_CHASSIS_NEIGHBOR are defined in asic config db's and not in the global config_db.json. Thus, these fields are not populated correctly in the facts gathered in __init__.py in conditional mark - as the config facts are not taking into consideration all the asics.

**Steps to reproduce the issue:**
1. Run voq_ipfwd.py suite against a T2 chassis with multi-asic linecards and having the first DUT be the linecard that connects to only T3 VM's.
2.
3.

**Describe the results you received:**
Tests are getting skipped.

**Describe the results you expected:**
Tests should run and not get skipped.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rlhui** [comment]
@sanmalho-git - is this issue fixed with #5708 ? Please close the issue if so.

**Comment by sanmalho-git** [comment]
No - PR #5708 is what introduced this issue.

**Comment by rlhui** [comment]
@yutongzhang-microsoft - would you please check this issue?  Should https://github.com/sonic-net/sonic-mgmt/pull/5708 be reverted?

**Comment by arlakshm** [comment]
@yutongzhang-microsoft  @wangxin, To fix we need to change the https://github.com/sonic-net/sonic-mgmt/blob/1bb0a97d3d317e61fac805900ae71bb2a0b88e74/tests/common/plugins/conditional_mark/__init__.py#L305 to handle multi dut and multi asic devices. This might be big change and needs more testing.

To unblock testing on voq chassis I created PR #6952 to revert the changes in #5708  for voq tests

**Comment by abdosi** [comment]
We need to close this soon.
