### ISSUE TITLE
Validate the PFC counting function should work if the src MAC is all zero in the PFC frame

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#6172]
**Description**

Sending PFC traffic with src MAC all zero, validate the PFC rx counter should count for those frames and the dut is able to react to those pfc frames
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
there is another aspect of the problem, we need to also validate the tx pfc frame send by the asic and validate the packet format is valid, this is more difficult to validate since we need to capture the pfc frames send by the asic.

**Comment by developfast** [comment]
This will be validated using an ixia traffic generator
