### ISSUE TITLE
[azp stuck] with testmodule test_copp for 7050cx3 platform

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-mgmt#6194]
**Description**
When run az pipeline with test_copp modules, it would stuck till time out of pipeline runs against master branch images. 

**Steps to reproduce the issue:**
1. To trigger a azp nightly on 7050cx3 platform
2.
3.

**Describe the results you received:**
the azure pipeline would be timed out with test_copp test module.

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ZhaohuiS** [comment]
@StormLiangMS This issue is fixed in https://github.com/sonic-net/sonic-mgmt/pull/6199 from test case side.
And we have an original fix for bullseye base docker image in this PR https://github.com/sonic-net/sonic-buildimage/pull/11895
