### ISSUE TITLE
[snmp] Snmp value for cached memory is different from system_info 

### ISSUE THREAD

**Issue by AndriiLozovyi** [sonic-net/sonic-mgmt#6307]
**Description**
 **snmp/test_snmp_memory.py::test_snmp_memory**  gets failed with message below: 
 ```
> pytest.fail("Snmp memory MIBs: {} differs more than {} %".format(snmp_diff, percent))
E Failed: Snmp memory MIBs: ['ansible_sysCachedMemory'] differs more than 4 %
```

It looks that starting from sonic image `SONiC.master.137279-dirty-20220820.094848` something changed in output of snmp for CachedMemory, and now output of snmp and info from system have a difference about 6.7-7 %. On previous sonic image `SONiC.master.135201-dirty-20220815.112418` output of snmp for cached memory was in touch with system_info from DUT. 

**Steps to reproduce the issue:**
1. Deploy sonic image `SONiC.master.137279-dirty-20220820.094848`
2. Run cmd from sonic-mgmt `snmpwalk -v 2c -c public <DUT_IP> 1.3.6.1.4.1.2021.4.15.0`
3. Check cached memory value on device `cat /proc/meminfo | grep Cached`

**Describe the results you received:**
On `SONiC.master.137279-dirty-20220820.094848`:

```
iso.3.6.1.4.1.2021.4.15.0 = INTEGER: 1045492
Cached:           972064 kB

>>> CALC_DIFF = lambda snmp, sys_data: float(abs(snmp - int(sys_data)) * 100) / float(snmp)
>>> CALC_DIFF(1045492, 972064)
7.023296208866256
```

**Describe the results you expected:**
On `SONiC.master.135201-dirty-20220815.112418`:

```
iso.3.6.1.4.1.2021.4.15.0 = INTEGER: 965504
Cached:           965504 kB
>>> CALC_DIFF(965504, 965504)
0.0
```

**Additional information you deem important:**

    **Output of `show version`:**
```
SONiC Software Version: SONiC.master.137279-dirty-20220820.094848
Distribution: Debian 11.4
Kernel: 5.10.0-12-2-amd64
Build commit: 0f50835c1
Build date: Sat Aug 20 16:51:04 UTC 2022
Built by: AzDevOps@sonic-build-workers-001Y2N

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
Following 2 image changes might be the trigger of the change:

commit 9753f28d1798eb556ead1a26dea6c3a8dfc2a7e4
Author: Saikrishna Arcot <sarcot@microsoft.com>
Date:   Fri Aug 19 11:20:17 2022 -0700

    Upgrade snmp docker to Bullseye (#11741)
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

commit 5bb6d0deba7aa77bb4a28868125077118206ca53
Author: Saikrishna Arcot <sarcot@microsoft.com>
Date:   Fri Aug 19 11:20:00 2022 -0700

    [snmpd]: Update to 5.9+dfsg-4+deb11u1 to match Debian version (#11763)
    
    * [snmpd]: Update to 5.9+dfsg-4+deb11u1 to match Debian version
    
    This brings in some security fixes.
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
    
    * Update snmpd makefile
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
    
    * Remove binNMU for snmpd
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
    
    Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

**Comment by AndriiLozovyi** [comment]
If this change in output of snmp for cached memory is okay and acceptable, then the fix would probably be to increase the percentage, although not sure that 8% will be enough, because I spotted even higher difference. 

```
Cached:          2480620 kB
iso.3.6.1.4.1.2021.4.15.0 = INTEGER: 2800252
>>> CALC_DIFF(2800252, 2480620)
11.414401275313793
```

Strange that only snmp output for cached memory seems to have such difference between these two sonic images: 
`SONiC.master.135201-dirty-20220815.112418`
```
# sysTotalFreeMemory
>>> CALC_DIFF(12482868, 12483008)
0.001121537133934285

# sysTotalBuffMemory
>>> CALC_DIFF(43428, 43428)
0.0

# sysCachedMemory 
>>> CALC_DIFF(965504, 965504)
0.0

# sysTotalSharedMemory
>>> CALC_DIFF(24104, 24104)
0.0
```

`SONiC.master.137279-dirty-20220820.094848`
```
# sysTotalFreeMemory
>>> CALC_DIFF(12520324, 12520340)
0.00012779222007353803

# sysTotalBuffMemory
>>> CALC_DIFF(33048, 33048)
0.0 

# sysCachedMemory 
>>> CALC_DIFF(1045492, 972064)
7.023296208866256

# sysTotalSharedMemory
>>> CALC_DIFF(36896, 36896)
0.0 
```
