### ISSUE TITLE
T2 profile: test_snmp_interfaces fails for non-existent backplane interfaces.

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#6346]
**Description**

In case of T2 profile, test_snmp_interfaces fails for non-existent backplane interfaces. The testcase checks interfaces from port_name_to_alias_map in snmp_facts. Since port_name_to_alias_map contains all interfaces even the ones for the absent FCs, the test case fails for those non-existent backplane interfaces

    # Verify all physical ports in snmp interface list
    for _, alias in config_facts['port_name_to_alias_map'].items():
        assert alias in snmp_ifnames, "Interface not found in SNMP facts."

<testcase classname="snmp.test_snmp_interfaces" file="snmp/test_snmp_interfaces.py" line="137" name="test_snmp_interfaces[sfd-t2-sup-14]" time="393.628">
<properties>
<property name="start" value="2022-09-11 20:20:39.685272"/>
<property name="end" value="2022-09-11 20:27:13.324014"/>
</properties>
<failure message="AssertionError: Interface not found in SNMP facts.">localhost = <tests.common.devices.local.Localhost object at 0x7fd9f5e836d0>

**Comment by vperumal** [comment]
FYI @abdosi

**Comment by anamehra** [comment]
Hi @abdosi , this could be because on the Supervisor side, we have a topology for 8 FCs even though some FCs are missing. We could not remove the missing FCs from topology because of other issues we encountered with minigraph generation during the initial days.

**Comment by abdosi** [comment]
Passing now.
