### ISSUE TITLE
[test_fwutil]fixture 'fw_pkg_name' not found

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#6489]
**Description**
`platform_tests.fwutil.test_fwutil` failed due to not found fixture 'fw_pkg_name'

```
_________ ERROR at setup of test_fwutil_install_file[str-dx010-acs-4] __________
file /azp/agent/_work/70/s/tests/platform_tests/fwutil/test_fwutil.py, line 32
  def test_fwutil_install_file(duthost, localhost, pdu_controller, fw_pkg, random_component):
file /azp/agent/_work/70/s/tests/platform_tests/fwutil/conftest.py, line 28
  @pytest.fixture(scope='module')
  def fw_pkg(fw_pkg_name):
E       fixture 'fw_pkg_name' not found


/azp/agent/_work/70/s/tests/platform_tests/fwutil/conftest.py:28
__________ ERROR at setup of test_fwutil_install_url[str-dx010-acs-4] _________
```

**Steps to reproduce the issue:**
1. Run `platform_tests.fwutil.test_fwutil` 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by StormLiangMS** [comment]
@prgeor  could you have someone to take a look at this platform test case issue?

**Comment by prgeor** [comment]
@sujinmkang can you help triage this?

**Comment by sanmalho-git** [comment]
> specify the package with firmware.

@AndriiLozovyi - could you please provide details regarding 'package with firmware'.  For our DUT, we have a BIOS .cap file to change the BIOS. Is that what we would specify as the argument to '--fw_pkg'?

**Comment by AndriiLozovyi** [comment]
> > specify the package with firmware.
> 
> @AndriiLozovyi - could you please provide details regarding 'package with firmware'. For our DUT, we have a BIOS .cap file to change the BIOS. Is that what we would specify as the argument to '--fw_pkg'?

You can find more details about the package in fwutil doc - [custom-firmware-package](https://github.com/sonic-net/SONiC/blob/master/doc/fwutil/fwutil.md#22243-custom-firmware-package-option-with---fw-image)

**Comment by ZhaohuiS** [comment]
> > > specify the package with firmware.
> > 
> > 
> > @AndriiLozovyi - could you please provide details regarding 'package with firmware'. For our DUT, we have a BIOS .cap file to change the BIOS. Is that what we would specify as the argument to '--fw_pkg'?
> 
> You can find more details about the package in fwutil doc - [custom-firmware-package](https://github.com/sonic-net/SONiC/blob/master/doc/fwutil/fwutil.md#22243-custom-firmware-package-option-with---fw-image)

@AndriiLozovyi Sorry, still don't know which firmware package should add for --fw_pkg, could you please specific it much more?
