### ISSUE TITLE
[test-gap] lldp neighbors disappear when orchagnet restarted

### ISSUE THREAD

**Issue by ZhaohuiS** [sonic-net/sonic-mgmt#6560]
**Description**

There is a known issue for lldp https://github.com/lldpd/lldpd/pull/492.

**Steps to reproduce the issue:**
1. sudo config feature autorestart swss diable
2. docker exec swss supervisorctl status
3. docker exec swss kill -SIGKILL 111(orchagent)
4. docker inspect -f {{.State.Running}} swss => make sure swss is running
5. docker exec swss supervisorctl start orchagent

Or run `autorestart/test_container_autorestart.py`

It's been fixed in https://github.com/sonic-net/sonic-buildimage/pull/9519.
But there is test gap to cover this scenario.
1. restart orchagent
2. check if lldp neighbors are missing.

**Describe the results you received:**

lldp neighbors gone but bgp sessions are up, interfaces are up. Throw these warning log.

```
Oct 18 07:07:58.126844 str2-z9332f-01 INFO lldp#/supervisord: lldpd 2022-10-18T07:07:58 [WARN/lldp] unable to send packet on real device for Ethernet112: No such device or address
Oct 18 07:07:58.127528 str2-z9332f-01 INFO lldp#/supervisord: lldpd 2022-10-18T07:07:58 [WARN/lldp] unable to send packet on real device for Ethernet136: No such device or address
Oct 18 07:07:58.142229 str2-z9332f-01 WARNING lldp#lldpd[25]: unable to send packet on real device for Ethernet200: No such device or address
Oct 18 07:07:58.142578 str2-z9332f-01 INFO lldp#/supervisord: lldpd 2022-10-18T07:07:58 [WARN/lldp] unable to send packet on real device for Ethernet200: No such device or address
```

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by augusdn** [comment]
Assign to myself for 2024 Hackathon task
