### ISSUE TITLE
【sonic-mgmt T0 topology failed】Ptf unreachable

### ISSUE THREAD

**Issue by Wlyy0314** [sonic-net/sonic-mgmt#6570]
**Description**
Failed to execute this step
./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k ceos add-topo vms-kvm-t0 password.txt

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
error message：
TASK [vm_set : wait until ptf is reachable] *******************************************************
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_wait_for_payload_xL5I8h/__main__.py", line 599, in main
    s = _create_connection(host, port, min(connect_timeout, alt_connect_timeout))
  File "/tmp/ansible_wait_for_payload_xL5I8h/__main__.py", line 456, in _create_connection
    connect_socket = socket.create_connection((host, port), connect_timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err

fatal: [STR-ACS-VSERV-01 -> localhost]: FAILED! => {
    "changed": false, 
    "elapsed": 300, 
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED", 
                "FIN_WAIT1", 
                "FIN_WAIT2", 
                "SYN_RECV", 
                "SYN_SENT", 
                "TIME_WAIT"
            ], 
            "connect_timeout": 5, 
            "delay": 0, 
            "exclude_hosts": null, 
            "host": "10.250.0.102", 
            "msg": null, 
            "path": null, 
            "port": 22, 
            "search_regex": null, 
            "sleep": 1, 
            "state": "started", 
            "timeout": 300
        }
    }, 
    "msg": "Timeout when waiting for 10.250.0.102:22"
}
docker images
REPOSITORY                                            TAG           IMAGE ID       CREATED         SIZE
ceosimage                                             4.25.5.1M-1   bfad2007b40e   46 hours ago    2.01GB
docker-sonic-mgmt-wl                                  master        b28fbc5a83ae   2 days ago      4.29GB
sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt   latest        8afd508621bf   3 days ago      3.68GB
ceosimage                                             4.25.5.1M     dcfe63828133   5 days ago      2.01GB
sonicdev-microsoft.azurecr.io:443/docker-ptf          latest        b91d9bca6405   5 months ago    1.81GB
hello-world                                           latest        feb5d9fea6a5   13 months ago   13.3kB
debian                                                jessie        3aaeab7a4777   19 months ago   129MB

docker ps -a
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED        STATUS                  PORTS              NAMES
d53a277c76eb   sonicdev-microsoft.azurecr.io:443/docker-ptf          "/usr/local/bin/supe…"   22 hours ago   Up 22 hours             22/tcp, 8009/tcp   docker-ptf
cca3e6c425f6   sonicdev-microsoft.azurecr.io:443/docker-ptf          "/usr/local/bin/supe…"   24 hours ago   Up 24 hours             22/tcp, 8009/tcp   ptf
abae68bad4c9   debian:jessie                                         "bash"                   46 hours ago   Up 46 hours                                net_vms6-1_VM0102
f0cee1ced053   debian:jessie                                         "bash"                   46 hours ago   Up 46 hours                                net_vms6-1_VM0101
26c222bc5907   debian:jessie                                         "bash"                   46 hours ago   Up 46 hours                                net_vms6-1_VM0100
93e800057640   debian:jessie                                         "bash"                   46 hours ago   Up 46 hours                                net_vms6-1_VM0103
9ae260833443   sonicdev-microsoft.azurecr.io:443/docker-ptf:latest   "/usr/local/bin/supe…"   46 hours ago   Up 46 hours                                ptf_vms6-1
995c0b8e9406   docker-sonic-mgmt-wl:master                           "/bin/bash"              2 days ago     Up 2 days               22/tcp             sonic-mgmt
4b14c1f0ab8b   hello-world                                           "/hello"                 5 days ago     Exited (0) 5 days ago                      sleepy_rosalind

docker-ptf ip
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
488: eth0@if489: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever

**Describe the results you expected:**
ptf is reachable

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
@wangxin

**Comment by Wlyy0314** [comment]
It‘s ok!

**Comment by bigwboy** [comment]
I also encountered a similar problem, can you tell me how to solve it. Thanks ：）

**Comment by Wlyy0314** [comment]
sudo ./setup-management-network.sh
make sure you have br1
brctl show

**Comment by bigwboy** [comment]
Thanks~!:)
