### ISSUE TITLE
[test_vxlan_ecmp] doesn't work for 4600c platform

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-mgmt#6616]
**Description**
test_vxlan_ecmp doesn't work for 4600c platform, it will failed with sanity check for the vnetRouteCheck, below is the log.

E               Oct 20 23:00:43.360925 str2-msn4600c-acs-01 ERR monit[568]: 'vnetRouteCheck' status failed (1) -- (0, {'results': {}})
E               
E               Oct 20 23:05:43.460814 str2-msn4600c-acs-01 ERR monit[568]: 'vnetRouteCheck' status failed (1) -- (0, {'results': {}})

**Steps to reproduce the issue:**
1. To run the test_vxlan_ecmp
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by siqbal1986** [comment]
https://github.com/sonic-net/sonic-utilities/pull/2480 the PR fixes this problem.

**Comment by siqbal1986** [comment]
@StormLiangMS  can you please close this issue

**Comment by bingwang-ms** [comment]
Issue fixed.
