### ISSUE TITLE
Chassis  : Unable to download syncd-dnx-rpc docker image on LC. SUP is fine.

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-mgmt#6644]
**Description**

Unable to download syncd-dnx-rpc image from LC. Needed for QoS test suite.

**Steps to reproduce the issue:**
1. Trigger swapSyncd call by running any of qos tests
2. It will fail in logging to docker registry

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
![image](https://user-images.githubusercontent.com/46945843/198351926-3886acf4-222b-4e97-b809-7371714cc901.png)

**Comment by abdosi** [comment]
@vmittal-msft please check if we can close this now.

**Comment by vmittal-msft** [comment]
This is fine now.
