### ISSUE TITLE
ipfwd/test_mtu.py fails due to "AttributeError: 'SubRequest' object has no attribute 'param'"

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#6760]
**Description**

ipfwd/test_mtu.py fails due to "AttributeError: 'SubRequest' object has no attribute 'param'". This issue seems to have started after 
https://github.com/sonic-net/sonic-mgmt/pull/6084 - which was introduced on August 23. We see the test case last passing on August 15th.

@abdosi - are we supposed to add some variable in inventory file or pass something while running the nightly - Kindly let us know

________________ ERROR at setup of test_mtu[sfd-vt2-lc0-1-1514] ________________

request = <SubRequest 'enum_rand_one_frontend_asic_index' for <Function test_mtu[sfd-vt2-lc0-0-1514]>>

    @pytest.fixture(scope="module")
    def enum_rand_one_frontend_asic_index(request):
>       return request.param
E       AttributeError: 'SubRequest' object has no attribute 'param'

request    = <SubRequest 'enum_rand_one_frontend_asic_index' for <Function test_mtu[sfd-vt2-lc0-0-1514]>>

conftest.py:1364: AttributeError
________________ ERROR at setup of test_mtu[sfd-vt2-lc0-1-9114] ________________

request = <SubRequest 'enum_rand_one_frontend_asic_index' for <Function test_mtu[sfd-vt2-lc0-0-1514]>>

    @pytest.fixture(scope="module")
    def enum_rand_one_frontend_asic_index(request):
>       return request.param
E       AttributeError: 'SubRequest' object has no attribute 'param'

request    = <SubRequest 'enum_rand_one_frontend_asic_index' for <Function test_mtu[sfd-vt2-lc0-0-1514]>>

conftest.py:1364: AttributeError

**Comment by sanmalho-git** [comment]
This was fixed by https://github.com/sonic-net/sonic-mgmt/pull/6332. After having this PR merged, we don't see the above error

**Comment by vperumal** [comment]
@sanmalho-git and @abdosi - we still see this issue

**Comment by abdosi** [comment]
fixed is their.
