### ISSUE TITLE
T2 topology br-T2Inband not created when running veos_vtb with SONiC image

### ISSUE THREAD

**Issue by mrkcmo** [sonic-net/sonic-mgmt#6798]
We are trying to bring up the T2 topology in the veos_vtb using the SONiC image as the DUT and neighbors. The following error is displayed during the creation of the testbed:

TASK [vm_set : Bind topology t2-vs to VMs. base vm = VM0100] *******************************************************************************************************
Friday 11 November 2022  01:09:06 +0000 (0:00:00.049)       0:10:14.741 ******* 
fatal: [STR-ACS-VSERV-01]: FAILED! => {"changed": false, "msg": "ret_code=1, error message=\"ovs-vsctl: no bridge named br-T2Inband\n\". cmd=\"ovs-vsctl list-ports br-T2Inband\""}

We are able to bring up the T0 topology and run tests without issues so the images and testbed setup seems correct.

**Steps to reproduce the issue:**
1. ./testbed-cli.sh -t vtestbed.yaml -m veos_vtb -k vsonic add-topo vms-kvm-t2 password.txt
2.
3.

**Describe the results you received:**
The below error is noted and we are trying to backwards engineer where the issue is but would like to get support to speed along the resolution:

TASK [vm_set : Bind topology t2-vs to VMs. base vm = VM0100] *******************************************************************************************************
Friday 11 November 2022  01:09:06 +0000 (0:00:00.049)       0:10:14.741 ******* 
fatal: [STR-ACS-VSERV-01]: FAILED! => {"changed": false, "msg": "ret_code=1, error message=\"ovs-vsctl: no bridge named br-T2Inband\n\". cmd=\"ovs-vsctl list-ports br-T2Inband\""}

**Describe the results you expected:**
We expect that the T2 topology would come up and be accessible to run T2 tests.

**Additional information you deem important:**

Full output of command and output is attached.

[T2-Topo-first.log](https://github.com/sonic-net/sonic-mgmt/files/9985837/T2-Topo-first.log)

**Comment by rlhui** [comment]
@sanmalho-git wondering if you would be able to check this?  Thanks.

**Comment by mrkcmo** [comment]
> @sanmalho-git wondering if you would be able to check this? Thanks.

@sanmalho-git  I am happy to work with you on this to resolve the issue. Please let me know.

**Comment by sanmalho-git** [comment]
@mrkcmo  - could you please run the add-topo command with -vvv and attach the log for that. Also under the /tmp folder in the testbed server, there should be a file like "vm_topology_bind_vms_<timestamp>".  Could you grep "CMD:" from that file and attach as well. Example:

cat /tmp/vm_topology_bind_vms_11_2022-11-24T11\:59\:57.687713.log | grep "CMD:"

**Comment by mrkcmo** [comment]
> 

@sanmalho-git I am trying to run with the "-vvv" as you outlined above but I can't seem to make that option work. Can you provide the exact syntax you are looking for in this instance? Thanks in advance!

**Comment by mrkcmo** [comment]
[session.log](https://github.com/sonic-net/sonic-mgmt/files/10171884/session.log)
@sanmalho-git 
The session log for the testbed-cli command is attached. 

[session2.log](https://github.com/sonic-net/sonic-mgmt/files/10171909/session2.log)
The session2 log attached is the output of the grep for 'CMD:' as requested.

Please let me know if you need anything else. Thanks!

**Comment by sanmalho-git** [comment]
We would have to work on enhancing the add-topo to support vsonic for kvm based T2 topology.

**Comment by mrkcmo** [comment]
@sanmalho-git that was the ask from @rlhui  to see if that is possible and how quickly it could be done. Right now it is a major blocker for the community for T2 test development if they don't have a license to use or can't purchase one.

**Comment by Azarack** [comment]
When trying to bring up vms-kvm-t1-lag topology with either vsonic or veos neighbors I get the following similar error:
fatal: [STR-ACS-VSERV-01]: FAILED! => {"changed": false, "msg": "ret_code=1, error message=\"\". cmd=\"ifconfig -a | grep -E br-VM0127-[0-9]+\""}

**Comment by abdosi** [comment]
ceos and Virtual chassis is fine.  we need this for macsec testing with virtual chassis.

**Comment by Azarack** [comment]
> When trying to bring up vms-kvm-t1-lag topology with either vsonic or veos neighbors I get the following similar error: fatal: [STR-ACS-VSERV-01]: FAILED! => {"changed": false, "msg": "ret_code=1, error message="". cmd="ifconfig -a | grep -E br-VM0127-[0-9]+""}

I was able to get passed this error by running these commands on the host:
sudo ovs-vsctl --may-exist add-br br-T2Inband
sudo ovs-vsctl --may-exist add-br br-T2Midplane


I get a new set of errors though:
TASK [sonic : create topo config] **********************************************************************************************
Tuesday 23 May 2023  14:28:33 +0000 (0:00:42.915)       0:17:07.077 ***********
fatal: [VM0100]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: u\"hostvars['vlab-t2-01,vlab-t2-02,vlab-t2-sup']\" is undefined"}
fatal: [VM0101]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0102]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: u\"hostvars['vlab-t2-01,vlab-t2-02,vlab-t2-sup']\" is undefined"}
fatal: [VM0105]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0107]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0106]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: u\"hostvars['vlab-t2-01,vlab-t2-02,vlab-t2-sup']\" is undefined"}


This is for vsonic neighbors with the t2_2lc_min_ports-masic topology.

**Comment by mithun2498** [comment]
Hello @mrkcmo 

I tried to deploy T2 on a virtual setup and I was able to successfully complete add topology step using ceos image.
I am facing the following issue in deploying minigraph,

Error:
fatal: [vlab-t2-sup]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'syslog_servers' is undefined"
}
<10.250.0.120> ESTABLISH SSH CONNECTION FOR USER: admin
<10.250.0.120> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyC
hecking=no -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/bdec70cf60 10.250.0.120 '
/bin/sh -c '"'"'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1688638282.68-7818-40059235962417/ > /dev/null 2>&1 && sleep 0'"'"''
<10.250.0.120> (0, '', '')
fatal: [vlab-t2-01]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'syslog_servers' is undefined"
}
<10.250.0.121> ESTABLISH SSH CONNECTION FOR USER: admin
<10.250.0.121> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyC
hecking=no -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/859f14b87d 10.250.0.121 '
/bin/sh -c '"'"'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1688638282.71-7822-65563955282801/ > /dev/null 2>&1 && sleep 0'"'"''
<10.250.0.121> (0, '', '')
fatal: [vlab-t2-02]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'syslog_servers' is undefined"
}

Kindly help me on this!!

**Comment by mrkcmo** [comment]
You might try using the latest master image from the vSonic build page. We found an issue when using an image older than 6 months.  Issues with connectivity during ansible setup of the vSonic devices was consistent before using the lastest master. We currently run T2 virtual with vSonic meighbors with no issues and have also brought up T2 virtual with CEOS as well but once again used the latest CEOS image.

________________________________

**Comment by mrkcmo** [comment]
This issue was resolve via another PR request and ticket. I am closing this issue.

**Comment by cyw233** [comment]
Hey @mrkcmo, I ran into the same `"msg": "AnsibleUndefinedVariable: 'syslog_servers' is undefined"` issue as @mithun2498 when I was trying to deploy minigraph on T2 KVM. I created the PR https://github.com/sonic-net/sonic-mgmt/pull/12691 to fix it. Could you please have a review? Thanks
