### ISSUE TITLE
[test gap] Enhance the existing incremental ACL test

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#6801]
**Description**

The test is to verify dataplane ACL works as expected after excessive update.
The existing `TestIncrementalAcl` did some incremental test, but not enough to cover the real scenario in production.
https://github.com/sonic-net/sonic-mgmt/blob/8ba7efab4a8eb1565a79e5aeeb0b760330aca24f/tests/acl/test_acl.py#L1061

**Test steps**
1. Configure some ACL rule on the box. We call it original rules
2. Do multiple (say 1000 times) insertion/deletion on the testing ACL table.
3. Verify the original rules work as expected.
4. Add new ACL rules, and verify it works as expected.
5. Verify no crash happened.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by xwjiang-ms** [comment]
Add a testcase to send a template sh file to dut, run 1000 times add/delete acl, and check dut status
Details in PR: https://github.com/sonic-net/sonic-mgmt/pull/6903
