### ISSUE TITLE
Validate the queue watermark counter

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#6926]
**Description**

Need to add a new case to check the queue watermark counter of each interface works well.
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@kevinskwang can you clarify the difference of this gap and #6639?

**Comment by kevinskwang** [comment]
Duplicated with https://github.com/sonic-net/sonic-mgmt/issues/6639
