### ISSUE TITLE
CACL test_multiasic_cacl_application script for SUP check failing because of asic check with TCP/UDP/ICMP I-table rules

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#6936]
**Description**

In the CACL test_multiasic_cacl_application test, when the SUP test is run it is checking for specific icmp,udp,tcp entries in Iptables. These IP tables are configured by caclmgrd only when the interface/Ips are available in the ASIC.
But T2 we don’t have interfaces/Ips in ASIC0/1/2.
 
But the script is checking in SUP with asic_index 1 and failing
**Steps to reproduce the issue:**
1. Running cacl multi asic script for sup

**Describe the results you received:**
(Pdb) p expected_iptables_rules
['-P INPUT ACCEPT', '-P FORWARD ACCEPT', '-P OUTPUT ACCEPT', '-A INPUT -s 127.0.0.1/32 -i lo -j ACCEPT', '-A INPUT -s 240.127.1.7/32 -d 240.127.1.7/32 -j ACCEPT', '-A INPUT -s 240.127.1.1/32 -d 240.127.1.7/32 -j ACCEPT', '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT', '-A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT', '-A INPUT -p udp -m udp --dport 67:68 -j ACCEPT', '-A INPUT -p udp -m udp --dport 546:547 -j ACCEPT', '-A INPUT -p tcp -m tcp --dport 179 -j ACCEPT', '-A INPUT -d 1.72.0.0/32 -j DROP', '-A INPUT -m ttl --ttl-lt 2 -j ACCEPT']
(Pdb) p actual_iptables_rules
[u'-P INPUT ACCEPT', u'-P FORWARD ACCEPT', u'-P OUTPUT ACCEPT']
(Pdb)
 

DEBUG:root:/data/tests/common/devices/sonic_asic.py::command#384: [sfd-vt2-sup] AnsibleModule::command Result => {"stderr_lines": [], "cmd": ["sudo", "ip", "netns", "exec", "asic1", "iptables", "-S"], "end": "2022-11-30 18:33:09.549684", "_ansible_no_log": false, "stdout": "-P INPUT ACCEPT\n-P FORWARD ACCEPT\n-P OUTPUT ACCEPT", "changed": true, "rc": 0, "start": "2022-11-30 18:33:09.533690", "stderr": "", "delta": "0:00:00.015994", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "sudo ip netns exec asic1 iptables -S", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": ["-P INPUT ACCEPT", "-P FORWARD ACCEPT", "-P OUTPUT ACCEPT"], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"], "failed": false}
18:33:09 base._run                                L0082 DEBUG  | /data/tests/common/devices/sonic_asic.py::command#384: [sfd-vt2-sup] AnsibleModule::command Result => {"stderr_lines": [], "cmd": ["sudo", "ip", "netns", "exec", "asic1", "iptables", "-S"], "end": "2022-11-30 18:33:09.549684", "_ansible_no_log": false, "stdout": "-P INPUT ACCEPT\n-P FORWARD ACCEPT\n-P OUTPUT ACCEPT", "changed": true, "rc": 0, "start": "2022-11-30 18:33:09.533690", "stderr": "", "delta": "0:00:00.015994", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "sudo ip netns exec asic1 iptables -S", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": ["-P INPUT ACCEPT", "-P FORWARD ACCEPT", "-P OUTPUT ACCEPT"], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"], "failed": false}
INFO:raj:Number of expected iptable rules:16, number of acutal iptables rules:3
18:33:09 raj.verify_cacl                          L0748 INFO   | Number of expected iptable rules:16, number of acutal iptables rules:3

**Comment by rajendrat** [comment]
@SuvarnaMeenakshi @abdosi , Please have a look.

**Comment by abdosi** [comment]
@arlakshm

**Comment by abdosi** [comment]
@rajendrat please check back. It is passing for us as of now,

**Comment by rajendrat** [comment]
@abdosi . CACL tests are passing in our local run. Closing this issue.
