### ISSUE TITLE
ACL: acl/test_stress_acl.py is using hardcoded ports portchannels, which are not configured on switch 

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#7091]
**Description**

acl/test_stress_acl.py is using hardcoded ports, so the tests are failing in configure ACL table.

https://github.com/sonic-net/sonic-mgmt/blob/master/tests/acl/test_stress_acl.py

def test_acl_add_del_stress(duthosts, rand_one_dut_hostname, get_function_conpleteness_level):
    duthost = duthosts[rand_one_dut_hostname]
    generate_acl_rule(duthost, "ipv4")
    duthost.shell("config acl add table -p PortChannel101,PortChannel102,PortChannel103,PortChannel104 \
                  IP_STRESS_ACL L3")

**Steps to reproduce the issue:**
1. Running test_stress_acl.py test

**Describe the results you received:**
Failing to configure ACL table with the portchannel not configure on switch

**Describe the results you expected:**
Look up the configured portchannel from the config, and use it to configure.

**Comment by rajendrat** [comment]
@xwjiang-ms  @abdosi

**Comment by abdosi** [comment]
@rajendrat Can you please work on test pr for this as root cause in known ?

**Comment by rajendrat** [comment]
@abdosi. We have fix for this issue and verified locally. @vperumal will create a upstream PR.

**Comment by abdosi** [comment]
@wenyiz2021 for viz.

**Comment by rajendrat** [comment]
This issue is fixed part of https://github.com/sonic-net/sonic-mgmt/pull/7174 PR
