### ISSUE TITLE
[testbed] File `ansible/roles/fanout/templates/sonic_deploy.j2` seems useless

### ISSUE THREAD

**Issue by lizhijianrd** [sonic-net/sonic-mgmt#7221]
**Description**

SONiC fanout startup-config template file [ansible/roles/fanout/templates/sonic_deploy.j2](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/fanout/templates/sonic_deploy.j2) seems useless. I didn't find any codes in the repo using this file. 

Currently, deploy SONiC fanout is using following templates:

* For SONiC 202012 fanout: [ansible/roles/fanout/templates/sonic_deploy_202012.j2](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/fanout/templates/sonic_deploy_202012.j2)
* For SONiC 202205 fanout: [ansible/roles/fanout/templates/sonic_deploy_202205.j2](https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/roles/fanout/templates/sonic_deploy_202205.j2)

**Comment by lizhijianrd** [comment]
Hi @Blueve @wangxin @lolyu, can you help to confirm if I can delete this file?

**Comment by wangxin** [comment]
@lizhijianrd I think yes, this file can be deleted.
