### ISSUE TITLE
Test expected macsec to run on SKU that does not support macsec

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7222]
**Description**

Noticed the issue when run T2 tests with 202205 sonic-mgmt.  LC does not support macsec, so macsec was not running. However,  test failed in pre-test sanity check because macsec was running.

The issue was due to https://github.com/sonic-net/sonic-mgmt/pull/7003. With the PR,  macsec is required to run on all LCs that are configured as SpineRouter. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by judyjoseph** [comment]
@ysmanman is this issue seen on a particular LC which is a SpineRouter and don't support macsec ? 
With this PR #7003 we check if it is SpineRouter and if so add macsec as a default service.

Let me know if you have a scenario or a card which is a LC in SpineRouter and not supporting macsec. If so we will have fix #7003 by adding a check to see if platform supports macsec as well.

**Comment by arlakshm** [comment]
Fix in this PR https://github.com/sonic-net/sonic-mgmt/issues/7222
