### ISSUE TITLE
[chassis] test_lag_2.py is broken on multi-asic

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7281]
**Description**

Test uses redis-cli to check admin/oper status in redis-db without specifying namespace, which is broken on multi-asic.

**Steps to reproduce the issue:**
1. Run test_lag_2.py on multi-asic chassis. 
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@arlakshm, @abdosi can you review @ysmanman 's PR or assing someone to review?
