### ISSUE TITLE
test_iface_namingmode.py failed with "unable to connect to redis (unix-socket)"

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7282]
**Description**

test_show_acl_table failed with the following error:

14/01/2023 14:31:16 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/tests/iface_namingmode/test_iface_namingmode.py", line 805, in test_show_acl_table
    acl_table = dutHostGuest.shell('SONIC_CLI_IFACE_MODE={} show acl table DATAACL'.format(ifmode))['stdout']
  File "/data/tests/common/devices/base.py", line 89, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{"changed": true, "cmd": "SONIC_CLI_IFACE_MODE=default show acl table DATAACL", "delta": "0:00:00.911312", "end": "2023-01-14 14:31:16.052102", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2023-01-14 14:31:15.140790", "stderr": "Traceback (most rec\
ent call last):\n  File \"/usr/local/bin/acl-loader\", line 8, in <module>\n    sys.exit(cli())\n  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packag\
es/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 1134, in invoke\n    Command.invoke(self, ctx)\n  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 956, in invoke\\
n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packages/click/decorators.py\", line 17, in new_func\\
n    return f(get_current_context(), *args, **kwargs)\n  File \"/usr/local/lib/python3.9/dist-packages/acl_loader/main.py\", line 944, in cli\n    \"acl_loader\": AclLoader()\n  File \"/usr/local/lib/python3.9/dist-packages/acl_loader/main.py\", line 151, in __init__\n\
    self.per_npu_configdb[front_asic_namespaces].connect()\n  File \"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py\", line 1859, in connect\n    return _swsscommon.ConfigDBConnector_Native_connect(self, wait_for_init, retry_on)\nRuntimeError: Unable to connec\
t to redis (unix-socket): Cannot assign requested address", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/bin/acl-loader\", line 8, in <module>", "    sys.exit(cli())", "  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line\
 764, in __call__", "    return self.main(*args, **kwargs)", "  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 717, in main", "    rv = self.invoke(ctx)", "  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 1134, in invoke", "   \
 Command.invoke(self, ctx)", "  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 956, in invoke", "    return ctx.invoke(self.callback, **ctx.params)", "  File \"/usr/local/lib/python3.9/dist-packages/click/core.py\", line 555, in invoke", "    retur\
n callback(*args, **kwargs)", "  File \"/usr/local/lib/python3.9/dist-packages/click/decorators.py\", line 17, in new_func", "    return f(get_current_context(), *args, **kwargs)", "  File \"/usr/local/lib/python3.9/dist-packages/acl_loader/main.py\", line 944, in cli"\
, "    \"acl_loader\": AclLoader()", "  File \"/usr/local/lib/python3.9/dist-packages/acl_loader/main.py\", line 151, in __init__", "    self.per_npu_configdb[front_asic_namespaces].connect()", "  File \"/usr/lib/python3/dist-packages/swsscommon/swsscommon.py\", line 1\
859, in connect", "    return _swsscommon.ConfigDBConnector_Native_connect(self, wait_for_init, retry_on)", "RuntimeError: Unable to connect to redis (unix-socket): Cannot assign requested address"], "stdout": "", "stdout_lines": []}

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
The issue is the guest user was created without permission to access redis https://github.com/sonic-net/sonic-mgmt/blob/bfed495fe138f123c96f1d5eadc8afeccf74b2b4/tests/iface_namingmode/test_iface_namingmode.py#L122

**Comment by yxieca** [comment]
@arlakshm please review @ysmanman's PR addressing this issue.

**Comment by arlakshm** [comment]
@ysmanman the PR sonic-net/sonic-utilities#2525
