### ISSUE TITLE
route/test_route_flap.py multi-asic script support

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#7288]
**Description**

route script to use namespace for multi-asic platform:

failure : route/test_route_flap.py----route.test_route_flap----test_route_flap
	 Summary: RunAnsibleModuleFail: run module shell failed, Ansible Results => {     "changed": true,      "cmd": "vtysh -c \"show ip bgp ipv4 json\"",      "delta": "0:00:00.006029",      "end": "2022-12-23 09:23:19.068367",      "failed": true,      "invocation": {         "module_args": {             "_raw_params": "vtysh -c \"show ip bgp ipv4 json\"",              "_uses_shell": true,              "argv": null,              "chdir": null,              "creates": null,              "executable": null,              "removes": null,              "stdin": null,              "stdin_add_newline": true,              "strip_empty_ends": true,              "warn": true         }     },      "msg": "non-zero return code",      "rc": 1,      "start": "2022-12-23 09:23:19.062338",      "stderr": "Usage: /usr/bin/vtysh -n [0 to 2] [OPTION]... ",      "stderr_lines": [         "Usage: /usr/bin/vtysh -n [0 to 2] [OPTION]... "     ],      "stdout": "",      "stdout_lines": [] }

**Steps to reproduce the issue:**
1. running route/test_route_flap.py sonic-mgmt test

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rajendrat** [comment]
@abdosi @vperumal

**Comment by abdosi** [comment]
@rajendrat  : multi-asic support is their for this test script now.
