### ISSUE TITLE
Current installation scripts call "pip install" under root user and can break the host packaging system

### ISSUE THREAD

**Issue by guillaumelambert** [sonic-net/sonic-mgmt#7318]
When no j2cli executable can be detected, the deployment script ansible/setup-management-network.sh tries to install it using pip.

According to the documentation at docs/testbed/README.testbed.Setup.md this script must be launched with sudo during the deployment process.

Running "sudo pip install" can be OK in a CI or inside a test container but it generates a clear warning.
It is strongly disadvised to run "pip install" under root in a user or a production environment because it can break the host packages system. "pip install --user" or venv are usually prefered in most situations.

https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice

**Comment by yxieca** [comment]
@theasianpianist can you help review the PR addressing this issue?
