### ISSUE TITLE
test_show_ip_route_v4 fails in T2 topology due to incorrectly specified route

### ISSUE THREAD

**Issue by kartik-arista** [sonic-net/sonic-mgmt#7335]
**Description**

**Steps to reproduce the issue:**

execute  test_show_ip_route_v4 on a T2 topology.

**Describe the results you received:**

The test failed  as

```
       dutHostGuest, mode, ifmode = setup_config_mode
        route = dutHostGuest.shell('SONIC_CLI_IFACE_MODE={} show ip route 192.168.1.1'.format(ifmode))['stdout']
        logger.info('route:\n{}'.format(route))

        if mode == 'alias':
            for alias in spine_ports['alias']:
>               assert re.search(r'via {}'.format(alias), route) is not None
E               AssertionError
```

**Describe the results you expected:**

The test should pass successfully.

**Additional information you deem important:**

The fix should be to either generalize to verify the default route for all topologies (which should be reasonable)
or to introduce some conditionality that verifies the default route on T2 but preserves existing behavior on other topologies.

Note that the v6 version of the test does verify the V6 default route:

```
 route = dutHostGuest.shell('SONIC_CLI_IFACE_MODE={} show ipv6 route ::/0'.format(ifmode))['stdout']
```

**Comment by ysmanman** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/7411 should fix this.

**Comment by ysmanman** [comment]
Add @arlakshm @wenyiz2021 for viz.

**Comment by yxieca** [comment]
@ysmanman I think your fix is hiding the issue? Shouldn't the fix be that: get the ip route for the prefix, parse the output, assert that the output should contain either the target route or '0.0.0.0'?

**Comment by arlakshm** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/7411 is merged. Closing this issue
