### ISSUE TITLE
[chassis] qos/test_buffer is broken on multi-aisc

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7415]
**Description**

The current implementation of the test is not working with multi-asic, e.g., not finding qos profiles in asic directory and checking db in host, instead of in asic namespace.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by sanmalho-git** [comment]
This is addressed in https://github.com/sonic-net/sonic-mgmt/pull/7079

**Comment by ysmanman** [comment]
> This is addressed in #7079

Hi @sanmalho-git. it's not clear to me that PR also addresses the multi-asic support of qos/test_buffers.py.  Add @vmittal-msft to clarify.

**Comment by vmittal-msft** [comment]
This should handle multi asic case. We will first push 7079 once tested out. Then 6946.
https://github.com/sonic-net/sonic-mgmt/pull/6946

**Comment by yxieca** [comment]
@vmittal-msft can this issue be closed now?

**Comment by vmittal-msft** [comment]
We can close this as PR #7079 is part of github.
