### ISSUE TITLE
test_everflow_per_interface injects ipv4 packet in ipv6 test case

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7455]
**Description**

test_everflow_per_interface is hardcoded to generate ipv4 packetss, which is not working in ipv6 test case.

https://github.com/sonic-net/sonic-mgmt/blob/1ee0fdc330907ffac9791e6a8a47263f23cc6e87/tests/everflow/test_everflow_per_interface.py#L160-L163

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
Add @arlakshm @wenyiz2021 for awareness.

**Comment by bingwang-ms** [comment]
The issue has been addressed by https://github.com/sonic-net/sonic-mgmt/pull/7495
