### ISSUE TITLE
[test gap] Add a test case to verify ECMP is not impacted by unexpected fields 

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#7509]
**Description**

We found ECMP is impacted by some unexpected field (payload length of inner frame in a IPinIP packet) on some platform. The existing `test_hash.py` verified the traffic is distributed evenly among all paths. We need to improve the existing script or add a new test case to verify the hash in ECMP is not impacted by unexpected fields in the packet.

The test case should be running on all topology.
**Steps to reproduce the issue:**
1. Generate IPinIP packet with various inner_frame length, but keep the other fields not changed (MAC, IP, port, protocol)
2. Send the packet to DUT. The packet should be routed by default route
3. Check the counters in each upstream port, and capture the traffic on ptf. We should see all the packets go to the same upstream neighbor.

**Describe the results you received:**

**Describe the results you expected:**
The path should be fixed for various inner frame length.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@bingwang-ms is this a duplicate of #7525?

This is a good candidate for hardware tester. Software solution is also welcome.

@isgmano please help assess if Ixia could help.

**Comment by bingwang-ms** [comment]
> @bingwang-ms is this a duplicate of #7525?
> 
> This is a good candidate for hardware tester. Software solution is also welcome.
> 
> @isgmano please help assess if Ixia could help.

Yes, seems Kevin also open a test gap for the same issue. I'll close mine.
