### ISSUE TITLE
test_techsupport_commands fails on DNX based platforms due to incorrect bcmcmd specfications

### ISSUE THREAD

**Issue by kartik-arista** [sonic-net/sonic-mgmt#7510]
test_techsupport_commands fail with an error because the test is not aware of DNX family and tries to execute common commands.

**Steps to reproduce the issue:**

run the above test on any DNX platform.

**Describe the results you received:**

```
--- FAILED: test_techsupport_commands[cmp227-4] Failed!
Failed: defaultdict(<type 'list'>, {'broadcom_cmd_bcmcmd': ['bcmcmd -n 0 "l3 nat_ingress show"', 'bcmcmd -n 1 "l3 nat_ingress show"', 'bcmcmd -n 0 "l3 nat_egress show"', '\
bcmcmd -n 1 "l3 nat_egress show"', 'bcmcmd -n 0 "ipmc table show"', 'bcmcmd -n 1 "ipmc table show"', 'bcmcmd -n 0 "multicast show"', 'bcmcmd -n 1 "multicast show"', 'bcmcm\
d -n 0 "fp show"', 'bcmcmd -n 1 "fp show"', 'bcmcmd -n 0 "pvlan show"', 'bcmcmd -n 1 "pvlan show"', 'bcmcmd -n 0 "l3 intf show"', 'bcmcmd -n 1 "l3 intf show"', 'bcmcmd -n
```

**Describe the results you expected:**

The test should have passed.

The fix is to have checks in the test to expect the specific tech_support commands based on family.

**Comment by yxieca** [comment]
@adyeung do you think Broadcom can help triage / address this issue?

Sounds like we need to be able to distinguish DNX v.s. XGS platform at run time and have list of commands for them respectively.
