### ISSUE TITLE
[test gap] Validate the IPinIP packet can be transferred without any re-order

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-mgmt#7525]
**Description**
We observed some IPinIP packets are reordered which belong to the same stream. This is unexpected. Need a new case to cover this scenario.

**Steps to reproduce the issue:**
1. Send IPinIP packet with different payload lengths - 512 and 1000 (same src port/ip, dst port/ip, protocol in the inner packet) from the source port to the target port of a traffic generator
2. Can make use of the following topology
    traffic gen(port 1) --- dut ---- traffic gen(port 2)

**Describe the results you received:**
Traffic was received out of order on port 2

**Describe the results you expected:**
There should not be any reordering of packets received on port 2

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
Good candidate for Ixia/hardware tester.

**Comment by kamalsahu0001** [comment]
Surely, Keysight can help with this case. Just wanted to understand the use case better, Is it enough to send IPnIP packet through ECMP links or it has to go through the tunnel? Also, testing it on single t0 device is enough?

**Comment by developfast** [comment]
@kamalsahu0001 I am actively working on this test gap. I have reached out through internal channels for assistance on the specific ixia snappi API available for the metric.
