### ISSUE TITLE
A new parameter is added for neighbor_vm_restore but the usage in advanceboot_neighbor_restore is not updated

### ISSUE THREAD

**Issue by congh-nvidia** [sonic-net/sonic-mgmt#7582]
**Description**
In recent PR https://github.com/sonic-net/sonic-mgmt/pull/7461, a new parameter "result" is added to the function neighbor_vm_restore:
https://github.com/sonic-net/sonic-mgmt/blob/a45d53f195f0bfe3fd0edcfdbc3f1e998b246681/tests/common/plugins/sanity_check/recover.py#L114
This function is called in a fixture advanceboot_neighbor_restore in:
https://github.com/sonic-net/sonic-mgmt/blob/a45d53f195f0bfe3fd0edcfdbc3f1e998b246681/tests/platform_tests/conftest.py#L564
But the parameters are not updated.

**Steps to reproduce the issue:**
1. Run the test tests/platform_tests/test_advanced_reboot.py::test_warm_reboot_sad
2.
3.

**Describe the results you received:**
    @pytest.fixture()
    def advanceboot_neighbor_restore(duthosts, enum_rand_one_per_hwsku_frontend_hostname, nbrhosts, tbinfo):
        """
        This fixture is invoked at the test teardown for advanced-reboot SAD cases.
        If a SAD case fails or crashes for some reason, the neighbor VMs can be left in
        a bad state. This fixture will restore state of neighbor interfaces, portchannels
        and BGP sessions that were shutdown during the test.
        """
        yield
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
>       neighbor_vm_restore(duthost, nbrhosts, tbinfo)
E       TypeError: neighbor_vm_restore() takes exactly 4 arguments (3 given)

**Describe the results you expected:**
Test passes

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Pterosaur** [comment]
Hi Cong, thanks for your feedback. I create a PR: https://github.com/sonic-net/sonic-mgmt/pull/7586 for it. Could you help to check it?

**Comment by congh-nvidia** [comment]
> Hi Cong, thanks for your feedback. I create a PR: #7586 for it. Could you help to check it?

Hi Ze, the fix looks good to me, thanks.

**Comment by Pterosaur** [comment]
> > Hi Cong, thanks for your feedback. I create a PR: #7586 for it. Could you help to check it?
> 
> Hi Ze, the fix looks good to me, thanks.

Could you please help to approve this PR?

**Comment by congh-nvidia** [comment]
> > > Hi Cong, thanks for your feedback. I create a PR: #7586 for it. Could you help to check it?
> > 
> > 
> > Hi Ze, the fix looks good to me, thanks.
> 
> Could you please help to approve this PR?

Sorry, but I don't have the permission to approve a PR.

**Comment by congh-nvidia** [comment]
> > > Hi Cong, thanks for your feedback. I create a PR: #7586 for it. Could you help to check it?
> > 
> > 
> > Hi Ze, the fix looks good to me, thanks.
> 
> Could you please help to approve this PR?

Done
