### ISSUE TITLE
Where can I download the pre-built docker-sonic-mgmt and docker-ptf for sonic-mgmt 202205 branch?

### ISSUE THREAD

**Issue by oldboyzzzz** [sonic-net/sonic-mgmt#7596]
Hi,

Where can I download the pre-built docker-sonic-mgmt and docker-ptf for sonic-mgmt 202205 branch?

My sonic-mgmt testbed needs to run 202205 branch scripts.But the download urls of pre-built docker-sonic-mgmt/docker-ptf in 202205 [README.testbed.Setup.md](http://readme.testbed.setup.md/)  and master [README.testbed.Setup.md](http://readme.testbed.setup.md/) are the same. Example, for docker-sonic-mgmt download url, both are:
 https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=master&definitionId=194&artifactName=docker-sonic-mgmt&target=target%2Fdocker-sonic-mgmt.gz

Looks like the download urls are for master only.

How can I download 202205 based docker-sonic-mgmt and docker-ptf?

Thanks,

John

**Comment by yxieca** [comment]
@oldboyzzzz , docker-sonic-mgmt and/or docker-ptf are not changing frequently. It is best to use these dockers downloaded from master branch even if you want to run a test for 202205 branch.

Do you have specific reason you want to use these dockers from 202205 branch?

**Comment by yxieca** [comment]
If you want to download these dockers build for 202205 branch, you can go to the download page and select 202205 branch target.

Can you try this link? https://dev.azure.com/mssonic/build/_build?definitionId=142&_a=summary

**Comment by oldboyzzzz** [comment]
Hi yxieca,

Much appreciated of your reply. As per your comment, now I don't have concerns on using master mgmt-docker/ptf-docker to run 202205 branch. Will stay on the master ones.
