### ISSUE TITLE
Withdraw routes timely effective when BGP session is teared down.

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-mgmt#7714]
**Description**
With quagga, the routes withdraw could be delayed up to update hold timer when BGP session is teared down, it could cause transient route blackhole. 
Need to have a test case to check if routes withdraw update are immediately advertised out to it's neighbor.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by sdszhang** [comment]
issue has been addressed in https://github.com/sonic-net/sonic-mgmt/pull/7847 . Closing it.
