### ISSUE TITLE
To change various sonic-vs images on DUT/VM's

### ISSUE THREAD

**Issue by Vickyni2** [sonic-net/sonic-mgmt#7717]
**Description :** 
Trying to Install other sonic Vs-images to the VM's and DUT.

**Steps to reproduce the issue:**
1. Copying the other image to inside the VM/DUT  .
2.  sonic-installer install ( Image ).
3. sonic-installer list.

**Describe the results you received:**
I've Copied other image inside the VM and  trying to install other images inside the VM. It's getting aborted !!!

root@VM0102:~# sonic-installer install sonic-vs_old.img
New image will be installed, continue? [y/N]: y
Image file does not exist or is not a valid SONiC image file
Aborted!
root@VM0102:~#

When I try to list the available images in the Vm's Its not listed .
I've Copied both the creation path and inside the Vm also . 

Root privileges required for this operation
admin@VM0102:~$ sudo -i
root@VM0102:~# sonic-installer list
Current: SONiC-OS-master.228991-506f37253
Next: SONiC-OS-master.228991-506f37253
Available:
SONiC-OS-master.228991-506f37253
root@VM0102:~# ls
sonic-vs_old.img
root@VM0102:~#

**Comment by MahendranPackiam** [comment]
@wangxin  Can you please help with this query. Thanks

**Comment by wangxin** [comment]
Hi @MahendranPackiam 
KVM based SONiC does not support sonic-installer to upgrade image.
You can use `testbed-cli.sh refresh-dut` to re-create the SONiC KVM to update image.
