### ISSUE TITLE
Running test_eth_interface.py on system with up to 32 ports (indexes), lead to an error: "xcvrd SFP index 32 out of range (0-31)" when

### ISSUE THREAD

**Issue by dprital** [sonic-net/sonic-mgmt#7733]
**Description**

Running test_eth_interface.py test on system with up to 32 [0:31] port indexes, lead to the following errors:

   
    Feb 25 13:35:56.966698 r-leopard-58 ERR pmon#xcvrd: Exception occured at SfpStateUpdateTask thread due to AttributeError("'NoneType' object has no attribute 'get_presence'")
    Feb 25 13:35:56.966698 r-leopard-58 INFO pmon#supervisord: xcvrd SFP index 32 out of range (0-31)
    Feb 25 13:35:56.970645 r-leopard-58 ERR pmon#xcvrd: Traceback (most recent call last):
    Feb 25 13:35:56.970645 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2049, in run
    Feb 25 13:35:56.970645 r-leopard-58 ERR pmon#xcvrd:     self.task_worker(self.task_stopping_event, self.sfp_error_event)
    Feb 25 13:35:56.970759 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 1862, in task_worker
    Feb 25 13:35:56.970785 r-leopard-58 ERR pmon#xcvrd:     port_mapping.handle_port_config_change(sel, asic_context, stopping_event, self.port_mapping, helper_logger, self.on_port_config_change)
    Feb 25 13:35:56.970815 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd_utilities/port_mapping.py", line 225, in handle_port_config_change
    Feb 25 13:35:56.970815 r-leopard-58 ERR pmon#xcvrd:     read_port_config_change(asic_context, port_mapping, logger, port_change_event_handler)
    Feb 25 13:35:56.970854 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd_utilities/port_mapping.py", line 255, in read_port_config_change
    Feb 25 13:35:56.970896 r-leopard-58 ERR pmon#xcvrd:     port_change_event_handler(port_change_event)
    Feb 25 13:35:56.970923 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2082, in on_port_config_change
    Feb 25 13:35:56.970951 r-leopard-58 ERR pmon#xcvrd:     self.on_add_logical_port(port_change_event)
    Feb 25 13:35:56.970970 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 2190, in on_add_logical_port
    Feb 25 13:35:56.971000 r-leopard-58 ERR pmon#xcvrd:     if _wrapper_get_presence(port_change_event.port_index) and read_eeprom:
    Feb 25 13:35:56.971019 r-leopard-58 ERR pmon#xcvrd:   File "/usr/local/lib/python3.9/dist-packages/xcvrd/xcvrd.py", line 154, in _wrapper_get_presence
    Feb 25 13:35:56.971050 r-leopard-58 ERR pmon#xcvrd:     return platform_chassis.get_sfp(physical_port).get_presence()
    Feb 25 13:35:56.971069 r-leopard-58 ERR pmon#xcvrd: AttributeError: 'NoneType' object has no attribute 'get_presence'
    Feb 25 13:35:56.971253 r-leopard-58 ERR pmon#xcvrd: Xcvrd: exception found at child thread SfpStateUpdateTask due to AttributeError("'NoneType' object has no attribute 'get_presence'")
    Feb 25 13:35:56.971270 r-leopard-58 ERR pmon#xcvrd: Exiting main loop as child thread raised exception!

Due to the following (from :sonic-mgmt/tests/generic_config_updater/test_eth_interface.py):

    ```
    @pytest.mark.parametrize("index, is_valid", [
        ("33", True),
            ("abc1", False)
            ])

<!--
Briefly describe the problem you are having in a few paragraphs.
-->

**Steps to reproduce the issue:**
1. Run "test_eth_interface.py" test and check the LOG after
2. See the Errors listed above 

**Describe the results you received:**
1. LOG Errors as described above

**Describe the results you expected:**
1. Run the test with no Errors in LOG

**Additional information you deem important:**
<!--
software/ASIC/Hardware Flatform version and info
-->
    **Output of `show version`:**

    ```
    SONiC Software Version: SONiC.202205_2_rc.5-f1dfee1fe_Internal
    Distribution: Debian 11.6
    Kernel: 5.10.0-18-2-amd64
    Build commit: f1dfee1fe
    Build date: Tue Feb 21 20:34:33 UTC 2023
    Built by: sw-r2d2-bot@r-build-sonic-ci03-243
    
    Platform: x86_64-mlnx_msn4700-r0
    HwSKU: ACS-MSN4700
    ASIC: mellanox
    ASIC Count: 1
    Serial Number: MT2119X03331
    Model Number: MSN4700-WS2F_QP1
    Hardware Revision: A1
    Uptime: 13:40:21 up  8:30,  2 users,  load average: 1.71, 1.29, 1.10
    Date: Sat 25 Feb 2023 13:40:21
    
    Docker images:
    REPOSITORY                                         TAG                                IMAGE ID       SIZE
    docker-fpm-frr                                     202205_2_rc.5-f1dfee1fe_Internal   56bb380645c8   530MB
    docker-fpm-frr                                     latest                             56bb380645c8   530MB
    docker-orchagent                                   202205_2_rc.5-f1dfee1fe_Internal   171014e53625   519MB
    docker-orchagent                                   latest                             171014e53625   519MB
    docker-teamd                                       202205_2_rc.5-f1dfee1fe_Internal   be4fadc39b09   500MB
    docker-teamd                                       latest                             be4fadc39b09   500MB
    docker-macsec                                      202205_2_rc.5-f1dfee1fe_Internal   89e9a2474316   503MB
    docker-syncd-mlnx                                  202205_2_rc.5-f1dfee1fe_Internal   32f924b71a10   915MB
    docker-syncd-mlnx                                  latest                             32f924b71a10   915MB
    docker-platform-monitor                            202205_2_rc.5-f1dfee1fe_Internal   57492b28a7b3   920MB
    docker-platform-monitor                            latest                             57492b28a7b3   920MB
    docker-dhcp-relay                                  202205_2_rc.5-f1dfee1fe_Internal   60365b4de0ec   494MB
    docker-snmp                                        202205_2_rc.5-f1dfee1fe_Internal   ef87d91b74ed   529MB
    docker-snmp                                        latest                             ef87d91b74ed   529MB
    docker-mux                                         202205_2_rc.5-f1dfee1fe_Internal   b47df6b51285   533MB
    docker-mux                                         latest                             b47df6b51285   533MB
    docker-lldp                                        202205_2_rc.5-f1dfee1fe_Internal   3de9ee2d5b42   527MB
    docker-lldp                                        latest                             3de9ee2d5b42   527MB
    docker-sonic-telemetry                             202205_2_rc.5-f1dfee1fe_Internal   115b6c541b65   565MB
    docker-sonic-telemetry                             latest                             115b6c541b65   565MB
    docker-database                                    202205_2_rc.5-f1dfee1fe_Internal   320e9ab808de   484MB
    docker-database                                    latest                             320e9ab808de   484MB
    docker-router-advertiser                           202205_2_rc.5-f1dfee1fe_Internal   6e5782a78952   484MB
    docker-router-advertiser                           latest                             6e5782a78952   484MB
    docker-sonic-mgmt-framework                        202205_2_rc.5-f1dfee1fe_Internal   9276f706e7a4   598MB
    docker-sonic-mgmt-framework                        latest                             9276f706e7a4   598MB
    docker-sflow                                       202205_2_rc.5-f1dfee1fe_Internal   9ba2e59cfc7a   469MB
    docker-sflow                                       latest                             9ba2e59cfc7a   469MB
    docker-nat                                         202205_2_rc.5-f1dfee1fe_Internal   c55772828f7e   471MB
    docker-nat                                         latest                             c55772828f7e   471MB
    urm.nvidia.com/sw-nbu-sws-sonic-docker/sonic-wjh   1.3.3-202205-4                     be754e3710ef   310MB
    urm.nvidia.com/sw-nbu-sws-sonic-docker/doroce      1.0.1-202205-internal-1            71d2b33030e2   200MB
    

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lipxu** [comment]
Hi, @isabelmsft and @bingwang-ms , may you please help to check whether this issue is a  known issue, and be fixed by the below PR, thanks a lot.
https://github.com/sonic-net/sonic-mgmt/pull/8129

**Comment by isabelmsft** [comment]
Closed with this PR:
