### ISSUE TITLE
[test_stress_arp] run time too long

### ISSUE THREAD

**Issue by wangxin** [sonic-net/sonic-mgmt#7874]
**Description**

**Steps to reproduce the issue:**
1. Run the arp/test_stress_arp.py script.
2.
3.

**Describe the results you received:**
The script needs couple of hours to run. This is not acceptable during nightly test. 

**Describe the results you expected:**
Need to optimize the script to ensure that it can complete in 30 minutes.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
@yutongzhang-microsoft Please consider reduce the loop count, or the hardcoded sleep.

**Comment by yutongzhang-microsoft** [comment]
The first step is to remove unnecessary wait_until in test case, #11922
But this is not enough, sending one packet needs 2 seconds, I'm trying to speed up sending packet.

**Comment by vivekverma-arista** [comment]
Hi @wangxin 

Will [#11922](https://github.com/sonic-net/sonic-mgmt/pull/11922) this be backported to other branches like 202305/202311? 

The issue was closed so the test has started running on all branches taking long time as the change in the pull request is not yet present in other branches.

Keeping @StormLiangMS in the loop.

**Comment by StormLiangMS** [comment]
reopen this issue, since the fix is not cherry-picked to 202305/202311 yet.

**Comment by lipxu** [comment]
@yutongzhang-microsoft  seems the PR had already merged into 202305/202311, could we close this issue now, thanks
