### ISSUE TITLE
[test_ipinip] | TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by slutati1536** [sonic-net/sonic-mgmt#7881]
**Description**

test failed over py3 migration, test fail with error 
TypeError: a bytes-like object is required, not 'str'

**Steps to reproduce the issue:**
1.run dualtor/test_ipinip.py

**Describe the results you received:**
    @pytest.fixture(scope="function")
    def build_encapsulated_packet(rand_selected_interface, ptfadapter,          # noqa F401
                                  rand_selected_dut, tunnel_traffic_monitor):   # noqa F811
        """Build the encapsulated packet sent from T1 to ToR."""
        tor = rand_selected_dut
        _, server_ips = rand_selected_interface
        server_ipv4 = server_ips["server_ipv4"].split("/")[0]
        config_facts = tor.get_running_config_facts()
        try:
            peer_ipv4_address = [_["address_ipv4"] for _ in list(config_facts["PEER_SWITCH"].values())][0]
        except IndexError:
            raise ValueError("Failed to get peer ToR address from CONFIG_DB")
    
        tor_ipv4_address = [_ for _ in config_facts["LOOPBACK_INTERFACE"]["Loopback0"]
                            if is_ipv4_address(_.split("/")[0])][0]
        tor_ipv4_address = tor_ipv4_address.split("/")[0]
    
        inner_dscp = random.choice(list(range(0, 33)))
        inner_ttl = random.choice(list(range(3, 65)))
        inner_packet = testutils.simple_ip_packet(
            ip_src="1.1.1.1",
            ip_dst=server_ipv4,
            ip_dscp=inner_dscp,
            ip_ttl=inner_ttl
        )[IP]
        packet = testutils.simple_ipv4ip_packet(
            eth_dst=tor.facts["router_mac"],
            eth_src=ptfadapter.dataplane.get_mac(0, 0),
            ip_src=peer_ipv4_address,
            ip_dst=tor_ipv4_address,
            ip_dscp=inner_dscp,
            ip_ttl=255,
            inner_frame=inner_packet
        )
>       logging.info("the encapsulated packet to send:\n%s", dump_scapy_packet_show_output(packet))

_          = 'Ethernet156'
config_facts = {'ACL_TABLE': {'DATAACL': {'policy_desc': 'DATAACL', 'ports': ['PortChannel101', 'PortChannel102', 'PortChannel103', '...'rate_limit_interval': '600', 'state': 'enabled'}, ...}, 'BGP_DEVICE_GLOBAL': {'STATE': {'tsa_enabled': 'false'}}, ...}
inner_dscp = 26
inner_packet = <IP  ihl=None tos=0x68 id=1 ttl=61 proto=hopopt src=1.1.1.1 dst=192.168.0.26 |<Raw  load='\x00\x01\x02\x03\x04\x05\x06...b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>
inner_ttl  = 61
packet     = <Ether  dst=1c:34:da:c9:60:00 src=b'76:34:9e:fa:fd:00' type=IPv4 |<IP  ihl=None tos=0x68 id=1 flags= frag=0 ttl=255 pr...x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>>
peer_ipv4_address = '10.1.0.33'
ptfadapter = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>
rand_selected_dut = <MultiAsicSonicHost r-tigon-20>
rand_selected_interface = ('Ethernet156', {'server_ipv4': '192.168.0.26/32', 'server_ipv6': 'fc02:1000::1a/128', 'state': 'auto'})
server_ips = {'server_ipv4': '192.168.0.26/32', 'server_ipv6': 'fc02:1000::1a/128', 'state': 'auto'}
server_ipv4 = '192.168.0.26'
tor        = <MultiAsicSonicHost r-tigon-20>
tor_ipv4_address = '10.1.0.32'
tunnel_traffic_monitor = <class 'tests.common.dualtor.tunnel_traffic_utils.tunnel_traffic_monitor.<locals>.TunnelTrafficMonitor'>

dualtor/test_ipinip.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/utilities.py:507: in dump_scapy_packet_show_output
    packet.show()
        _stdout    = <_io.TextIOWrapper name="<_io.FileIO name=10 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>
        packet     = <Ether  dst=1c:34:da:c9:60:00 src=b'76:34:9e:fa:fd:00' type=IPv4 |<IP  ihl=None tos=0x68 id=1 flags= frag=0 ttl=255 pr...x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>>
/var/AzDevOps/env-python3/lib/python3.8/site-packages/scapy/packet.py:1464: in show
    return self._show_or_dump(dump, indent, lvl, label_lvl)
        dump       = False
        indent     = 3
        label_lvl  = ''
        lvl        = ''
        self       = <Ether  dst=1c:34:da:c9:60:00 src=b'76:34:9e:fa:fd:00' type=IPv4 |<IP  ihl=None tos=0x68 id=1 flags= frag=0 ttl=255 pr...x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Ether  dst=1c:34:da:c9:60:00 src=b'76:34:9e:fa:fd:00' type=IPv4 |<IP  ihl=None tos=0x68 id=1 flags= frag=0 ttl=255 pr...x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>>
dump = False, indent = 3, lvl = '', label_lvl = '', first_call = True

    def _show_or_dump(self,
                      dump=False,  # type: bool
                      indent=3,  # type: int
                      lvl="",  # type: str
                      label_lvl="",  # type: str
                      first_call=True  # type: bool
                      ):
        # type: (...) -> Optional[str]
        """
        Internal method that shows or dumps a hierarchical view of a packet.
        Called by show.
    
        :param dump: determine if it prints or returns the string value
        :param int indent: the size of indentation for each layer
        :param str lvl: additional information about the layer lvl
        :param str label_lvl: additional information about the layer fields
        :param first_call: determine if the current function is the first
        :return: return a hierarchical view if dump, else print it
        """
    
        if dump:
            from scapy.themes import AnsiColorTheme
            ct = AnsiColorTheme()  # No color for dump output
        else:
            ct = conf.color_theme
        s = "%s%s %s %s \n" % (label_lvl,
                               ct.punct("###["),
                               ct.layer_name(self.name),
                               ct.punct("]###"))
        for f in self.fields_desc:
            if isinstance(f, ConditionalField) and not f._evalcond(self):
                continue
            if isinstance(f, Emph) or f in conf.emph:
                ncol = ct.emph_field_name
                vcol = ct.emph_field_value
            else:
                ncol = ct.field_name
                vcol = ct.field_value
            fvalue = self.getfieldval(f.name)
            if isinstance(fvalue, Packet) or (f.islist and f.holds_packets and isinstance(fvalue, list)):  # noqa: E501
                pad = max(0, 10 - len(f.name)) * " "
                s += "%s  \\%s%s\\\n" % (label_lvl + lvl, ncol(f.name), pad)
                fvalue_gen = SetGen(
                    fvalue,
                    _iterpacket=0
                )  # type: SetGen[Packet]
                for fvalue in fvalue_gen:
                    s += fvalue._show_or_dump(dump=dump, indent=indent, label_lvl=label_lvl + lvl + "   |", first_call=False)  # noqa: E501
            else:
                pad = max(0, 10 - len(f.name)) * " "
                begn = "%s  %s%s%s " % (label_lvl + lvl,
                                        ncol(f.name),
                                        pad,
                                        ct.punct("="),)
                reprval = f.i2repr(self, fvalue)
                if isinstance(reprval, str):
                    reprval = reprval.replace("\n", "\n" + " " * (len(label_lvl) +  # noqa: E501
                                                                  len(lvl) +
                                                                  len(f.name) +
                                                                  4))
                s += "%s%s\n" % (begn, vcol(reprval))
        if self.payload:
            s += self.payload._show_or_dump(  # type: ignore
                dump=dump,
                indent=indent,
                lvl=lvl + (" " * indent * self.show_indent),
                label_lvl=label_lvl,
                first_call=False
            )
    
        if first_call and not dump:
>           print(s)
E           TypeError: a bytes-like object is required, not 'str'

begn       = '  type      = '
ct         = <NoTheme>
dump       = False
f          = <XShortEnumField (Ether).type>
first_call = True
fvalue     = 2048
indent     = 3
label_lvl  = ''
lvl        = ''
ncol       = <function create_styler.<locals>.do_style at 0x7fcdc4ab63a0>
pad        = '      '
reprval    = 'IPv4'
s          = '###[ Ethernet ]### \n  dst       = 1c:34:da:c9:60:00\n  src       = b\'76:34:9e:fa:fd:00\'\n  type      = IPv4\n###[ ...10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f !"#$%&\\\'()*+,-./0123456789:;<=>?@A\'\n'
self       = <Ether  dst=1c:34:da:c9:60:00 src=b'76:34:9e:fa:fd:00' type=IPv4 |<IP  ihl=None tos=0x68 id=1 flags= frag=0 ttl=255 pr...x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>>
vcol       = <function create_styler.<locals>.do_style at 0x7fcdc4ab6c10>

/var/AzDevOps/env-python3/lib/python3.8/site-packages/scapy/packet.py:1447: TypeError

**Describe the results you expected:**
test should not fail over test issue

**Additional information you deem important:**
 **Output of `show version`:**
```
SONiC Software Version: SONiC.202211_RC8.3-696a6a43b_Internal
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: 696a6a43b
Build date: Mon Mar 27 10:50:51 UTC 2023
Built by: sw-r2d2-bot@r-build-sonic-ci03-244

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: Mellanox-SN4600C-C64
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2131X10295
Model Number: MSN4600-CS2FO
Hardware Revision: A1
Uptime: 13:16:06 up 13:25,  2 users,  load average: 1.37, 1.34, 1.30
Date: Tue 28 Mar 2023 13:16:06

Docker images:
REPOSITORY                                         TAG                               IMAGE ID       SIZE
docker-orchagent                                   202211_RC8.3-696a6a43b_Internal   84055ebb4c77   539MB
docker-orchagent                                   latest                            84055ebb4c77   539MB
docker-fpm-frr                                     202211_RC8.3-696a6a43b_Internal   83d5f57abddb   550MB
docker-fpm-frr                                     latest                            83d5f57abddb   550MB
docker-teamd                                       202211_RC8.3-696a6a43b_Internal   e6b58409a5c6   520MB
docker-teamd                                       latest                            e6b58409a5c6   520MB
docker-macsec                                      latest                            d76f633dda63   522MB
docker-syncd-mlnx                                  202211_RC8.3-696a6a43b_Internal   2bd090589266   939MB
docker-syncd-mlnx                                  latest                            2bd090589266   939MB
docker-platform-monitor                            202211_RC8.3-696a6a43b_Internal   4fcfc27b9bbe   942MB
docker-platform-monitor                            latest                            4fcfc27b9bbe   942MB
docker-sonic-telemetry                             202211_RC8.3-696a6a43b_Internal   be9f9e750657   802MB
docker-sonic-telemetry                             latest                            be9f9e750657   802MB
docker-snmp                                        202211_RC8.3-696a6a43b_Internal   62432cf85f40   549MB
docker-snmp                                        latest                            62432cf85f40   549MB
docker-eventd                                      202211_RC8.3-696a6a43b_Internal   855b7c3d7218   503MB
docker-eventd                                      latest                            855b7c3d7218   503MB
docker-dhcp-relay                                  latest                            c90d1c5967eb   513MB
docker-lldp                                        202211_RC8.3-696a6a43b_Internal   e33be345d3f2   546MB
docker-lldp                                        latest                            e33be345d3f2   546MB
docker-mux                                         202211_RC8.3-696a6a43b_Internal   e9f6fa7ef277   552MB
docker-mux                                         latest                            e9f6fa7ef277   552MB
docker-database                                    202211_RC8.3-696a6a43b_Internal   9cae58961a25   503MB
docker-database                                    latest                            9cae58961a25   503MB
docker-sonic-p4rt                                  202211_RC8.3-696a6a43b_Internal   77b20e5b758d   586MB
docker-sonic-p4rt                                  latest                            77b20e5b758d   586MB
docker-router-advertiser                           202211_RC8.3-696a6a43b_Internal   f3a99688e9df   503MB
docker-router-advertiser                           latest                            f3a99688e9df   503MB
docker-sflow                                       202211_RC8.3-696a6a43b_Internal   780973343beb   479MB
docker-sflow                                       latest                            780973343beb   479MB
docker-nat                                         202211_RC8.3-696a6a43b_Internal   83454bb6925c   481MB
docker-nat                                         latest                            83454bb6925c   481MB
docker-sonic-mgmt-framework                        202211_RC8.3-696a6a43b_Internal   20cfc12ab3c5   612MB
docker-sonic-mgmt-framework                        latest                            20cfc12ab3c5   612MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/doroce      1.1.0-202211-internal-5           078ba366e374   200MB
urm.nvidia.com/sw-nbu-sws-sonic-docker/sonic-wjh   1.4.0-202211-internal-5           b4f92852d9ca   323MB
```

**Comment by wsycqyz** [comment]
Fixed in #8063
