### ISSUE TITLE
[ test_orch_stress ] | test configures incorrect ip commands

### ISSUE THREAD

**Issue by slutati1536** [sonic-net/sonic-mgmt#7934]
**Description**
test is configuring in correct commands because fixture mock_server_ip_mac_map returns dict:
mock_server_ip_mac_map = {IPv4Address('192.168.0.2'): b'b8:ce:f6:56:da:06', IPv4Address('192.168.0.3'): b'b8:ce:f6:56:da:07', IPv4Address('192.168.0.4'): b'b8:ce:f6:56:da:08', IPv4Address('192.168.0.5'): b'b8:ce:f6:56:da:09', ...}

values should be strings not bytes.

**Steps to reproduce the issue:**
1.run the test test_flap_neighbor_entry_active/test_flap_neighbor_entry_standby

**Describe the results you received:**

test configures command:
ip -4 neigh replace 192.168.0.2 lladdr b'b8:ce:f6:56:da:06' dev Vlan1000

the command should be:
ip -4 neigh replace 192.168.0.2 lladdr b8:ce:f6:56:da:06 dev Vlan1000

and because the incorrect command test failed over error:
"\"bb8\" is invalid lladdr.\n",

**Describe the results you expected:**
the commands should be in correct syntax

**Comment by bingwang-ms** [comment]
It seems to be a python2 to python3 migration issue. May I know on which branch did you see this error?

**Comment by wsycqyz** [comment]
Working on it
