### ISSUE TITLE
[ip/test_forward_ip_packet_with_0xffff_chksum_drop] Failed in tx cnt check

### ISSUE THREAD

**Issue by ysmanman** [sonic-net/sonic-mgmt#7954]
**Description**

We observed the test was flaky in recent T2 testing with DNX chassis. Test injects 1000 identical packets, and expects them to be dropped.  But it failed in tx cnt check https://github.com/sonic-net/sonic-mgmt/blob/34ce7e3c2cec20a7619af5b005dea21282bed8ef/tests/ip/test_ip_packet.py#L386-L387

PKT_NUM_ZERO is 100 in this case https://github.com/sonic-net/sonic-mgmt/blob/34ce7e3c2cec20a7619af5b005dea21282bed8ef/tests/ip/test_ip_packet.py#L29

When test failed,  the value of `tx_ok` was something between 100 and 200. The `tx_ok` is likely counting the background traffic.  So it seems the computation of  `PKT_NUM_ZERO` is not quite working in T2 testing.

Furthermore, the tests also validates that expected packet should not egress out from switch. So not sure the above tx cnt check is really needed.
https://github.com/sonic-net/sonic-mgmt/blob/34ce7e3c2cec20a7619af5b005dea21282bed8ef/tests/ip/test_ip_packet.py#L390-L391 

**Steps to reproduce the issue:**
1. Run the test on DNX chassis with T2 topo.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by ysmanman** [comment]
Add @arlakshm @wenyiz2021 for visibility.

**Comment by tjchadaga** [comment]
Fixed by https://github.com/sonic-net/sonic-mgmt/pull/8414

**Comment by arista-nwolfe** [comment]
This issue is hitting again on 202405 T2 devices, specifically on the upstream LCs it seems.

Here is an example of the number of packets seen on our recent runs:
```
cmp235-3:
Failed: Forwarded 276 packets in tx, not in expected range

cmp227-4:
Failed: Forwarded 275 packets in tx, not in expected range
Failed: Forwarded 264 packets in tx, not in expected range
Failed: Forwarded 295 packets in tx, not in expected range
Failed: Forwarded 316 packets in tx, not in expected range

cmp206-4:
Failed: Forwarded 301 packets in tx, not in expected range
Failed: Forwarded 264 packets in tx, not in expected range
```

I think maybe we should increase the tolerance from 20% to 40%.
I checked the device and all 1000 packets were RX_DROP'd on the ingress port so these TX_OK packets are all bgp and control traffic:
```
root@cmp235-3:~# show interfaces counters
Last cached time was 2024-12-10T22:16:35.704269
      IFACE    STATE    RX_OK      RX_BPS    RX_UTIL    RX_ERR    RX_DRP
-----------  -------  -------  ----------  ---------  --------  --------
Ethernet144        U   15,399  141.74 B/s      0.00%         0     1,000
```

**Comment by arista-nwolfe** [comment]
@arlakshm could you reopen this issue? I don't seem to have permissions to do this.
