### ISSUE TITLE
Pre-test sanity check failed due to 'down_neighbors' after running test_bgp_session_flap.py on t1

### ISSUE THREAD

**Issue by Gfrom2016** [sonic-net/sonic-mgmt#7963]
**Description**

After running [test_bgp_session_flap.py](https://github.com/sonic-net/sonic-mgmt/pull/6621), the test setup throws the 'down_neighbor' error and cause the next case failed at sanity check.
This only happens on T1 topology.

![image](https://user-images.githubusercontent.com/19384917/230264396-e39479dd-6951-4d15-8390-0d393e5258b7.png)

**Steps to reproduce the issue:**
1. Run test_bgp_session_flap.py on the master/internal branch.
2. Run the next test case, it will fail on sanity check.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
Skip this test case for T1 for now https://github.com/sonic-net/sonic-mgmt/pull/7964.

**Comment by Gfrom2016** [comment]
@Azarack Can you please check this on T1 and see if the BGP session fully recovered after running the case?

**Comment by Azarack** [comment]
I created https://github.com/sonic-net/sonic-mgmt/pull/8018 with a fix for this issue.
