### ISSUE TITLE
Is t1-lag or ptf32 topo supported by pytest testcases

### ISSUE THREAD

**Issue by oldboyzzzz** [sonic-net/sonic-mgmt#8036]
Hi Experts,

I don't see t1-lag or ptf marker in testcases under tests folder. Does that mean those 2 topoes are not supported by pytest scripts?
I'm using 202205 branch.

Thanks,
John

**Comment by bingwang-ms** [comment]
The test script with `pytest.mark.topology("t1")` also runs on `t1-lag` testbed. We don't have `ptf` topology test cases at this moment.

**Comment by rhsmci** [comment]
> The test script with `pytest.mark.topology("t1")` also runs on `t1-lag` testbed. We don't have `ptf` topology test cases at this moment.

@bingwang-ms As we know, there are no BGP sessions in ptf topologies, therefore the test cases in BGP, decap, fib, etc. will fail with ptf32. From your comments, it seems the test cases are not designed for ptf. Is it adaquate to add pytest.mark.skipif for ptf topologies? Thank you.
