### ISSUE TITLE
PR #7894 breaks vSonic based setup for T2 profile

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#8109]
**Description**

PR #7894 breaks vSonic based setup for T2 profile. The change expects all vSonic VMs to have Port Channels. In case of https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/vars/topo_t2_2lc_min_ports-masic.yml - Even numbered vSonic VM have PC so they work fine while odd numbered VM have issues

It also is missing leaf_asn_start in t2 yaml files.

TASK [sonic : create topo config] ********************************************************************************************************
Friday 21 April 2023  15:06:02 +0000 (0:00:01.459)       0:07:59.739 **********
fatal: [VM0100]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0101]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0102]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0103]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0104]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"}
fatal: [VM0105]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'Port-Channel1'"}
fatal: [VM0106]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'leaf_asn_start'"} 

@saiarcot895 can you please take a look ?

@abdosi  for viz

**Comment by yxieca** [comment]
@saiarcot895 can you help take a look?
