### ISSUE TITLE
When deploying vSONIC as neighbor the management interface is lost during add-topo in some instances

### ISSUE THREAD

**Issue by mrkcmo** [sonic-net/sonic-mgmt#8191]
**Description**
We have ran into an issue when deploying a T2 topology with physical T2 DUT with vSONIC neighbors. The start_vms script works as expected but when the add-topo script is ran we see random instances where the VMS(vSONIC) VM's will go unreachable and fail to get fully configured. 
While troubleshooting the issue we found that in the VMS's that went unreachable the full configuration was applied but the management configuration was missing. So it appears that at some point during the add-topo script the management interface configuration is set but never saved it seems. Then later in the script more configuration is apply and the config is saved but the previous management configuration is lost on some of the VMS(vSONIC) VM's causing the script to think they are unreachable. 

**Steps to reproduce the issue:**
1. start the VMS servers:  "./testbed-cli.sh -n 8 -k vsonic start-vms server_1 password.txt"
2. run the app-topo: "./testbed-cli.sh -t auto-tb.yaml -k vsonic add-topo auto-t2 password.txt"
3. observe that random VMS(vSONIC) VM's will go unreachable at times

**Describe the results you received:**
The management interface randomly disappears from the VMS(vSONIC) VM's.

**Describe the results you expected:**
That the management interface for the VMS(vSONIC) VM's remains intact after add-topo script is ran.

**Additional information you deem important:**
**Output of `show run all` where management interface is missing:**

    ```
    "KDUMP": {
        "config": {
            "enabled": "false",
            "memory": "0M-2G:256M,2G-4G:320M,4G-8G:384M,8G-:448M",
            "num_dumps": "3"
        }
    },
    "LOOPBACK_INTERFACE": {
        "Loopback0": {},
        "Loopback0|10.1.0.1/32": {}
    },
    "PASSW_HARDENING": {
        "POLICIES": {
            "digits_class": "true",
            "expiration": "180",
            "expiration_warning": "15",
            "history_cnt": "10",
            "len_min": "8",
            "lower_class": "true",
            "reject_user_passw_match": "true",
            "special_class": "true",
            "state": "disabled",
            "upper_class": "true"
        }
    ```

**Full configuration file with missing management interface:**
[vsonicwithmissingmgmt-config.txt](https://github.com/sonic-net/sonic-mgmt/files/11373540/vsonicwithmissingmgmt-config.txt)

**Will be adding a full debug capture of add-topo with issue below by using -vvv**

**Comment by mrkcmo** [comment]
@rlhui @sanmalho-git this issue is blocking as it happens more times than not and it takes repeated runs of cleanup and add-topo to get the testbed back in working order. 

@Azarack tagging you for visibility.

**Comment by yxieca** [comment]
@Pterosaur can you help with this issue?

**Comment by yxieca** [comment]
@Pterosaur question: do we have a recommended vSONiC image for community members?

**Comment by yxieca** [comment]
@mrkcmo can you share a few information:
- A diff between good configuration and bad configuration on the vSONiC.
- Your server configuration (CPU/memory, etc).

**Comment by Pterosaur** [comment]
> @Pterosaur question: do we have a recommended vSONiC image for community members?

Hi, we don't have a specific image for community members. I believe the master image and 202205 are both available.

**Comment by Pterosaur** [comment]
> @Pterosaur can you help with this issue?

Sure, I will check it locally.

**Comment by Pterosaur** [comment]
If I want to reproduce your testbed, where can I find the ` auto-tb.yaml` and ` auto-t2 `?

**Comment by Pterosaur** [comment]
I tried to create the topo, `vms-kvm-t2`, with 8 neighbors. It looks good in my local environment.
My server is 64GB memory and 16 CPU cores.

**Comment by mrkcmo** [comment]
> @mrkcmo can you share a few information:
> 
> * A diff between good configuration and bad configuration on the vSONiC.
> * Your server configuration (CPU/memory, etc).

Let me grab one that is good vs bad. I already attached one where the MGMT interface was missing. Let me add one where it is not lost.

**Comment by mrkcmo** [comment]
> I tried to create the topo, `vms-kvm-t2`, with 8 neighbors. It looks good in my local environment. My server is 64GB memory and 16 CPU cores.

That is the virtual T2 topology. We are using a physical T2 in our instance.

**Comment by mrkcmo** [comment]
> > @Pterosaur question: do we have a recommended vSONiC image for community members?
> 
> Hi, we don't have a specific image for community members. I believe the master image and 202205 are both available.

We are using the 202205 image for our testing.

**Comment by mrkcmo** [comment]
> The failure rate is high, 1 out of 4 times the deploy succeeds.

That is about the same rate we are seeing. Are you seeing the same issue where it goes "unreachable" and the issue is the mgmt interface is missing @yxieca ?

**Comment by yxieca** [comment]
> > The failure rate is high, 1 out of 4 times the deploy succeeds.
> 
> That is about the same rate we are seeing. Are you seeing the same issue where it goes "unreachable" and the issue is the mgmt interface is missing @yxieca ?

I defer this question to @Pterosaur

**Comment by Pterosaur** [comment]
Hi Chris, I didn't find the topo, auto-t2, you mentioned in our lab. But as I said before, it looks good in my testbed for a virtual environment with 8 scales.
Is it possible to reproduce your topo description in my local environment?

**Comment by mrkcmo** [comment]
In the end we moved to the latest master per feedback from the community and this seems to have solved the reachability issue with the vSONIC VMS as neighbors. We did however run into a different issue with the latest master image of vSONIC where all interfaces are show an auto-neg of 4.2M GB on the interfaces. Will file this issue with the vSONIC community.
