### ISSUE TITLE
 test_sai_sdk_dump fails after not finding an interface which is not a member of PC.

### ISSUE THREAD

**Issue by siqbal1986** [sonic-net/sonic-mgmt#8192]
**Description**
When running on a testbed, this testcrashes if it cannot find an interface which is not a member of a portChannel.
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[show_techsupport/test_auto_techsupport.py:1273: in get_random_physical_port_non_po_member](https://dev.azure.com/mssonic/internal/_git/5380e8f7-6e2a-4154-8dee-f3be7b096894?path=show_techsupport%2Ftest_auto_techsupport.py&version=GBinternal&_a=contents&line=1273&lineEnd=1274&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
test_port = random.choice(non_po_ports)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = &lt;random.Random object at 0x5654d9850d40&gt;, seq = []
def choice(self, seq):
&quot;&quot;&quot;Choose a random element from a non-empty sequence.&quot;&quot;&quot;
&gt;       return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
E       IndexError: list index out of range
self       = &lt;random.Random object at 0x5654d9850d40&gt;
seq        = []

**Steps to reproduce the issue:**
1. run test_sai_sdk_dump test on a mellanox 4600 device where the configuration has all ports member of some or other portchannels.
2.
3.

**Describe the results you received:**
crash due to index out of range.

**Describe the results you expected:**
graceful failure with a message.

**Additional information you deem important:**

    **Output of `show version`:**
 ```
SONiC Software Version: SONiC.internal.72539810-ee2e7de8f6
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: ee2e7de8f6
Build date: Sun Apr 30 17:09:43 UTC 2023
Built by: cloudtest@0645e225c000001

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2115X26246
Model Number: MSN4600-CS2RO
Hardware Revision: A1
Uptime: 00:18:18 up 18:48,  1 user,  load average: 3.22, 2.83, 2.74
Date: Wed 03 May 2023 00:18:18
```
    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
@ppikh Can you help take a look?

**Comment by ppikh** [comment]
Hi @siqbal1986 

Which topology do you use?

**Comment by siqbal1986** [comment]
> Hi @siqbal1986 
> 
> Which topology do you use?

T1

**Comment by siqbal1986** [comment]
yes you are correct. its a t1-64-lag
