### ISSUE TITLE
generic_config_updater:: ptfwd realted tests failing due to various errros.

### ISSUE THREAD

**Issue by siqbal1986** [sonic-net/sonic-mgmt#8197]
**Description**
The following tests are failing due to "No interface found running pfcwd - unable to run test" and "Command did not run successfully."
test_stop_pfcwd
test_pfcwd_interval_config_updates[True-nonexistent-add]

The configuration is Mlnx 4600 T1 with master.

**Steps to reproduce the issue:**
1. run the test.
2.
3.

**Describe the results you received:**
**stack trace fpr no interface found error.**
 duthost = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;, ensure_dut_readiness = None
def test_stop_pfcwd(duthost, ensure_dut_readiness):
pfcwd_config = duthost.shell(&quot;show pfcwd config&quot;)
pytest_assert(not pfcwd_config[&#39;rc&#39;], &quot;Unable to read pfcwd config&quot;)
for line in pfcwd_config[&#39;stdout_lines&#39;]:
if line.startswith(&#39;Ethernet&#39;):
interface = line.split()[0]
break
else:
pytest_assert(False, &quot;No interface found running pfcwd - unable to run test&quot;)
json_patch = [
{
&quot;op&quot;: &quot;remove&quot;,
[&quot;path&quot;: &quot;/PFC_WD/{}/detection_time&quot;.format(interface),]
},
{
&quot;op&quot;: &quot;remove&quot;,
[&quot;path&quot;: &quot;/PFC_WD/{}/restoration_time&quot;.format(interface),]
},
{
&quot;op&quot;: &quot;remove&quot;,
[&quot;path&quot;: &quot;/PFC_WD/{}/action&quot;.format(interface)]
}
]
try:
tmpfile = generate_tmpfile(duthost)
output = apply_patch(duthost, json_data=json_patch, dest_file=tmpfile)
&gt;           expect_op_success(duthost, output)
duthost    = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
ensure_dut_readiness = None
interface  = &#39;Ethernet136&#39;
[json_patch = [{&#39;op&#39;: &#39;remove&#39;, &#39;path&#39;: &#39;/PFC_WD/Ethernet136/detection_time&#39;}, {&#39;op&#39;: &#39;remove&#39;, &#39;path&#39;: &#39;/PFC_WD/Ethernet136/restoration_time&#39;}, {&#39;op&#39;: &#39;remove&#39;, &#39;path&#39;: &#39;/PFC_WD/Ethernet136/action&#39;}]]
line       = &#39;Ethernet136      drop               400                 400&#39;
output     = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.VlgGOE9pwu&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}
pfcwd_config = {&#39;cmd&#39;: &#39;show pfcwd config&#39;, &#39;stdout&#39;: &#39;Changed polling interval to 400ms\n       PORT    ACTION    DETECTION TIME    ...et252      drop               400                 400&#39;], &#39;stderr_lines&#39;: [], &#39;_ansible_no_log&#39;: False, &#39;failed&#39;: False}
start_pfcwd = {&#39;cmd&#39;: &#39;config pfcwd start_default&#39;, &#39;stdout&#39;: &#39;&#39;, &#39;stderr&#39;: &#39;&#39;, &#39;rc&#39;: 0, &#39;start&#39;: &#39;2023-05-01 14:58:33.351723&#39;, &#39;end...e, &#39;removes&#39;: None, &#39;stdin&#39;: None}}, &#39;stdout_lines&#39;: [], &#39;stderr_lines&#39;: [], &#39;_ansible_no_log&#39;: False, &#39;failed&#39;: False}
tmpfile    = &#39;/tmp/tmp.VlgGOE9pwu&#39;
generic_config_updater/test_pfcwd_interval.py:170:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
duthost = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
[output = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.VlgGOE9pwu&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}]
def expect_op_success(duthost, output):
&quot;&quot;&quot;Expected success from apply-patch output
&quot;&quot;&quot;
&gt;       pytest_assert(not output[&#39;rc&#39;], &quot;Command is not running successfully&quot;)
E       Failed: Command is not running successfully
duthost    = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
output     = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.VlgGOE9pwu&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}
[generic_config_updater/gu_utils.py:48: Failed]

**Stacktrace for "Failed: Command is not running successfully.**

duthost = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;, ensure_dut_readiness = None
operation = &#39;add&#39;, field_pre_status = &#39;existing&#39;, is_valid_config_update = True
@pytest.mark.parametrize(&quot;operation&quot;, [&quot;add&quot;, &quot;replace&quot;])
@pytest.mark.parametrize(&quot;field_pre_status&quot;, [&quot;existing&quot;, &quot;nonexistent&quot;])
@pytest.mark.parametrize(&quot;is_valid_config_update&quot;, [True, False])
def test_pfcwd_interval_config_updates(duthost, ensure_dut_readiness, operation,
field_pre_status, is_valid_config_update):
new_interval = get_new_interval(duthost, is_valid_config_update)
operation_to_new_value_map = {&quot;add&quot;: &quot;{}&quot;.format(new_interval), &quot;replace&quot;: &quot;{}&quot;.format(new_interval)}
detection_time, restoration_time = get_detection_restoration_times(duthost)
pre_status = max(detection_time, restoration_time)
field_pre_status_to_value_map = {&quot;existing&quot;: &quot;{}&quot;.format(pre_status), &quot;nonexistent&quot;: &quot;&quot;}
prepare_pfcwd_interval_config(duthost, field_pre_status_to_value_map[field_pre_status])
tmpfile = generate_tmpfile(duthost)
logger.info(&quot;tmpfile {} created for json patch of pfcwd poll interval and operation: {}&quot;.format(tmpfile, operation))
value = operation_to_new_value_map[operation]
logger.info(&quot;value to be added to json patch: {}&quot;.format(value))
json_patch = [
{
&quot;op&quot;: &quot;{}&quot;.format(operation),
[&quot;path&quot;: &quot;/PFC_WD/GLOBAL/POLL_INTERVAL&quot;,]
&quot;value&quot;: &quot;{}&quot;.format(value)
}]
try:
output = apply_patch(duthost, json_data=json_patch, dest_file=tmpfile)
if is_valid_config_update:
&gt;               expect_op_success(duthost, output)
detection_time = 400
duthost    = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
ensure_dut_readiness = None
field_pre_status = &#39;existing&#39;
field_pre_status_to_value_map = {&#39;existing&#39;: &#39;400&#39;, &#39;nonexistent&#39;: &#39;&#39;}
is_valid_config_update = True
[json_patch = [{&#39;op&#39;: &#39;add&#39;, &#39;path&#39;: &#39;/PFC_WD/GLOBAL/POLL_INTERVAL&#39;, &#39;value&#39;: &#39;390&#39;}]]
new_interval = 390
operation  = &#39;add&#39;
operation_to_new_value_map = {&#39;add&#39;: &#39;390&#39;, &#39;replace&#39;: &#39;390&#39;}
output     = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.gXdL8scucG&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}
pre_status = 400
restoration_time = 400
tmpfile    = &#39;/tmp/tmp.gXdL8scucG&#39;
value      = &#39;390&#39;
generic_config_updater/test_pfcwd_interval.py:213:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
duthost = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
[output = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.gXdL8scucG&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}]
def expect_op_success(duthost, output):
&quot;&quot;&quot;Expected success from apply-patch output
&quot;&quot;&quot;
&gt;       pytest_assert(not output[&#39;rc&#39;], &quot;Command is not running successfully&quot;)
E       Failed: Command is not running successfully
duthost    = &lt;MultiAsicSonicHost str2-msn4600c-acs-01&gt;
output     = {&#39;failed&#39;: True, &#39;msg&#39;: &#39;non-zero return code&#39;, &#39;cmd&#39;: &#39;config apply-patch /tmp/tmp.gXdL8scucG&#39;, &#39;stdout&#39;: &#39;Patch Appl...eric_config_updater.field_operation_validators.rdma_config_update_validator returned False&#39;], &#39;_ansible_no_log&#39;: False}
[generic_config_updater/gu_utils.py:48: Failed]
**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**
 ```
SONiC Software Version: SONiC.internal.72539810-ee2e7de8f6
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-amd64
Build commit: ee2e7de8f6
Build date: Sun Apr 30 17:09:43 UTC 2023
Built by: cloudtest@0645e225c000001

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2115X26246
Model Number: MSN4600-CS2RO
Hardware Revision: A1
Uptime: 00:18:18 up 18:48,  1 user,  load average: 3.22, 2.83, 2.74
Date: Wed 03 May 2023 00:18:18
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by siqbal1986** [comment]
@SavchukRomanLv could you please look into this.

**Comment by SavchukRomanLv** [comment]
@siqbal1986 did you run with https://github.com/sonic-net/sonic-mgmt/pull/8081?

**Comment by yxieca** [comment]
> @siqbal1986 did you run with #8081?

@siqbal1986 please check and report back. Thanks!

**Comment by siqbal1986** [comment]
yes it was included in the test run.
