### ISSUE TITLE
[test gap] Validate /etc/resolv.conf in each docker container

### ISSUE THREAD

**Issue by wangxin** [sonic-net/sonic-mgmt#8242]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
If /etc/resolv.conf is broken in docker container, some critical service may fail to start.

**Describe the results you expected:**
Need to add test cases to cover the validation of /etc/resolv.conf in each docker container.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by StormLiangMS** [comment]
hi @qiluo-msft  this one seems a dns related test gap, assigned to you for further triage.

**Comment by ganglyu** [comment]
ETA: 2024-07-30
