### ISSUE TITLE
T2: crm/test_crm.py::test_crm_route test failure in multi-asic/chassis platforms

### ISSUE THREAD

**Issue by rajendrat** [sonic-net/sonic-mgmt#8425]
**Description**

crm/test_crm.py::test_crm_route test failure for multi-asic/chassis platforms.
The test checks for crm route used entires before and after adding 64 routes, the crm show resources output shows the increased used entires.  

But the newly added API get_crm_resources_fdb_and_ip_route [#7564](https://github.com/sonic-net/sonic-mgmt/pull/7564) does not check the correct asic / ipv4_route, this fails all the tests using other than ASIC0.

**Steps to reproduce the issue:**
1. run test crm/test_crm.py::test_crm_route[sfd-lt2-lc0-2-ipv4] // other than Asic0 
2.
3.

**Describe the results you received:**
get_crm_resources_fdb_and_ip_route gets the crm_stats from ASIC0 
(Pdb) p new_crm_stats_route_used 
51383
(Pdb) p crm_stats_route_used 
51383

But the ASIC2 output is  "ipv4_route                   51449   " .

ASIC0

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                   51383             329751
ipv6_route                   51384             329751
ipv4_nexthop                    76               3942
ipv6_nexthop                    76               3942
ipv4_neighbor                   76             622165
ipv6_neighbor                   76             311082
nexthop_group_member           552             228872
nexthop_group                   28              16356
fdb_entry                        0             622165

ASIC1

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                   51387             329814
ipv6_route                   51388             329814
ipv4_nexthop                    80               3934
ipv6_nexthop                    80               3934
ipv4_neighbor                   80             622145
ipv6_neighbor                   80             311072
nexthop_group_member           540             228884
nexthop_group                   30              16354
fdb_entry                        0             622145

ASIC2

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                   51449             329715
ipv6_route                   51386             329715
ipv4_nexthop                    78               3938
ipv6_nexthop                    78               3938
ipv4_neighbor                   78             622155
ipv6_neighbor                   78             311077
nexthop_group_member           556             228864
nexthop_group                   28              16356
fdb_entry                        0             622155

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rajendrat** [comment]
viz @abdosi @congh-nvidia

**Comment by congh-nvidia** [comment]
> viz @abdosi @congh-nvidia

Hi @rajendrat 
Nvidia doesn't have multi-asic platforms, could you please help fix the logic for multi-asic?
Thanks.

**Comment by abdosi** [comment]
@rajendrat can you update script to handle multi-asic ?

cc @arlakshm 
@judyjoseph for viz.

**Comment by rajendrat** [comment]
@arlakshm @abdosi
Please merge this fix to 202205 branch as well.
