### ISSUE TITLE
TC Issue: tests.bgp.test_bgpmon.test_bgpmon And Template update bgpd/templates/BGPMON/peer-group.conf.j2

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-mgmt#8569]
The test tests/bgp/test_bgpmon.py  fails sometimes when ran on multi asic DUT (part of VoQ Chassis) with t2 topology.

The Test Case uses Loopback0 as the source ip for the BGP mon neighbor and selects a random port on ptf from all connected ports.

Since loopback0 ip is not unique across asics, if the bgpmon is configured on asic0 but peer port on ptf is part of asic1 the packet coming from ptf side is consumed as expected not forwarded to correct asic and hence test will fail.

From discussions we had to run correctly in case of multi asic, it was suggested to use Loopback4096 as both asics have unique ip for 4096 unlike Loopback0. 

After analyzing the modifications needed to current test code to support this we also found that template bgpd/templates/BGPMON/peer-group.conf.j2 configures the BGPMon peer group to use     loopback0 as source ip: 

"neighbor BGPMON update-source {{ loopback0_ipv4 | ip }}" 

 

This template needs to be updated to use loopback4096 for multi asic DUTs.

**Comment by yxieca** [comment]
@judyjoseph this issue seems to ask for an image change. If you agree, please move to sonic-buildimage repo. Thanks.

**Comment by judyjoseph** [comment]
@yxieca will check how it is working in other multi-DUT platforms. We need to fix the testcase as needed to support multi-asic if needed.

**Comment by rlhui** [comment]
@tjchadaga please help check this?   thanks.

**Comment by tjchadaga** [comment]
BGP template is already updated for chassis to use loopback4096 - https://github.com/sonic-net/sonic-buildimage/pull/14844
Also, BGPMon session uses ipv6 address of loopback4096 as source.

test_bgpmon.py is no longer run on chassis and a new test - test_bgpmon_v6.py is run to test the changed functionality - https://github.com/sonic-net/sonic-mgmt/pull/9233

**Comment by tjchadaga** [comment]
@vikshaw-Nokia - please close this issue if there are no other concerns

**Comment by vikshaw-Nokia** [comment]
Closing the issue with PR https://github.com/sonic-net/sonic-buildimage/pull/14844 was merged. @tjchadaga  Thank You.
