### ISSUE TITLE
[Multi-asic/Multi-Dut/T2] crm/test_crm.py::test_acl_counter fails for T2 profile

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#8609]
**Description**

The test case fails because collector fixture used doesnot have the dut information for the dut being tested, so it randomly picks up the dut for the test. Because of which on a system with varying LCs (different number of asics) it fails. 

For e.g. In the below case, it is testing on LC0 but gathers information on Supervisor, causing it to hit missing keyerror issue

_______________________ test_acl_counter[sfd-lt2-lc0-2] ________________________

duthosts = [<MultiAsicSonicHost sfd-lt2-lc0>, <MultiAsicSonicHost sfd-lt2-lc1>, <MultiAsicSonicHost sfd-lt2-lc2>, <MultiAsicSonicHost sfd-lt2-sup>]
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-lt2-lc0'
enum_frontend_asic_index = 2, collector = {0: {}, 1: {}, 4: {}, 5: {}, ...}

    def test_acl_counter(duthosts, enum_rand_one_per_hwsku_frontend_hostname,enum_frontend_asic_index, collector):
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
        asichost = duthost.asic_instance(enum_frontend_asic_index)
>       asic_collector = collector[asichost.asic_index]
E       KeyError: 2

asichost   = <SonicAsic 2>
collector  = {0: {}, 1: {}, 4: {}, 5: {}, ...}
duthost    = <MultiAsicSonicHost sfd-lt2-lc0>
duthosts   = [<MultiAsicSonicHost sfd-lt2-lc0>, <MultiAsicSonicHost sfd-lt2-lc1>, <MultiAsicSonicHost sfd-lt2-lc2>, <MultiAsicSonicHost sfd-lt2-sup>]
enum_frontend_asic_index = 2
enum_rand_one_per_hwsku_frontend_hostname = 'sfd-lt2-lc0'

crm/test_crm.py:950: KeyError

**Comment by vperumal** [comment]
FYI @abdosi

**Comment by abdosi** [comment]
works fine.
