### ISSUE TITLE
[Multi-asic/Multi-Dut/T2]: route/test_route_flap.py::test_route_flap fails due to use of BP PC

### ISSUE THREAD

**Issue by vperumal** [sonic-net/sonic-mgmt#8612]
**Description**

Testcase passes when front facing ports are chosen for finding out the Exabgp port 

show ip int | grep -w Ethernet60 | awk '{print $4}' 

But fails when it choses a Backplane PC, which is expected. 

The test should skip BP ports, which in this case it doesn't, hence hitting the key error.

duthost = <MultiAsicSonicHost sfd-lt2-lc2>
tbinfo = {'auto_recover': 'True', 'comment': 'Tests SFD T2 - Closed PID setup', 'conf-name': 'sfd-lt2', 'duts': ['sfd-lt2-lc0', 'sfd-lt2-lc1', 'sfd-lt2-lc2', 'sfd-lt2-sup'], ...}
dev_port = 'PortChannel01'

    def get_exabgp_port(duthost, tbinfo, dev_port):
        tor1 = duthost.shell("show ip int | grep -w {} | awk '{{print $4}}'".format(dev_port))['stdout']
>       tor1_offset = tbinfo['topo']['properties']['topology']['VMs'][tor1]['vm_offset']
E       KeyError: u''

dev_port   = 'PortChannel01'
duthost    = <MultiAsicSonicHost sfd-lt2-lc2>
tbinfo     = {'auto_recover': 'True', 'comment': 'Tests SFD T2 - Closed PID setup', 'conf-name': 'sfd-lt2', 'duts': ['sfd-lt2-lc0', 'sfd-lt2-lc1', 'sfd-lt2-lc2', 'sfd-lt2-sup'], ...}
tor1       = u''

route/test_route_flap.py:191: KeyError
==================================== PASSES ====================================
________________________ test_route_flap[sfd-lt2-lc1-0] ________________________
- generated xml file: /data/tests/logs/route/test_route_flap_2023-06-14-23-45-33.xml -
=========================== short test summary info ============================
FAILED route/test_route_flap.py::test_route_flap[sfd-lt2-lc0-1] - KeyError: u''
FAILED route/test_route_flap.py::test_route_flap[sfd-lt2-lc2-0] - KeyError: u''
PASSED route/test_route_flap.py::test_route_flap[sfd-lt2-lc1-0]
==================== 2 failed, 1 passed in 1692.47 seconds =====================

**Comment by vperumal** [comment]
FYI @abdosi

**Comment by abdosi** [comment]
can you look into fixng this ?

cc @wenyiz2021 can you see if this is quick fix you can do ?

**Comment by wenyiz2021** [comment]
@vperumal @abdosi I'll take a look

**Comment by vperumal** [comment]
Hi @wenyiz2021, Yes the testing branch was the latest, but I had tested it on the chassis and there the PCs 01-48 face backplane. External facing PCs are 101 onwards. I will add the breakpoint and get u the details needed

**Comment by wenyiz2021** [comment]
hi @vperumal, I had this PR merge yday, can you please try with the PR fix?
(https://github.com/sonic-net/sonic-mgmt/pull/8623)

the issue is previous design had 2 filters: one makes sure routes origins from external, the other makes sure interface name does not have 'IB'.
the 1st filter could not guarantee paths origin from external are also external routes, the 2nd is incomplete filter. e.g. Cisco chassis has 'BP' and 'PortChannel01' as interface names, and are BP intf.
new change is on 2nd filter, to get interfaces IP also, and make sure their IP are not one of internal BGP IPs.

**Comment by vperumal** [comment]
Thanks @wenyiz2021 - will pick it up and let u know the result

**Comment by abdosi** [comment]
can you check back ?
