### ISSUE TITLE
Test module test_route_flow_counter is skipped due to missing topology marker

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#8724]
**Description**
The test cases in module `test_route_flow_counter.py` are skipped because no topology marker present in the module.
https://github.com/sonic-net/sonic-mgmt/blob/master/tests/route/test_route_flow_counter.py

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by bingwang-ms** [comment]
@Junchao-Mellanox  Can you please help check this issue?

**Comment by SavchukRomanLv** [comment]
HI @bingwang-ms, please merge and backport to  202205 branch
