### ISSUE TITLE
[test-gap] Add a testcase to validate L2 switch config and functionality across reboots/upgrades

### ISSUE THREAD

**Issue by vaibhavhd** [sonic-net/sonic-mgmt#8777]
**Description**

1) Cold reboot a device.
2) Perform L2 config steps via [L2 Switch mode · sonic-net/SONiC Wiki (github.com)](https://github.com/sonic-net/SONiC/wiki/L2-Switch-mode)
3) Install target image.
4) Cold reboot
5) Check config_db

Expectation: config db should not have configuration coming from minigraph (as there is no minigraph.xml).

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by qiluo-msft** [comment]
This is to prevent potential bug in db_migrator.

**Comment by StormLiangMS** [comment]
hi @qiluo-msft  this one seems a manage plane related test gap, assigned to you for further triage.

**Comment by qiluo-msft** [comment]
@vaibhavhd Do we really need this step?
Install target image.

I believe a reboot is good enough.

**Comment by qiluo-msft** [comment]
Closed by https://github.com/sonic-net/sonic-mgmt/pull/14714
