### ISSUE TITLE
[test gap] Enhance testQosSaiDscpQueueMapping and testQosSaiDscpToPgMapping to cover IPinIP traffic

### ISSUE THREAD

**Issue by bingwang-ms** [sonic-net/sonic-mgmt#8789]
**Description**

Currently, the test case `testQosSaiDscpQueueMapping` and `testQosSaiDscpToPgMapping` only verify the DSCP to Queue/Pg mapping for regular traffic. The mapping of IPinIP traffic (decapsulated in IPinIP tunnel) is not tested.
We need to enhance the existing `testQosSaiDscpQueueMapping` and `testQosSaiDscpToPgMapping`, or add new test cases to verify the mapping for IPinIP traffic.
 

**Steps to reproduce the issue:**
1. Generate IPinIP traffic from ptf. The destination IP in the outer layer of the packets should be the loopback (10.1.0.32) of DUT.
2. Ingress the packets to DUT, verify the packets are decapsulated.
3. Check the queue counter or PG counter with sai_thrift_api from ptf, ensure the mapping is as expected.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by developfast** [comment]
Acknowledged

**Comment by neethajohn** [comment]
Only dscp-q mapping is covered in the PR #9098. New issue raised for DSCP-PG mapping (#9576)

**Comment by yxieca** [comment]
Close this issue. The work left is tracked by #9567
