### ISSUE TITLE
Test Case test_default_route_with_bgp_flap tc fails by addition of 'AZNGHub' device type for Upstream T3 Neighbors  in minigraph templates

### ISSUE THREAD

**Issue by vikshaw-Nokia** [sonic-net/sonic-mgmt#9052]
**Description**
PR:https://github.com/sonic-net/sonic-mgmt/pull/8779 leads to failure of  Test Case tests.route.test_default_route.test_default_route_with_bgp_flap  by addition of 'AZNGHub' device type for Upstream T3 Neighbors  in minigraph templates.
The Test cases uses the function get_upstream_neigh, which considers only T3 Neighbors  which are not of type "AZNGHub".
As the PR have changed the device type, and adds "AZNGHub" and in default 50% type, it impacts the test case, as the test case needs the count of uplink route nexthops needs to same as the number Upstream Neighbor as per the topology.

**Describe the results you received:**
"Default route nexthops doesn't match the testbed topology"
The count of the Uplink Route is not matching with the  Upstream Neighbor as per the topology(reading data from configfacts)

**Describe the results you expected:**
The count of the Uplink Route should match with the  Upstream Neighbor as per the topology(reading data from configfacts)

**Additional information you deem important:**

The Condition failing 
![image](https://github.com/sonic-net/sonic-mgmt/assets/135994174/fe9f3eec-a4a5-44c1-ac89-756da73d87b8)
because of 
![image](https://github.com/sonic-net/sonic-mgmt/assets/135994174/ba09856e-ae3b-43de-bb02-de1de3f9604d)

**Comment by mlok-nokia** [comment]
@arlakshm @rlhui  This is one of the new issues on the latest sonic-mgmt rebase which is caused by PR8779.  Plwas take a look  at that.

**Comment by abdosi** [comment]
@arlakshm is this issue still applicable ?

**Comment by rlhui** [comment]
https://github.com/sonic-net/sonic-mgmt/pull/14804/ is to fix this
