### ISSUE TITLE
[test gap][dhcpv6_relay] Add testcase for multi-vlan

### ISSUE THREAD

**Issue by kellyyeh** [sonic-net/sonic-mgmt#9122]
**Description**
Previously dhcp6relay was not always forwarding packets with correct vlan ip because one client socket was used for multiple interfaces and vlan interfaces were not filtered

**Steps to reproduce the issue:**
1. Configure multiple Vlans and dhcp servers
2. Send dhcp requests
3. Check dhcp packets relayed contains expected Vlan IP

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yaqiangz** [comment]
https://github.com/sonic-net/sonic-dhcp-relay/pull/27
