### ISSUE TITLE
snmp/test_snmp_loopback.py testcase fails on BSL setup because there are no bgp neighbors

### ISSUE THREAD

**Issue by CharudattaSChitale** [sonic-net/sonic-mgmt#9322]
**Description**

**Steps to reproduce the issue:**
 1 Convert the DUT to L2 mode
 https://github.com/Azure/SONiC/wiki/L2-Switch-mode 
https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/testbed_set_l2_mode.yml 
2 run below testcases on DUT 
   snmp/test_snmp_loopback.py

**Results observed:** 
Testcase failed with below error AssertionError: Sysdescr not found in SNMP result

**Issue Analysis:**
Test tries to do snmp query over the loopback ip from one of the bgp neighbors. Since there are no BGP neighbors in BSL mode, is this testcase applicable for BSL mode? 
If not, @pytest.mark.bsl can be removed from this testcase.

**Comment by jcaiMR** [comment]
Would you please have a try again with the fix of  https://github.com/sonic-net/sonic-mgmt/pull/9254

**Comment by yxieca** [comment]
@qiluo-msft are you taking action on this test case?

@kevinskwang for viz.

**Comment by qiluo-msft** [comment]
Fixed by https://github.com/sonic-net/sonic-mgmt/pull/9441
