### ISSUE TITLE
[202205] test_decap failing after PTF python3 migration

### ISSUE THREAD

**Issue by veronica-arista** [sonic-net/sonic-mgmt#9595]
Changes in https://github.com/sonic-net/sonic-mgmt/pull/9522 cause the test to fail due to `unicode()` calls (which are not required in Python3)

**Steps to reproduce the issue:**
1. run test_decap.py on 202205 branch with changes from PR9522
2.
3.

**Describe the results you received:**
Test should pass

**Describe the results you expected:**
Test fails with `NameError: name 'unicode' is not defined`

**Comment by kenneth-arista** [comment]
@wenyiz2021 @arlakshm

**Comment by yxieca** [comment]
@veronica-arista issue has been addressed by #9596. Please confirm.
